---
title: "Toán 12"
format: html
---

# Các chuyên mục
- [Cánh Diều](canh-dieu/index.qmd)
    - [Sách lý thuyết](canh-dieu/sach-ly-thuyet/index.qmd)
    - [Sách bài tập](canh-dieu/sach-bai-tap/index.qmd)
    - [Sách chuyên đề học tập](canh-dieu/sach-chuyen-de-hoc-tap/index.qmd)
    - [Bạn đã nghĩ đến chưa?](canh-dieu/ban-da-nghi-den-chua/index.qmd)

- [Chân Trời Sáng Tạo](chan-troi-sang-tao/index.qmd)
    - [Sách lý thuyết](chan-troi-sang-ta/sach-ly-thuyet/index.qmd)
    - [Sách bài tập](chan-troi-sang-tao/sach-bai-tap/index.qmd)
    - [Sách chuyên đề học tập](chan-troi-sang-tao/sach-chuyen-de-hoc-tap/index.qmd)
    - [Bạn đã nghĩ đến chưa?](chan-troi-sang-tao/ban-da-nghi-den-chua/index.qmd)

- [Kết Nối Tri Thức Với Cuộc Sống](ket-noi-tri-thuc-voi-cuoc-song//index.qmd)
    - [Sách lý thuyết](ket-noi-tri-thuc-voi-cuoc-song/sach-ly-thuyet/index.qmd)
    - [Sách bài tập](ket-noi-tri-thuc-voi-cuoc-song/sach-bai-tap/index.qmd)
    - [Sách chuyên đề học tập](ket-noi-tri-thuc-voi-cuoc-song/sach-chuyen-de-hoc-tap/index.qmd)
    - [Bạn đã nghĩ đến chưa?](ket-noi-tri-thuc-voi-cuoc-song/ban-da-nghi-den-chua/index.qmd)