<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.35">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="ZO Math">

<title>Trọng tâm trong Toán học Trung học Phổ thông: Lý luận và kiến tạo ý nghĩa – ZO Math</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../images/favicon.ico" rel="icon">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-46f66b053e56abd73bb6e954d61a315b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-3d1903c5838503892ba651cf513ab205.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  MathJax = {
    loader: { load: ['[tex]/ams'] },
    tex: {
      packages: { '[+]': ['ams'] }
    },
    chtml: {
      scale: 1.0
    },
    options: {
      renderActions: { addMenu: [] }
    }
  };
</script>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    const tooltipTriggerList = Array.from(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
    const tooltipList = tooltipTriggerList.map(tooltipTriggerEl => {
      const title = tooltipTriggerEl.getAttribute('title');
      if (!title) return null;

      const hasMath = /\\\(.*\\\)|\\\[.*\\\]/.test(title);
      const newTitle = hasMath ? `<span class="mathjax-tooltip">${title}</span>` : title;
      tooltipTriggerEl.setAttribute('data-bs-title', newTitle);
      tooltipTriggerEl.setAttribute('title', '');

      return new bootstrap.Tooltip(tooltipTriggerEl, {
        html: true,
        trigger: 'hover focus',
        boundary: 'viewport',
        placement: 'auto'
      });
    }).filter(tooltip => tooltip !== null);

    tooltipTriggerList.forEach(tooltipTriggerEl => {
      const tooltipInstance = bootstrap.Tooltip.getInstance(tooltipTriggerEl);
      tooltipTriggerEl.addEventListener('shown.bs.tooltip', function () {
        // Tìm phần tử .tooltip
        const tooltip = document.querySelector('.tooltip');
        if (tooltip) {
          // Kiểm tra xem có .tooltip-arrow không
          const tooltipArrow = tooltip.querySelector('.tooltip-arrow');
          if (tooltipArrow) {
            tooltipArrow.style.background = 'transparent';
          } else {
            // Nếu không có .tooltip-arrow, kiểm tra pseudo-elements của .tooltip hoặc .tooltip-inner
            const tooltipInner = tooltip.querySelector('.tooltip-inner');
            if (tooltipInner) {
              // Thử làm trong suốt pseudo-elements của .tooltip
              tooltip.style.setProperty('--tooltip-before-background', 'transparent', 'important');
              // Thử làm trong suốt pseudo-elements của .tooltip-inner
              tooltipInner.style.setProperty('--tooltip-inner-before-background', 'transparent', 'important');
            }
          }
        }

        // Xử lý MathJax trong tooltip
        const tooltipEl = document.querySelector('.tooltip-inner');
        if (!tooltipEl || !tooltipEl.querySelector('.mathjax-tooltip')) return;

        if (typeof MathJax !== 'undefined' && MathJax.typesetPromise) {
          MathJax.typesetPromise([tooltipEl.querySelector('.mathjax-tooltip')]).then(() => {
            console.log('MathJax rendered successfully in tooltip');
            if (tooltipInstance) {
              tooltipInstance.update();
            }
          }).catch(err => {
            console.error('MathJax render error:', err);
          });
        } else {
          console.error('MathJax is not loaded. Ensure MathJax script is included.');
        }
      });
    });
  });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.0/p5.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../assets/css/custom.css">
<link rel="stylesheet" href="../../../assets/css/three-columns.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">ZO Math</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text"><i class="bi bi-house-door"></i></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../content/about.html"> 
<span class="menu-text">Giới Thiệu</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-trung-học-phổ-thông" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Trung Học Phổ Thông</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-trung-học-phổ-thông">    
        <li>
    <a class="dropdown-item" href="../../../content/toan-thpt/toan-11/index.qmd">
 <span class="dropdown-text">Toán 11</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../content/toan-thpt/toan-12/index.qmd">
 <span class="dropdown-text">Toán 12</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../content/toan-thpt/zo-math-100/100-ham-so-su-bien-thien-va-do-thi/index.qmd">
 <span class="dropdown-text">100+ Hàm số</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../../content/zo-o/index.qmd"> 
<span class="menu-text">ZO Ồ!</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../content/zo-lab/index.qmd"> 
<span class="menu-text">ZO Lab</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../content/shop/index.html"> 
<span class="menu-text">ZO Shop</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../content/support/donate.html"> 
<span class="menu-text">Bảo Trợ</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../content/contact.html"> 
<span class="menu-text">Liên Hệ</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page">
      <h1 class="title">Trọng tâm trong Toán học Trung học Phổ thông: Lý luận và kiến tạo ý nghĩa</h1>
            <p class="subtitle lead">Focus in High School Mathematics - Reasoning and Sense Making: Bản dịch đối chiếu song ngữ Anh - Việt</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta column-page">

      <div>
      <div class="quarto-title-meta-heading">Tác giả</div>
      <div class="quarto-title-meta-contents">
               <p>ZO Math </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Ngày cập nhật</div>
      <div class="quarto-title-meta-contents">
        <p class="date">30-06-2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block column-page" id="quarto-document-content">





<!-- Chapter 8 -->
<div class="three-cols">
<div class="row">
<section id="chapter-8.-reasoning-with-statistics-and-probability" class="level2 col-original">
<h2 class="anchored" data-anchor-id="chapter-8.-reasoning-with-statistics-and-probability">Chapter 8. Reasoning with Statistics and Probability</h2>
</section>
<section id="chương-8.-luận-với-thống-kê-và-xác-suất" class="level2 col-translation">
<h2 class="anchored" data-anchor-id="chương-8.-luận-với-thống-kê-và-xác-suất">Chương 8. Luận với Thống kê và Xác suất</h2>
</section>
<div class="col-notes">

</div>
</div>
</div>
<!--  -->
<div class="three-cols">
<div class="row">
<div class="col-original">
<p>In our increasingly data-intensive world, statistics is one of the most important areas of the mathematical sciences for helping students make sense of the information all around them, as well as for preparing them for further study in a variety of disciplines (e.g., the health sciences, the social sciences, and environmental science) for which statistics is a fundamental tool for advancing knowledge. Competence in the Standards found in <em>Principles and Standards</em> (NCTM 2000a) depends on a thorough and deep understanding of the foundations of statistics and probability, and of the connections between statistics and probability. Taken together, <em>Principles and Standards</em> and the American Statistical Association’s report <em>Guidelines for Assessment and Instruction in Statistics Education</em> (GAISE) (Franklin et al.&nbsp;2007) describe statistical problem solving as an investigative process that involves the following four components:</p>
<ul>
<li>Formulating a question (or questions) that can be addressed with data</li>
<li>Designing and employing a plan for collecting data</li>
<li>Analyzing and summarizing the data</li>
<li>Interpreting the results from the analysis, and answering the question on the basis of the data</li>
</ul>
</div>
<div class="col-translation">
<p>Trong một thế giới ngày càng đậm đặc dữ liệu như hiện nay, thống kê là một trong những lĩnh vực quan trọng nhất của khoa học toán học trong việc giúp học sinh hiểu lượng thông tin bao quanh mình, đồng thời chuẩn bị cho các em tiếp tục học tập trong nhiều ngành khác nhau, chẳng hạn khoa học sức khỏe, khoa học xã hội, và khoa học môi trường, những lĩnh vực mà thống kê là một công cụ nền tảng để thúc đẩy tri thức tiến lên. Năng lực đáp ứng các Chuẩn được nêu trong <em>Principles and Standards</em> (NCTM 2000a) phụ thuộc vào một sự hiểu biết vừa vững vừa sâu về những nền tảng của thống kê và xác suất, cũng như về các mối liên hệ giữa thống kê và xác suất. Khi được đọc cùng nhau, <em>Principles and Standards</em> và báo cáo của Hiệp hội Thống kê Hoa Kỳ mang tên <em>Guidelines for Assessment and Instruction in Statistics Education</em> (GAISE) (Franklin et al.&nbsp;2007) mô tả việc giải quyết vấn đề thống kê như một quá trình khảo sát gồm bốn thành phần sau:</p>
<ul>
<li>Hình thành một câu hỏi, hoặc một nhóm câu hỏi, có thể được trả lời bằng dữ liệu</li>
<li>Thiết kế và triển khai một kế hoạch thu thập dữ liệu</li>
<li>Phân tích và tóm lược dữ liệu</li>
<li>Diễn giải các kết quả phân tích, và trả lời câu hỏi trên cơ sở dữ liệu</li>
</ul>
</div>
<div class="col-notes">

</div>
</div>
</div>
<!--  -->
<div class="three-cols">
<div class="row">
<div class="col-original">
<p>The common thread throughout the statistical problem-solving process is the focus on making sense of, and reasoning about, variation in data. The goal is not only to solve problems in the presence of variation but also to provide a measure of how much the variation might affect the solution. This process provides a framework for teaching and learning statistics in school, and meaningful tasks that employ this process should permeate the statistical education of our students.</p>
</div>
<div class="col-translation">
<p>Sợi chỉ xuyên suốt toàn bộ quá trình giải quyết vấn đề thống kê là sự tập trung vào việc hiểu và luận về độ biến thiên trong dữ liệu. Mục tiêu không chỉ là giải quyết các bài toán trong sự hiện diện của biến thiên, mà còn là đưa ra một thước đo cho biết biến thiên ấy có thể ảnh hưởng đến lời giải ở mức nào. Quá trình này tạo nên một khung sườn cho việc dạy và học thống kê trong nhà trường, và những nhiệm vụ có ý nghĩa, vận dụng tiến trình ấy, cần thấm vào toàn bộ quá trình giáo dục thống kê của học sinh.</p>
</div>
<div class="col-notes">
<p>“Sự biến thiên” là trọng tâm cốt lõi của lập luận thống kê. Thống kê không tìm cách loại bỏ biến thiên, mà học cách hiểu, mô tả và lập luận với biến thiên như một đặc trưng tất yếu của dữ liệu trong thế giới thực.</p>
<p>Việc nhấn mạnh rằng mục tiêu không chỉ là tìm lời giải, mà còn là đánh giá mức độ ảnh hưởng của biến thiên đối với lời giải, cho thấy sự khác biệt căn bản giữa tư duy thống kê và các hình thức luận toán học mang tính xác định. Trong thống kê, một kết quả chỉ có ý nghĩa khi đi kèm với mức độ tin cậy hoặc phạm vi ảnh hưởng của sự không chắc chắn.</p>
<p>Tiến trình giải quyết vấn đề thống kê không chỉ là một mô hình kỹ thuật, mà là một khung sư phạm định hướng cho toàn bộ việc dạy và học thống kê. Theo đó, các nhiệm vụ học tập có ý nghĩa cần được thiết kế sao cho học sinh thường xuyên đối diện với dữ liệu có biến thiên và buộc phải luận về biến thiên đó, thay vì chỉ thực hiện các thao tác tính toán rời rạc.</p>
</div>
</div>
</div>
<!--  -->
<div class="three-cols">
<div class="row">
<div class="col-original">
<p>Key elements of reasoning and sense making with statistics and probability include the following:</p>
<ul>
<li><em>Data analysis.</em> Gaining insight about a solution to a statistics question by collecting data and describing features of the data through the use of graphical and tabular representations and numerical summaries. (The interpretation of results in data analysis encompasses both empirical and informal levels of reasoning, as described in the progression of reasoning in chapter 2.)</li>
<li><em>Modeling variability.</em> Developing probability models to describe the long-run behavior of observations of a random variable.</li>
<li><em>Connecting statistics and probability.</em> Recognizing probability as an essential tool of statistics; understanding the role of probability in statistical reasoning.</li>
<li><em>Interpreting designed statistical studies.</em> Drawing appropriate conclusions from data in ways that acknowledge random variation. (Interpreting results from designed statistical studies involves statistical inference and other more formal levels of statistical reasoning.)</li>
</ul>
<p>We address these key elements in more detail in the following sections.</p>
</div>
<div class="col-translation">
<p>Các yếu tố then chốt của luận và hiểu với thống kê và xác suất bao gồm:</p>
<ul>
<li><em>Phân tích dữ liệu.</em> Hình thành hiểu biết về lời giải cho một câu hỏi thống kê bằng cách thu thập dữ liệu và mô tả các đặc trưng của dữ liệu thông qua việc sử dụng các biểu diễn bằng đồ thị, bảng biểu và các đại lượng tóm tắt bằng số. (Việc diễn giải các kết quả trong phân tích dữ liệu bao hàm cả những mức độ luận thực nghiệm và không hình thức, như đã được mô tả trong tiến trình của luận ở Chương 2.)</li>
<li><em>Mô hình hóa biến thiên.</em> Xây dựng các mô hình xác suất để mô tả hành vi dài hạn của các quan sát của một biến ngẫu nhiên.</li>
<li><em>Kết nối thống kê và xác suất.</em> Nhận ra xác suất là một công cụ cốt yếu của thống kê; hiểu vai trò của xác suất trong luận thống kê.</li>
<li><em>Diễn giải các nghiên cứu thống kê được thiết kế.</em> Rút ra những kết luận thích hợp từ dữ liệu theo những cách có tính đến biến thiên ngẫu nhiên. (Việc diễn giải các kết quả từ những nghiên cứu thống kê có thiết kế bao hàm suy luận thống kê và những mức độ luận thống kê hình thức hơn.)</li>
</ul>
<p>Chúng tôi sẽ trình bày chi tiết hơn các yếu tố then chốt này trong những phần tiếp theo.</p>
</div>
<div class="col-notes">

</div>
</div>
</div>
<!--  -->
<div class="three-cols">
<div class="row">
<section id="data-analysis" class="level3 col-original">
<h3 class="anchored" data-anchor-id="data-analysis">Data Analysis</h3>
</section>
<section id="phân-tích-dữ-liệu" class="level3 col-translation">
<h3 class="anchored" data-anchor-id="phân-tích-dữ-liệu">Phân tích dữ liệu</h3>
</section>
<div class="col-notes">

</div>
</div>
</div>
<!--  -->
<div class="three-cols">
<div class="row">
<div class="col-original">
<p>Data analysis is more than simply the analysis of data. Data analysis includes all four components described in the process of statistical problem solving. Data are observations or measurements collected on one or more variables to address a statistical question. In statistics, a variable is any characteristic for which individual observations can be expected to take different values. Consequently, data vary and, once collected, need to be summarized in ways that foster meaningful insights for addressing the question under study. The analysis of data includes exploring various representations of the <em>data distribution</em> to summarize and describe patterns and relationships in the variation and to identify deviations from a pattern. Technology provides the opportunity to examine various representations of the data distribution and to identify important features of the distribution. In data analysis, the interpretation of results includes both empirical and informal levels of reasoning. Because both numerical data and numerical summaries of data are used in data analysis, statistics has connections with the Numbers and Measurements strand described in chapter 4, particularly the key elements of <em>reasonableness of answers and measurements and approximations and error</em>.</p>
</div>
<div class="col-translation">
<p>Phân tích dữ liệu không chỉ đơn thuần là việc xử lý dữ liệu. Phân tích dữ liệu bao gồm đầy đủ cả bốn thành phần đã được mô tả trong tiến trình giải quyết vấn đề thống kê. Dữ liệu là các quan sát hoặc phép đo được thu thập trên một hay nhiều biến nhằm trả lời một câu hỏi thống kê. Trong thống kê, một biến là bất kỳ đặc trưng nào mà các quan sát riêng lẻ có thể được kỳ vọng là nhận những giá trị khác nhau. Do đó, dữ liệu luôn có sự biến thiên và, sau khi được thu thập, cần được tóm tắt theo những cách giúp tạo lập ý nghĩa để giải quyết câu hỏi đang được nghiên cứu. Phân tích dữ liệu bao gồm việc khảo sát các biểu diễn khác nhau của <em>phân bố dữ liệu</em> nhằm tóm tắt và mô tả các khuôn mẫu và mối quan hệ trong sự biến thiên, cũng như để nhận diện những sai lệch so với một khuôn mẫu. Công nghệ tạo điều kiện cho việc xem xét nhiều biểu diễn khác nhau của phân bố dữ liệu và xác định những đặc trưng quan trọng của phân bố đó. Trong phân tích dữ liệu, việc diễn giải kết quả bao hàm cả các mức độ luận thực nghiệm và phi hình thức. Do cả dữ liệu dạng số và các đại lượng tóm tắt bằng số của dữ liệu đều được sử dụng trong phân tích dữ liệu, nên thống kê có mối liên hệ với mạch <em>Số và Đo lường</em> được trình bày ở Chương 4, đặc biệt là các yếu tố cốt lõi về <em>tính hợp lý của kết quả, đo lường, xấp xỉ và sai số</em>.</p>
</div>
<div class="col-notes">

</div>
</div>
</div>
<!--  -->
<div class="three-cols">
<div class="row">
<div class="col-original">
<p>Example 19 shows how statistical procedures for analyzing data that are developed in earlier grades continue to be useful tools for making sense of, and reasoning about, data in high school. Example 19 illustrates organizing and interpreting a solution and recognizing the scope of inference for a statistical solution. A detailed description of this activity is given in Kader and Mamer (2008).</p>
</div>
<div class="col-translation">
<p>Ví dụ 19 cho thấy các quy trình thống kê dùng trong phân tích dữ liệu, vốn đã được hình thành từ các lớp học trước, vẫn tiếp tục là những công cụ hữu ích giúp học sinh kiến tạo hiểu và luận về dữ liệu ở bậc trung học phổ thông. Ví dụ này minh họa việc tổ chức và diễn giải một lời giải, đồng thời nhận ra phạm vi suy luận mà một lời giải thống kê cho phép. Mô tả chi tiết về hoạt động này được trình bày trong công trình của Kader và Mamer (2008).</p>
</div>
<div class="col-notes">

</div>
</div>
</div>
<!-- Example 19, page 14 -->
<section id="example-19-meaningful-words-part-a" class="level4">
<h4 class="anchored" data-anchor-id="example-19-meaningful-words-part-a">Example 19: Meaningful Words, Part A</h4>
<p><em>(Adapted from WGBH Educational Foundation (2001))</em></p>
<p><strong>Task</strong></p>
<p>Scientists are interested in human recall and memory. Is it easier to memorize words that have “meaning?” To study this problem, two lists of 20 three-letter “words” were used. One list contained meaningful words (e.g., CAT, DOG), whereas the other list contained nonsense words (e.g., ATC, ODG). A ninth-grade class of thirty students was randomly divided into two groups of fifteen students. One group was asked to memorize the list of meaningful words; the other group was asked to memorize the list of nonsense words. The number of words correctly recalled by each student was tabulated, and the resulting data are as follows:</p>
<p>Number of meaningful words recalled: <span class="math inline">\(12\)</span>, <span class="math inline">\(15\)</span>, <span class="math inline">\(12\)</span>, <span class="math inline">\(12\)</span>, <span class="math inline">\(10\)</span>, <span class="math inline">\(3\)</span>, <span class="math inline">\(7\)</span>, <span class="math inline">\(11\)</span>, <span class="math inline">\(9\)</span>, <span class="math inline">\(14\)</span>, <span class="math inline">\(9\)</span>, <span class="math inline">\(10\)</span>, <span class="math inline">\(9\)</span>, <span class="math inline">\(5\)</span>, <span class="math inline">\(13\)</span></p>
<p>Number of nonsense words recalled: <span class="math inline">\(4\)</span>, <span class="math inline">\(6\)</span>, <span class="math inline">\(6\)</span>, <span class="math inline">\(5\)</span>, <span class="math inline">\(7\)</span>, <span class="math inline">\(5\)</span>, <span class="math inline">\(4\)</span>, <span class="math inline">\(7\)</span>, <span class="math inline">\(9\)</span>, <span class="math inline">\(10\)</span>, <span class="math inline">\(4\)</span>, <span class="math inline">\(8\)</span>, <span class="math inline">\(7\)</span>, <span class="math inline">\(3\)</span>, <span class="math inline">\(2\)</span></p>
<ol type="1">
<li>Provide a display for summarizing and comparing these data sets.</li>
<li>On the basis of your display, what observations can be made regarding how the students assigned the meaningful words performed compared with how the students assigned the nonsense words performed? Write a paragraph summarizing what the data and your analysis reveal about the question “Is it easier to memorize words that have meaning?”</li>
</ol>
<p><strong>In the Classroom (Ninth-Grade Mathematics Class)</strong></p>
<p>Several groups of students created comparative dotplots for the data, as shown below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fhsm_2009_p75_1_r.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<div class="dialogue">
<dl>
<dt>Teacher:</dt>
<dd>
Looking at the dotplots, for which type of words did students generally have better recall? How do you know? Give some specific reasons for your answer.
</dd>
<dt>Student A:</dt>
<dd>
A lot of students with the meaningful words did better. The highest number recalled is ten for the students with the nonsense words. Seven of the students with meaningful words recalled more than ten words, and ten is the best for all the students with the nonsense words.
</dd>
<dt>Student B:</dt>
<dd>
Yes, but some of the students with the meaningful words did not do very well, either. One recalled only three words; another, only fi ve words; and another, only seven words. These seem low for the meaningful words.
</dd>
<dt>Student C:</dt>
<dd>
Yes, and there are some gaps in the low end of the meaningful-words data distribution but not so much in the nonsense-words distribution. A lot of the students with the nonsense words recalled between three and seven words, and only a few of the students with the meaningful words recalled between three and seven words.
</dd>
<dt>Teacher:</dt>
<dd>
Can you be more specific?
</dd>
<dt>Student C:</dt>
<dd>
Well, three out of the fifteen students with the meaningful words recalled between three and seven words. That’s only 20 percent. For the students using the nonsense words, eleven out of fifteen, more than 73 percent, recalled that many. If you add the student who only recalled two nonsense words, twelve out of these fifteen students, that’s 80 percent, recalled between two and seven words, whereas only 20 percent of the students with the meaningful words were this low. In fact, all fifteen students using the nonsense words recalled between two and ten words, but only eight students with the meaningful words were this low.
</dd>
<dt>Teacher:</dt>
<dd>
That’s the same as what student A said, seven of the fifteen students using the meaningful-words list recalled more words than any of the students using the nonsense-words list. That means close to half the students memorizing the meaningful words did better than all students with the nonsense words.
</dd>
<dt>Teacher:</dt>
<dd>
Let’s try to identify a typical value for the number of words recalled for each list. What quantity would you propose?
</dd>
<dt>Student D:</dt>
<dd>
We could find the average number recalled for each list.
</dd>
<dt>Teacher:</dt>
<dd>
Why do you propose the average, which is also called the mean?
</dd>
<dt>Student D:</dt>
<dd>
Well, it seems like we always find the mean whenever we want to know a typical value.
</dd>
<dt>Student E:</dt>
<dd>
Yes, sometimes the mean is good. But sometimes we use the median for a typical value.
</dd>
<dt>Teacher:</dt>
<dd>
In this case, does it matter which one you use?
</dd>
</dl>
<p>Student E: Well, in the dotplot for the meaningful words, three of the values look kind of small. I think these three values might make the mean smaller than what’s typical. So I would use the median instead of the mean.</p>
<dl>
<dt>Teacher:</dt>
<dd>
Very good. When we see a graph of data like the dotplot for the meaningful words, we say the shape of the data distribution is skewed to the left. Like student E said, when a data distribution is skewed left, the mean is often smaller than what one might think of as typical for the data. For this reason, the median might provide a better indication of how many words were typically recalled by students with the meaningful list. So, what would you propose for a typical value for the number of words recalled by students with the nonsense-words list?
</dd>
<dt>Student E:</dt>
<dd>
The data distribution for the nonsense list looks pretty even. I think this indicates it has a symmetrical shape. So you could probably use either the mean r the median for these data. Since we are using the median for the meaningful words, and it would not make sense to compare the mean of one group to the median of another group, I would use the median for the nonsense words as well.
</dd>
<dt>Teacher:</dt>
<dd>
What do the rest of you think? What happens when we use the medians?
</dd>
<dt>Student D:</dt>
<dd>
My calculator gives the median for the meaningful words as 10, and for the nonsense words the median is 6.
</dd>
<dt>Teacher:</dt>
<dd>
What if we did not have the data values, but only knew the medians? What do the medians tell us about the data?
</dd>
<dt>Student D:</dt>
<dd>
The median divides the data in half.
</dd>
<dt>Teacher:</dt>
<dd>
Yes, so if the median is ten words for the data on meaningful words, what can we say about the rest of the data?
</dd>
<dt>Student F:</dt>
<dd>
About half the students assigned to the meaningful-words list remembered fewer than ten words, and about half remembered more than ten words.
</dd>
<dt>Teacher:</dt>
<dd>
Comparing the two medians, what would you conclude?
</dd>
<dt>Student F:</dt>
<dd>
The median for the meaningful words is ten words, but the median for the nonsense words is six words. Ten is higher than six, so students with meaningful words typically did better than the students with nonsense words.
</dd>
<dt>Teacher:</dt>
<dd>
This is an interesting observation. Another way of looking at this is to say that the difference between the medians is four words. So students with the meaningful words typically recalled four more words than students with the nonsense list.
</dd>
<dt>Teacher:</dt>
<dd>
If only the medians are reported for these data, what information about the number of words recalled is missing?
</dd>
<dt>Student G:</dt>
<dd>
If all you know is the median, you don’t know the actual number recalled for each student. Take the data for the meaningful words. If all I know is that the median number recalled is ten words, I don’t really know about the different values that actually occurred. For example, looking at the student who remembered only three words, three words is a lot different from ten words.
</dd>
<dt>Teacher:</dt>
<dd>
So, student G, what is the idea you talking about called?
</dd>
<dt>Student G:</dt>
<dd>
The number of words recalled is not the same for each student. I think this is the idea of variability in the data, which we have talked about before.
</dd>
<dt>Teacher:</dt>
<dd>
Yes, you are correct. In statistics, we are interested in representing the data with a typical value, such as the median, but we are also interested in summarizing the amount of variability in the data, as well. Does anyone have any suggestions for how we might do this?
</dd>
<dt>Student H:</dt>
<dd>
We could find the ranges. I think this tells us something about how much variability there is. The range is 12 for the meaningful list. The range for the nonsense list is 8.
</dd>
<dt>Teacher:</dt>
<dd>
So, what do the ranges suggest about the variation in the data?
</dd>
<dt>Student H:</dt>
<dd>
The biggest difference between any two values from the meaningful list is twelve words, but the biggest difference between any two values from the nonsense list is eight words. This says that there is more variability in the number of words recalled on the meaningful words list than on the nonsense words list.
</dd>
<dt>Student I:</dt>
<dd>
Yes, but the smallest value from the meaningful words seems really small. For this reason, I don’t think I would use the ranges. Instead, I think we should find the quartiles and use the interquartile ranges (IQR) instead. Then I am comparing the amount of variation for the middle portions of each group.
</dd>
<dt>Teacher:</dt>
<dd>
How do you find the IQR?
</dd>
<dt>Student I:</dt>
<dd>
First you have to find the first and third quartiles for each group of data. Then you find the range between the quartiles. You subtract the first quartile from the third quartile.
</dd>
<dt>Teacher:</dt>
<dd>
OK. Everyone find the quartiles and the interquartile ranges.
</dd>
<dt>Student J:</dt>
<dd>
For the meaningful words, my calculator gives the first quartile as nine words and the third quartile as twelve words. So the IQR is three words. For the nonsense words, the first quartile is four words and the third quartile is seven words. So the IQR is three words. The IQRs are the same, so there are similar amounts of variation in the middle 50 percent of the data for both the meaningful words and the nonsense words.
</dd>
<dt>Student K:</dt>
<dd>
My calculator gives five quantities for each group-the minimum, the first quartile, the median, the third quartile, and the maximum. I think we can get a graph called a box-and-whiskers plot by using these five numbers.
</dd>
<dt>Teacher:</dt>
<dd>
Yes, you can. When you include an outlier analysis, it is called a modified boxplot.
</dd>
</dl>
</div>
<p>The class used results from a calculator to produce the following comparative modified boxplots:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fhsm_2009_p79_1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<div class="dialogue">
<dl>
<dt>Teacher:</dt>
<dd>
Can you use the results from the boxplots to summarize our discussions about this question?
</dd>
<dt>Student M:</dt>
<dd>
Students with the list of meaningful words generally recalled more words. The maximum number of words recalled for the students with the nonsense list is ten. Ten is the median number recalled for the meaningful list, so about half the students with the meaningful words recalled more words than any of the student with the nonsense words. With the meaningful words, one student recalled only three words, and this score is an outlier and somewhat lower than expected when compared to the other data. The median number recalled with the meaningful words is ten, which is four more words than the median number recalled from the nonsense words. Excluding the outlier from the meaningful-words data, both groups appear to have similar amounts of variation. The IQR for each group is 3, indicating that for both meaningful and nonsense words the number of words recalled within the middle 50 percent differ by no more than three words.
</dd>
<dt>Teacher:</dt>
<dd>
What do these results suggest about memory and meaning?
</dd>
<dt>Student N:</dt>
<dd>
Since students with the meaningful words seemed to do better, these data suggest it is easier to memorize words that have meaning.
</dd>
<dt>Teacher:</dt>
<dd>
Do you think it would be appropriate to say that all ninth graders would get exactly the same results?
</dd>
<dt>Student O:</dt>
<dd>
Sure, it’s easier to memorize words that have meaning.
</dd>
<dt>Student P:</dt>
<dd>
Well, we would not get exactly the same scores! But we might still see that words with meaning will be easier to memorize.
</dd>
<dt>Teacher:</dt>
<dd>
We have to be careful about our scope of inference, or trying to generalize these results to other ninth graders based on these data. The scope of inference depends on whether or not the studied class is representative of all ninth-grade classes. As we don’t know how the class was selected, we should not try to generalize the results to all ninth-grade classes or to all ninth graders. If a group of ninth-grade students is selected at random, then we might try to generalize these results to all ninth graders.
</dd>
<dt>Student Q:</dt>
<dd>
But I thought they used randomness in the study.
</dd>
<dt>Teacher:</dt>
<dd>
Yes, they did. However, randomness was used in assigning the students to the different groups. The reason for using random assignment is to produce two comparable groups. For example, you would not want all students who are good at memorizing in one group. By randomly assigning the students to the two groups, we hope to balance the effects from not only students’ memorizing ability but from any other variables that might be related to the number of words recalled. Although random assignment does not guarantee similar groups, there is a high likelihood of creating groups that are similar groups with regard to all variables.
</dd>
</dl>
</div>
<p><strong>Key Elements of Mathematics</strong></p>
<p>Reasoning with Statistics and Probability—Data analysis</p>
<p><strong>Reasoning Habits</strong></p>
<p>Analyzing a Problem—deciding whether a statistical approach is appropriate; identifying relevant concepts, procedures, or representations; seeking patterns and relationships; making preliminary deductions and conjectures</p>
<p>Implementing a strategy—organizing the solution</p>
<p>Seeking and using connections</p>
<p>Reflecting on a solution—interpreting a solution; justifying or validating a solution; recognizing the scope of inference</p>
<!-- Ví dụ 19 -->
</section>
<section id="ví-dụ-19-những-từ-có-nghĩa-phần-a" class="level4">
<h4 class="anchored" data-anchor-id="ví-dụ-19-những-từ-có-nghĩa-phần-a">Ví dụ 19: Những từ có nghĩa, Phần A</h4>
<p><em>(Phỏng theo WGBH Educational Foundation, 2001)</em></p>
<p><strong>Nhiệm vụ</strong></p>
<p>Các nhà khoa học quan tâm đến khả năng ghi nhớ và trí nhớ của con người. Liệu việc ghi nhớ những từ “có nghĩa” có dễ hơn không? Để nghiên cứu vấn đề này, người ta sử dụng hai danh sách gồm <span class="math inline">\(20\)</span> “từ” ba chữ cái. Một danh sách chứa các từ có nghĩa (ví dụ: CAT, DOG), trong khi danh sách còn lại chứa các từ vô nghĩa (ví dụ: ATC, ODG). Một lớp chín gồm ba mươi học sinh được chia ngẫu nhiên thành hai nhóm, mỗi nhóm mười lăm học sinh. Một nhóm được yêu cầu ghi nhớ danh sách các từ có nghĩa; nhóm còn lại được yêu cầu ghi nhớ danh sách các từ vô nghĩa. Số lượng từ được mỗi học sinh nhớ lại đúng được ghi nhận, và dữ liệu thu được như sau:</p>
<p>Số từ có nghĩa được nhớ lại: <span class="math inline">\(12\)</span>, <span class="math inline">\(15\)</span>, <span class="math inline">\(12\)</span>, <span class="math inline">\(12\)</span>, <span class="math inline">\(10\)</span>, <span class="math inline">\(3\)</span>, <span class="math inline">\(7\)</span>, <span class="math inline">\(11\)</span>, <span class="math inline">\(9\)</span>, <span class="math inline">\(14\)</span>, <span class="math inline">\(9\)</span>, <span class="math inline">\(10\)</span>, <span class="math inline">\(9\)</span>, <span class="math inline">\(5\)</span>, <span class="math inline">\(13\)</span>.</p>
<p>Số từ vô nghĩa được nhớ lại: <span class="math inline">\(4\)</span>, <span class="math inline">\(6\)</span>, <span class="math inline">\(6\)</span>, <span class="math inline">\(5\)</span>, <span class="math inline">\(7\)</span>, <span class="math inline">\(5\)</span>, <span class="math inline">\(4\)</span>, <span class="math inline">\(7\)</span>, <span class="math inline">\(9\)</span>, <span class="math inline">\(10\)</span>, <span class="math inline">\(4\)</span>, <span class="math inline">\(8\)</span>, <span class="math inline">\(7\)</span>, <span class="math inline">\(3\)</span>, <span class="math inline">\(2\)</span>.</p>
<ol type="1">
<li>Hãy đưa ra một cách biểu diễn để tóm tắt và so sánh hai bộ dữ liệu này.</li>
<li>Dựa trên biểu diễn đó, có thể rút ra những nhận xét gì về kết quả của các học sinh được giao ghi nhớ từ có nghĩa so với các học sinh được giao ghi nhớ từ vô nghĩa? Hãy viết một đoạn văn tóm tắt những gì dữ liệu và phân tích của bạn cho thấy về câu hỏi: “Liệu việc ghi nhớ các từ có nghĩa có dễ hơn không?”</li>
</ol>
<p><strong>Trong lớp học (Lớp Toán lớp 9)</strong></p>
<p>Một số nhóm học sinh đã xây dựng các biểu đồ chấm so sánh cho dữ liệu, như minh họa dưới đây.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fhsm_2009_p75_1_r.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<div class="dialogue">
<dl>
<dt>Giáo viên:</dt>
<dd>
Nhìn vào các biểu đồ chấm, với loại từ nào thì học sinh nhìn chung có khả năng ghi nhớ tốt hơn? Em biết điều đó bằng cách nào? Hãy đưa ra những lý do cụ thể.
</dd>
<dt>Học sinh A:</dt>
<dd>
Nhiều học sinh với danh sách từ có nghĩa làm tốt hơn. Số lớn nhất được nhớ lại ở nhóm từ vô nghĩa là mười. Có bảy học sinh trong nhóm từ có nghĩa nhớ được hơn mười từ, trong khi mười là kết quả cao nhất của toàn bộ nhóm từ vô nghĩa.
</dd>
<dt>Học sinh B:</dt>
<dd>
Đúng, nhưng cũng có một số học sinh với từ có nghĩa không làm tốt. Một bạn chỉ nhớ được ba từ; một bạn khác chỉ nhớ được năm từ; và một bạn nữa chỉ nhớ được bảy từ. Những giá trị này có vẻ thấp đối với nhóm từ có nghĩa.
</dd>
<dt>Học sinh C:</dt>
<dd>
Đúng vậy, và ở phía thấp của phân bố dữ liệu của nhóm từ có nghĩa có một số khoảng trống, trong khi phân bố của nhóm từ vô nghĩa thì không rõ điều đó. Nhiều học sinh với từ vô nghĩa nhớ được từ ba đến bảy từ, trong khi chỉ có rất ít học sinh với từ có nghĩa nằm trong khoảng này.
</dd>
<dt>Giáo viên:</dt>
<dd>
Em có thể nói cụ thể hơn không?
</dd>
<dt>Học sinh C:</dt>
<dd>
Vâng. Ba trong số mười lăm học sinh với từ có nghĩa nhớ được từ ba đến bảy từ, tức là chỉ <span class="math inline">\(20\)</span> phần trăm. Trong khi đó, ở nhóm từ vô nghĩa, mười một trên mười lăm học sinh, tức hơn <span class="math inline">\(73\)</span> phần trăm, nhớ được từng ấy từ. Nếu tính cả học sinh chỉ nhớ được hai từ vô nghĩa, thì mười hai trong số mười lăm học sinh, tức <span class="math inline">\(80\)</span> phần trăm, nhớ được từ hai đến bảy từ, trong khi chỉ có <span class="math inline">\(20\)</span> phần trăm học sinh với từ có nghĩa ở mức thấp như vậy. Thực tế, tất cả mười lăm học sinh với từ vô nghĩa đều nhớ được từ hai đến mười từ, trong khi chỉ có tám học sinh với từ có nghĩa ở mức thấp như vậy.
</dd>
<dt>Giáo viên:</dt>
<dd>
Điều đó cũng giống như ý kiến của học sinh A: bảy trong số mười lăm học sinh dùng danh sách từ có nghĩa nhớ được nhiều từ hơn bất kỳ học sinh nào trong nhóm từ vô nghĩa. Điều này có nghĩa là gần một nửa số học sinh ghi nhớ từ có nghĩa làm tốt hơn toàn bộ nhóm từ vô nghĩa.
</dd>
<dt>Giáo viên:</dt>
<dd>
Bây giờ hãy thử xác định một giá trị điển hình cho số từ được nhớ lại của mỗi danh sách. Các em đề xuất dùng đại lượng nào?
</dd>
<dt>Học sinh D:</dt>
<dd>
Chúng ta có thể tính giá trị trung bình cho mỗi danh sách.
</dd>
<dt>Giáo viên:</dt>
<dd>
Tại sao em đề xuất dùng trung bình, hay còn gọi là số trung bình cộng?
</dd>
<dt>Học sinh D:</dt>
<dd>
Vì có vẻ như chúng ta luôn tìm trung bình mỗi khi muốn biết một giá trị điển hình.
</dd>
<dt>Học sinh E:</dt>
<dd>
Đúng là đôi khi trung bình tốt, nhưng đôi khi chúng ta lại dùng trung vị để biểu thị giá trị điển hình.
</dd>
<dt>Giáo viên:</dt>
<dd>
Trong trường hợp này, việc dùng cái nào có quan trọng không?
</dd>
<dt>Học sinh E:</dt>
<dd>
Với biểu đồ chấm của nhóm từ có nghĩa, ba giá trị trông khá nhỏ. Em nghĩ ba giá trị này có thể làm cho trung bình nhỏ hơn mức điển hình. Vì vậy em sẽ dùng trung vị thay vì trung bình.
</dd>
<dt>Giáo viên:</dt>
<dd>
Rất tốt. Khi quan sát một biểu đồ dữ liệu như biểu đồ chấm của nhóm từ có nghĩa, ta nói rằng dạng phân bố của dữ liệu bị lệch trái. Như học sinh E đã nói, khi phân bố dữ liệu lệch trái, trung bình thường nhỏ hơn giá trị mà ta xem là điển hình. Vì lý do này, trung vị có thể cho ta một chỉ báo tốt hơn về số từ mà học sinh với danh sách từ có nghĩa thường nhớ được. Vậy em sẽ đề xuất giá trị điển hình nào cho nhóm từ vô nghĩa?
</dd>
<dt>Học sinh E:</dt>
<dd>
Phân bố dữ liệu của nhóm từ vô nghĩa trông khá cân đối. Điều đó cho thấy nó có dạng đối xứng. Vì vậy, có lẽ ta có thể dùng cả trung bình lẫn trung vị. Nhưng vì chúng ta đang dùng trung vị cho nhóm từ có nghĩa, và sẽ không hợp lý nếu so sánh trung bình của nhóm này với trung vị của nhóm kia, nên em sẽ dùng trung vị cho nhóm từ vô nghĩa.
</dd>
<dt>Giáo viên:</dt>
<dd>
Các em khác nghĩ sao? Điều gì xảy ra khi chúng ta dùng trung vị?
</dd>
<dt>Học sinh D:</dt>
<dd>
Máy tính của em cho trung vị của nhóm từ có nghĩa là <span class="math inline">\(10\)</span>, còn trung vị của nhóm từ vô nghĩa là <span class="math inline">\(6\)</span>.
</dd>
<dt>Giáo viên:</dt>
<dd>
Nếu chúng ta không có các giá trị dữ liệu cụ thể, mà chỉ biết các trung vị, thì các trung vị cho ta biết điều gì về dữ liệu?
</dd>
<dt>Học sinh D:</dt>
<dd>
Trung vị chia dữ liệu thành hai nửa.
</dd>
<dt>Giáo viên:</dt>
<dd>
Đúng vậy. Vậy nếu trung vị là mười từ đối với dữ liệu từ có nghĩa, ta có thể nói gì về phần còn lại của dữ liệu?
</dd>
<dt>Học sinh F:</dt>
<dd>
Khoảng một nửa số học sinh với danh sách từ có nghĩa nhớ được ít hơn mười từ, và khoảng một nửa nhớ được nhiều hơn mười từ.
</dd>
<dt>Giáo viên:</dt>
<dd>
Khi so sánh hai trung vị, em rút ra kết luận gì?
</dd>
<dt>Học sinh F:</dt>
<dd>
Trung vị của nhóm từ có nghĩa là mười từ, còn trung vị của nhóm từ vô nghĩa là sáu từ. Mười lớn hơn sáu, nên học sinh với từ có nghĩa nhìn chung làm tốt hơn học sinh với từ vô nghĩa.
</dd>
<dt>Giáo viên:</dt>
<dd>
Đây là một nhận xét thú vị. Một cách khác để nhìn vào điều này là nói rằng sự chênh lệch giữa hai trung vị là bốn từ. Như vậy, học sinh với từ có nghĩa thường nhớ được nhiều hơn bốn từ so với học sinh với từ vô nghĩa.
</dd>
<dt>Giáo viên:</dt>
<dd>
Nếu chỉ báo cáo trung vị cho bộ dữ liệu này, thì thông tin gì về số từ được nhớ lại sẽ bị thiếu?
</dd>
<dt>Học sinh G:</dt>
<dd>
Nếu chỉ biết trung vị, ta không biết số từ cụ thể mà mỗi học sinh nhớ được. Ví dụ, trong dữ liệu của nhóm từ có nghĩa, nếu chỉ biết trung vị là mười từ, em không biết các giá trị khác thực sự đã xuất hiện như thế nào. Chẳng hạn, học sinh chỉ nhớ được ba từ khác xa rất nhiều so với mười từ.
</dd>
<dt>Giáo viên:</dt>
<dd>
Vậy học sinh G, ý tưởng mà em đang nói tới được gọi là gì?
</dd>
<dt>Học sinh G:</dt>
<dd>
Số từ được nhớ lại không giống nhau đối với mỗi học sinh. Em nghĩ đó chính là ý tưởng về sự biến thiên trong dữ liệu, điều mà chúng ta đã nói tới trước đây.
</dd>
<dt>Giáo viên:</dt>
<dd>
Đúng vậy. Trong thống kê, chúng ta quan tâm đến việc biểu diễn dữ liệu bằng một giá trị điển hình, chẳng hạn như trung vị, nhưng đồng thời cũng quan tâm đến việc tóm tắt mức độ biến thiên của dữ liệu. Có ai đề xuất cách làm điều đó không?
</dd>
<dt>Học sinh H:</dt>
<dd>
Chúng ta có thể tính khoảng biến thiên. Em nghĩ điều này cho biết phần nào mức độ biến thiên. Khoảng biến thiên của nhóm từ có nghĩa là <span class="math inline">\(12\)</span>. Còn của nhóm từ vô nghĩa là <span class="math inline">\(8\)</span>.
</dd>
<dt>Giáo viên:</dt>
<dd>
Vậy các khoảng biến thiên cho thấy điều gì về sự biến thiên trong dữ liệu?
</dd>
<dt>Học sinh H:</dt>
<dd>
Sự khác biệt lớn nhất giữa hai giá trị bất kỳ trong nhóm từ có nghĩa là mười hai từ, còn trong nhóm từ vô nghĩa là tám từ. Điều này cho thấy mức độ biến thiên trong số từ được nhớ lại ở nhóm từ có nghĩa lớn hơn so với nhóm từ vô nghĩa.
</dd>
<dt>Học sinh I:</dt>
<dd>
Nhưng giá trị nhỏ nhất của nhóm từ có nghĩa có vẻ rất thấp. Vì vậy em không nghĩ nên dùng khoảng biến thiên. Thay vào đó, em nghĩ chúng ta nên tìm các tứ phân vị và dùng khoảng tứ phân vị (IQR). Khi đó, em đang so sánh mức độ biến thiên của phần trung tâm trong mỗi nhóm.
</dd>
<dt>Giáo viên:</dt>
<dd>
Em tìm IQR như thế nào?
</dd>
<dt>Học sinh I:</dt>
<dd>
Trước hết phải tìm tứ phân vị thứ nhất và thứ ba cho mỗi nhóm dữ liệu. Sau đó lấy tứ phân vị thứ ba trừ đi tứ phân vị thứ nhất.
</dd>
<dt>Giáo viên:</dt>
<dd>
Được rồi. Mọi người hãy tìm các tứ phân vị và khoảng tứ phân vị.
</dd>
<dt>Học sinh J:</dt>
<dd>
Với nhóm từ có nghĩa, máy tính của em cho tứ phân vị thứ nhất là chín từ và tứ phân vị thứ ba là mười hai từ. Vậy IQR là ba từ. Với nhóm từ vô nghĩa, tứ phân vị thứ nhất là bốn từ và tứ phân vị thứ ba là bảy từ, nên IQR cũng là ba từ. Các IQR bằng nhau, nên mức độ biến thiên trong <span class="math inline">\(50\)</span> phần trăm dữ liệu trung tâm của hai nhóm là tương tự nhau.
</dd>
<dt>Học sinh K:</dt>
<dd>
Máy tính của em cho năm đại lượng cho mỗi nhóm: giá trị nhỏ nhất, tứ phân vị thứ nhất, trung vị, tứ phân vị thứ ba và giá trị lớn nhất. Em nghĩ từ năm số này chúng ta có thể vẽ một đồ thị gọi là biểu đồ hộp.
</dd>
<dt>Giáo viên:</dt>
<dd>
Đúng vậy. Khi kèm theo việc phân tích ngoại lệ, nó được gọi là biểu đồ hộp điều chỉnh.
</dd>
</dl>
</div>
<p>Lớp học đã sử dụng kết quả từ máy tính để xây dựng các biểu đồ hộp điều chỉnh so sánh sau đây:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fhsm_2009_p79_1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<div class="dialogue">
<dl>
<dt>Giáo viên:</dt>
<dd>
Các em có thể dùng kết quả từ các biểu đồ hộp để tóm tắt lại những thảo luận của chúng ta về câu hỏi này không?
</dd>
<dt>Học sinh M:</dt>
<dd>
Nhìn chung, học sinh với danh sách từ có nghĩa nhớ được nhiều từ hơn. Số từ tối đa được nhớ lại trong nhóm từ vô nghĩa là mười. Mười cũng chính là trung vị của nhóm từ có nghĩa, nên khoảng một nửa số học sinh với từ có nghĩa nhớ được nhiều từ hơn bất kỳ học sinh nào trong nhóm từ vô nghĩa. Trong nhóm từ có nghĩa, có một học sinh chỉ nhớ được ba từ; đây là một giá trị ngoại lệ và thấp hơn khá nhiều so với các dữ liệu còn lại. Trung vị của nhóm từ có nghĩa là mười, cao hơn bốn từ so với trung vị của nhóm từ vô nghĩa. Nếu loại bỏ ngoại lệ này khỏi dữ liệu của nhóm từ có nghĩa, thì hai nhóm có vẻ có mức độ biến thiên tương tự nhau. IQR của mỗi nhóm là <span class="math inline">\(3\)</span>, cho thấy trong cả hai nhóm, số từ được nhớ lại trong <span class="math inline">\(50\)</span> phần trăm dữ liệu trung tâm chỉ khác nhau nhiều nhất là ba từ.
</dd>
<dt>Giáo viên:</dt>
<dd>
Những kết quả này gợi ý điều gì về trí nhớ và ý nghĩa?
</dd>
<dt>Học sinh N:</dt>
<dd>
Vì học sinh với các từ có nghĩa dường như làm tốt hơn, nên những dữ liệu này cho thấy việc ghi nhớ các từ có nghĩa là dễ hơn.
</dd>
<dt>Giáo viên:</dt>
<dd>
Các em có nghĩ rằng sẽ phù hợp nếu nói rằng tất cả học sinh lớp chín đều sẽ có kết quả giống hệt như vậy không?
</dd>
<dt>Học sinh O:</dt>
<dd>
Chắc chắn rồi, ghi nhớ từ có nghĩa thì dễ hơn.
</dd>
<dt>Học sinh P:</dt>
<dd>
Em nghĩ là chúng ta sẽ không có các điểm số y hệt! Nhưng có thể vẫn thấy rằng các từ có nghĩa sẽ dễ ghi nhớ hơn.
</dd>
<dt>Giáo viên:</dt>
<dd>
Chúng ta cần cẩn trọng về phạm vi suy luận, tức là việc khái quát các kết quả này cho các học sinh lớp chín khác dựa trên dữ liệu này. Phạm vi suy luận phụ thuộc vào việc lớp học được nghiên cứu có đại diện cho tất cả các lớp chín hay không. Vì chúng ta không biết lớp học này được chọn như thế nào, nên không nên khái quát kết quả cho tất cả các lớp chín hoặc cho toàn bộ học sinh lớp chín. Nếu một nhóm học sinh lớp chín được chọn ngẫu nhiên, khi đó ta mới có thể thử khái quát các kết quả này cho toàn bộ học sinh lớp chín.
</dd>
<dt>Học sinh Q:</dt>
<dd>
Nhưng em tưởng là họ đã dùng ngẫu nhiên trong nghiên cứu rồi?
</dd>
<dt>Giáo viên:</dt>
<dd>
Đúng là có dùng ngẫu nhiên. Tuy nhiên, ngẫu nhiên được sử dụng trong việc phân công học sinh vào các nhóm khác nhau. Mục đích của việc phân công ngẫu nhiên là tạo ra hai nhóm có thể so sánh được. Chẳng hạn, ta không muốn tất cả những học sinh có khả năng ghi nhớ tốt đều rơi vào cùng một nhóm. Bằng cách phân công ngẫu nhiên học sinh vào hai nhóm, ta hy vọng cân bằng được ảnh hưởng không chỉ từ khả năng ghi nhớ của học sinh mà còn từ bất kỳ biến nào khác có thể liên quan đến số từ được nhớ lại. Mặc dù phân công ngẫu nhiên không đảm bảo tạo ra các nhóm giống hệt nhau, nhưng nó làm tăng khả năng hình thành các nhóm tương tự nhau xét trên tất cả các biến.
</dd>
</dl>
</div>
<p><strong>Các yếu tố then chốt toán học</strong></p>
<p>Luận với Thống kê và Xác suất—Phân tích dữ liệu</p>
<p><strong>Thói quen luận</strong></p>
<p>Phân tích bài toán—quyết định xem liệu cách tiếp cận thống kê có phù hợp hay không; xác định các khái niệm, quy trình hoặc biểu diễn liên quan; tìm kiếm các khuôn mẫu và mối quan hệ; đưa ra những suy luận và phỏng đoán ban đầu</p>
<p>Thực hiện chiến lược—tổ chức lời giải</p>
<p>Tìm kiếm và sử dụng các mối liên hệ</p>
<p>Suy ngẫm về lời giải—diễn giải lời giải; biện minh hoặc kiểm chứng lời giải; nhận diện phạm vi suy luận</p>
<!--  -->
</section>
<div class="three-cols">
<div class="row">
<section id="modeling-variability" class="level3 col-original">
<h3 class="anchored" data-anchor-id="modeling-variability">Modeling Variability</h3>
</section>
<section id="mô-hình-hóa-sự-biến-thiên" class="level3 col-translation">
<h3 class="anchored" data-anchor-id="mô-hình-hóa-sự-biến-thiên">Mô hình hóa sự biến thiên</h3>
</section>
<div class="col-notes">

</div>
</div>
</div>
<!--  -->
<div class="three-cols">
<div class="row">
<div class="col-original">
<p>Probability models reinforce the foundational principle that although an individual observation of a random variable cannot be predicted with certainty, patterns emerge in the frequency of values over a large number of observations. Fostering students’ understanding of random variables and probability requires engaging them in the development of both simulation and mathematical probability models. The design of a simulation model requires that students set up a logical sequence of steps for describing the possible outcomes of a random variable. The implementation of a simulation model allows students to both experience and make sense of the notion of the long-run behavior of a random variable and to determine experimental probabilities. The design and implementation of a simulation also provides transitional steps in the development of reasonable mathematical models for describing the long-run behavior of a random variable. Because many probability models involve counting, probability has connections with the Numbers and Measurements strand and the key element of counting described in chapter 4. Example 20 considers various developmental strategies for arriving at a solution to a probability problem and illustrates the importance of identifying relevant concepts, procedures, or representations and knowing how a solution can be generalized to a broader class of problems.</p>
</div>
<div class="col-translation">
<p>Các mô hình xác suất củng cố nguyên lý nền tảng rằng, mặc dù không thể dự đoán chắc chắn một quan sát riêng lẻ của một biến ngẫu nhiên, nhưng các khuôn mẫu sẽ xuất hiện trong tần suất của các giá trị khi số lượng quan sát đủ lớn. Việc bồi dưỡng cho học sinh sự hiểu biết về biến ngẫu nhiên và xác suất đòi hỏi phải lôi cuốn các em tham gia vào quá trình xây dựng cả các mô hình xác suất mô phỏng lẫn các mô hình xác suất toán học. Thiết kế một mô hình mô phỏng yêu cầu học sinh thiết lập một chuỗi các bước hợp lý để mô tả các kết quả có thể xảy ra của một biến ngẫu nhiên. Việc triển khai mô hình mô phỏng cho phép học sinh vừa trải nghiệm vừa tạo lập ý nghĩa cho khái niệm hành vi dài hạn của một biến ngẫu nhiên, đồng thời xác định các xác suất thực nghiệm. Quá trình thiết kế và triển khai mô phỏng cũng cung cấp những bước chuyển tiếp trong việc phát triển các mô hình toán học hợp lý nhằm mô tả hành vi dài hạn của một biến ngẫu nhiên. Vì nhiều mô hình xác suất liên quan đến việc đếm, nên xác suất có mối liên hệ với mạch <em>Số và Đo lường</em> và yếu tố cốt lõi <em>đếm</em> được trình bày trong Chương 4. Ví dụ 20 xem xét nhiều chiến lược phát triển khác nhau để đi tới lời giải của một bài toán xác suất, đồng thời minh họa tầm quan trọng của việc xác định các khái niệm, quy trình hoặc biểu diễn liên quan và hiểu được cách một lời giải có thể được khái quát hóa cho một lớp bài toán rộng hơn.</p>
</div>
<div class="col-notes">

</div>
</div>
</div>
<!-- Example 20 -->
<section id="example-20-what-are-the-chances-part-a" class="level4">
<h4 class="anchored" data-anchor-id="example-20-what-are-the-chances-part-a">Example 20: What Are the Chances? Part A</h4>
<p><strong>Task</strong></p>
<p>A high school club has fifty members: ten girls and forty boys. The refreshments committee will be formed by selecting two students from the club at random. What is the probability of getting exactly zero girls on the committee? Exactly one girl on the committee? Exactly two girls on the committee? That is, if two students are repeatedly selected at random from the club, how often will exactly no girl be selected? Exactly one girl? Exactly two girls?</p>
<p><strong>In the Classroom (Ninth- to Twelfth-Grade Mathematics Classes)</strong></p>
<p>The class is instructed to design a hands-on simulation for estimating the probability for each of the different possible results for the number of girls on the committee. Prior to this activity, students should have had experiences performing simulations by using various random devices and random-number generators in graphing calculators. After the task is read, the teacher can ask the students how they might design a simulation for the situation of choosing two students for the committee and reporting the number of girls on the committee.</p>
<p>The teacher can lead a discussion to help students design the simulation. Students may propose the use of a standard deck of cards (they would remove two face cards and represent the girls with the ten remaining face cards and the boys with the forty non-face cards). For each trial, they would shuffle the deck several times and then select two cards. The number of face cards selected represents the number of girls on the committee. For the next trial, they would replace the cards in the deck, reshuffle, and select two more cards. Students would need to decide how many trials to perform. From previous experiences, students know that the relative frequencies tend to be close to the actual probabilities if they perform a large number of trials. Together, the class performed a simulation of two hundred trials. The results are summarized in the table at the top of the next page.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 19%">
<col style="width: 37%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;">Number of Girls</td>
<td style="text-align: center;">Frequency</td>
<td style="text-align: center;">Experimental Probability</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(121\)</span></td>
<td style="text-align: center;"><span class="math inline">\(.605\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(70\)</span></td>
<td style="text-align: center;"><span class="math inline">\(.350\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9\)</span></td>
<td style="text-align: center;"><span class="math inline">\(.045\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(200\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1.000\)</span></td>
</tr>
</tbody>
</table>
<p>The experimental probabilities provide estimates for the true probabilities for each of the different possible results and illustrate the long-run relative frequency interpretation of probability.</p>
<p><strong>In the Classroom (High School Statistics Class)</strong></p>
<p>Students can revisit this problem in a statistics class after they have learned about tree diagrams and are learning about rules of probability. The class constructed the tree diagram at the right for describing the gender of the two students selected.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fhsm_2009_p82_1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>Students are asked to describe the ordered sequence of outcomes for gender that results in the number of girls selected to be 0. For this outcome, the ordered sequence must be —</p>
<div class="indent-both">
<p>Boy selected first and boy selected second.</p>
</div>
<p>Students are asked to determine the probability that the first student selected is a boy, which they all agree is</p>
<p><span class="math display">\[
  \frac{40}{50},
\]</span></p>
<p>or <span class="math inline">\(0.8\)</span>.</p>
<p>They are then asked to think about the probability that the second student selected is a boy, and many said</p>
<p><span class="math display">\[
  \frac{39}{49}.
\]</span></p>
<p>The teacher asks about any assumptions made in determining this probability, and the class agrees that this probability assumes that the first student selected is a boy. The teacher points out that</p>
<p><span class="math display">\[
  \frac{39}{49}
\]</span></p>
<p>is called a “conditional” probability and represents the probability that the second student selected is a boy, given that the first student selected is a boy. The teacher then asks about the probability of the ordered sequence “Boy selected first and boy selected second.” A student responds that the sequence can occur only if a boy is selected first and, given that a boy was selected first, a boy is selected second. That is,</p>
<p><span class="math display">\[
\begin{aligned}
  P(0 \, \text{Girls})
    &amp;= P(\text{Boy selected first and Boy selected second})\\
    &amp;= P(\text{Boy selected first})P(\text{Boy selected second given Boy selected first}) \\
    &amp;= \frac{40}{50}\cdot\frac{39}{49}.
\end{aligned}
\]</span></p>
<p>The teacher uses this opportunity to present the product rule for probability:</p>
<p><span class="math display">\[
  P(A \, \text{and}\, B)= P(A)P(\text{$B$ given that $A$ has occurred}).
\]</span></p>
<p>The class expands the tree diagram to show the conditional probabilities for the outcome of gender at each stage of the selection, the ordered sequence of gender, and the number of girls selected for each ordered sequence.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fhsm_2009_p83_1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>By traversing the tree and using the product rule, the class determines each of the following probabilities:</p>
<p><span class="math display">\[
\begin{aligned}
  P(\text{No Girls})&amp;=(40/50)(39/49) \approx .637, \\
  P(\text{One Girl})&amp;=(10/50)(40/49)+(40/50)(10/49) \approx .327, \, \text{and} \\
  P(\text{Two Girls})&amp;=P(\text{Girl on First and Girl on Second})=(10/50)(9/49) \approx .037.
\end{aligned}
\]</span></p>
<p>The teacher then asks the class to think about the following question for homework.</p>
<div class="indent-left">
<p>Suppose the gender of the first student selected is not known. We are interested in knowing the probability that the second student selected is a girl (regardless of the gender of the first student selected). This probability is —</p>
<p><span class="math display">\[
P(\text{Girl selected Second}) =\frac{10}{50}.
\]</span></p>
<p>Can you explain why this is the probability?</p>
</div>
<p><strong>In the Classroom (Twelfth Grade)</strong></p>
<p>Students can revisit this problem in the twelfth grade after they have learned counting rules. The class is instructed to use counting rules for determining the probability for each of the different possible results for the number of girls on the committee and to interpret the probabilities. Revisiting the same problem at a higher level gives students an opportunity to make sense of their earlier simulation.</p>
<p>Students are reminded that</p>
<p><span class="math display">\[
  C(m,k)=\frac{m!}{k!(m-k)!}
\]</span></p>
<p>counts the number of subsets of size <span class="math inline">\(k\)</span> from <span class="math inline">\(m\)</span> distinct objects.</p>
<p>For this problem, we get <span class="math inline">\(C(50, 2)\)</span>, or 1225, possible subsets (committees) of size two from the club of fifty students. Since the selection is random, we can assume that each possible committee is equally likely. The number of committees with —</p>
<div class="indent-left">
<p>exactly <span class="math inline">\(0\)</span> girls (and exactly <span class="math inline">\(2\)</span> boys) is <span class="math inline">\(C(10, 0) \cdot C(40, 2)\)</span>, or <span class="math inline">\(780\)</span>;</p>
<p>exactly <span class="math inline">\(1\)</span> girl (and exactly <span class="math inline">\(1\)</span> boy) is <span class="math inline">\(C(10, 1) \cdot C(40, 1)\)</span>, or <span class="math inline">\(400\)</span>;</p>
<p>exactly <span class="math inline">\(2\)</span> girls (and exactly <span class="math inline">\(0\)</span> boys) is <span class="math inline">\(C(10, 2) \cdot C(40, 0)\)</span>, or <span class="math inline">\(45\)</span>.</p>
</div>
<p>Thus, the mathematical probabilities are as shown in the following table:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 45%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;">Number of Girls</td>
<td style="text-align: center;">Probability</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{780}{1225}\approx .637\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{400}{1225}\approx .327\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{45 }{1225}\approx .037\)</span></td>
</tr>
</tbody>
</table>
<p>This example can be used as a rationale for developing the general formula for calculating these types of probabilities when sampling from a fi nite population. Suppose you have a population with <span class="math inline">\(N\)</span> objects and each object is classified as either a success or a failure. Within the population, <span class="math inline">\(M\)</span> of the objects are successes. You plan to randomly select <span class="math inline">\(n\)</span> objects and to count the number of successes among those selected. For this situation, the number of successes is called a <em>hypergeometric random variable</em>, and the probability of obtaining exactly <span class="math inline">\(x\)</span> successes is given by</p>
<p><span class="math display">\[
  P(x)=\frac{C(M,x)\cdot C(N-M,n-x)}{C(N,n)}.
\]</span></p>
<p><strong><em>Summary of example 20</em></strong></p>
<p>Note that the estimated probabilities from the simulation in the first task are close to the probabilities obtained either through counting or using the tree diagram. These latter probabilities indicate that if two members are repeatedly selected at random from the club, then on any one trial, getting exactly zero girls is most likely and would occur approximately <span class="math inline">\(64\)</span> percent of the time. Getting exactly one girl on the committee is fairly common and would occur approximately <span class="math inline">\(33\)</span> percent of the time. In addition, since the probability of getting exactly two girls is less than <span class="math inline">\(.04\)</span>, it would be unusual for the committee to have two girls. An examination of this problem from a statistical perspective is described in example 21.</p>
<p><strong>Key Elements of Mathematics</strong></p>
<p>Reasoning with Statistics and Probability—Modeling variability</p>
<p>Number and Measurement—Counting</p>
<p><strong>Reasoning Habits</strong></p>
<p>Analyzing a problem—identifying relevant concepts, procedures, or representations</p>
<p>Implementing a strategy—making logical deductions</p>
<p>Seeking and using connections</p>
<p>Reflecting on one’s solution—interpreting a solution; generalizing a solution</p>
<!-- Ví dụ 20 -->
</section>
<section id="ví-dụ-20-bao-nhiêu-khả-năng-phần-a" class="level4">
<h4 class="anchored" data-anchor-id="ví-dụ-20-bao-nhiêu-khả-năng-phần-a">Ví dụ 20: Bao nhiêu khả năng? Phần A</h4>
<p><strong>Nhiệm vụ</strong></p>
<p>Một câu lạc bộ trung học phổ thông có năm mươi thành viên: mười bạn nữ và bốn mươi bạn nam. Ban phụ trách nước uống sẽ được lập bằng cách chọn ngẫu nhiên hai học sinh từ câu lạc bộ. Xác suất để ban này có đúng không bạn nữ là bao nhiêu? Có đúng một bạn nữ là bao nhiêu? Có đúng hai bạn nữ là bao nhiêu? Nói cách khác, nếu hai học sinh được chọn ngẫu nhiên lặp đi lặp lại từ câu lạc bộ, thì sẽ có bao nhiêu lần đúng là không có nữ sinh nào được chọn? Đúng một nữ sinh? Đúng hai nữ sinh?</p>
<p><strong>Trong lớp học (Lớp Toán từ lớp 9 đến lớp 12)</strong></p>
<p>Lớp được hướng dẫn thiết kế một mô phỏng thực hành để ước lượng xác suất cho từng kết quả có thể xảy ra về số bạn nữ trong ban phụ trách. Trước hoạt động này, học sinh cần đã có trải nghiệm thực hiện mô phỏng bằng nhiều thiết bị ngẫu nhiên khác nhau và bằng các bộ sinh số ngẫu nhiên trong máy tính cầm tay vẽ đồ thị. Sau khi đọc đề bài, giáo viên có thể hỏi học sinh rằng các em có thể thiết kế một mô phỏng cho tình huống chọn hai học sinh vào ban phụ trách và báo cáo số bạn nữ trong ban như thế nào.</p>
<p>Giáo viên có thể dẫn dắt thảo luận để giúp học sinh thiết kế mô phỏng. Học sinh có thể đề xuất sử dụng một bộ bài tiêu chuẩn (các em sẽ bỏ đi hai lá hình, rồi dùng mười lá hình còn lại để biểu diễn các bạn nữ và bốn mươi lá không hình để biểu diễn các bạn nam). Ở mỗi lần thử, các em sẽ xáo bài vài lần rồi rút hai lá. Số lá hình được rút ra biểu diễn số bạn nữ trong ban phụ trách. Đến lần thử tiếp theo, các em trả lại các lá bài vào bộ, xáo lại, rồi rút thêm hai lá. Học sinh cần quyết định sẽ thực hiện bao nhiêu lần thử. Từ những kinh nghiệm trước đó, học sinh biết rằng các tần suất tương đối thường gần với các xác suất thực nếu các em thực hiện một số lượng lớn lần thử. Cả lớp đã cùng nhau thực hiện một mô phỏng gồm hai trăm lần thử. Kết quả được tóm tắt trong bảng ở đầu trang kế tiếp.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 15%">
<col style="width: 34%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;">Số bạn nữ</td>
<td style="text-align: center;">Tần số</td>
<td style="text-align: center;">Xác suất thực nghiệm</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(121\)</span></td>
<td style="text-align: center;"><span class="math inline">\(.605\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(70\)</span></td>
<td style="text-align: center;"><span class="math inline">\(.350\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9\)</span></td>
<td style="text-align: center;"><span class="math inline">\(.045\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(200\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1.000\)</span></td>
</tr>
</tbody>
</table>
<p>Các xác suất thực nghiệm cung cấp những ước lượng cho các xác suất thực đối với từng kết quả có thể xảy ra, đồng thời minh họa cách diễn giải xác suất theo tần số tương đối trong dài hạn.</p>
<p><strong>Trong lớp học (Lớp Thống kê trung học phổ thông)</strong></p>
<p>Học sinh có thể quay lại bài toán này trong lớp thống kê sau khi đã học về sơ đồ cây và đang học về các quy tắc xác suất. Cả lớp đã xây dựng sơ đồ cây ở bên dưới để mô tả giới tính của hai học sinh được chọn.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fhsm_2009_p82_1_vi.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>Học sinh được yêu cầu mô tả chuỗi kết quả có thứ tự về giới tính sao cho số bạn nữ được chọn là <span class="math inline">\(0\)</span>. Với kết quả này, chuỗi có thứ tự phải là:</p>
<div class="indent-both">
<p>Chọn nam ở lượt thứ nhất và chọn nam ở lượt thứ hai.</p>
</div>
<p>Học sinh được yêu cầu xác định xác suất để học sinh thứ nhất được chọn là nam; cả lớp đều đồng ý rằng đó là</p>
<p><span class="math display">\[
  \frac{40}{50},
\]</span></p>
<p>hay <span class="math inline">\(0.8\)</span>.</p>
<p>Sau đó, học sinh được yêu cầu suy nghĩ về xác suất để học sinh thứ hai được chọn là nam, và nhiều em trả lời là</p>
<p><span class="math display">\[
  \frac{39}{49}.
\]</span></p>
<p>Giáo viên hỏi các em đã đưa ra giả định nào khi xác định xác suất này, và cả lớp đồng ý rằng xác suất đó giả định học sinh thứ nhất được chọn là nam. Giáo viên chỉ ra rằng</p>
<p><span class="math display">\[
  \frac{39}{49}
\]</span></p>
<p>được gọi là một xác suất “có điều kiện” và biểu thị xác suất để học sinh thứ hai được chọn là nam, với điều kiện học sinh thứ nhất đã được chọn là nam. Sau đó, giáo viên hỏi về xác suất của chuỗi có thứ tự “chọn nam ở lượt thứ nhất và chọn nam ở lượt thứ hai”. Một học sinh trả lời rằng chuỗi này chỉ có thể xảy ra nếu chọn nam ở lượt thứ nhất và, với điều kiện đã chọn nam ở lượt thứ nhất, chọn nam ở lượt thứ hai. Tức là,</p>
<p><span class="math display">\[
\begin{aligned}
  P(0 \, \text{nữ})
    &amp;= P(\text{Nam được chọn ở lượt 1 và nam được chọn ở lượt 2})\\
    &amp;= P(\text{Nam được chọn ở lượt 1})P(\text{Nam được chọn ở lượt 2 khi nam đã được chọn ở lượt 1}) \\
    &amp;= \frac{40}{50}\cdot\frac{39}{49}.
\end{aligned}
\]</span></p>
<p>Giáo viên nhân cơ hội này giới thiệu quy tắc nhân của xác suất:</p>
<p><span class="math display">\[
  P(\text{$A$ và $B$})
    = P(A)P(\text{$B$ biết rằng $A$ đã xảy ra}).
\]</span></p>
<p>Cả lớp mở rộng sơ đồ cây để thể hiện các xác suất có điều kiện cho kết quả về giới tính ở mỗi giai đoạn chọn, chuỗi giới tính có thứ tự, và số bạn nữ được chọn ứng với mỗi chuỗi.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fhsm_2009_p83_1_vi.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>Bằng cách lần theo sơ đồ cây và sử dụng quy tắc nhân, cả lớp xác định từng xác suất sau đây:</p>
<p><span class="math display">\[
\begin{aligned}
  P(\text{Không nữ})
    &amp;=(40/50)(39/49) \approx .637, \\
  P(\text{Một nữ})
    &amp;=(10/50)(40/49)+(40/50)(10/49) \approx .327, \,\text{và} \\
  P(\text{Hai nữ})
    &amp;=P(\text{Nữ ở lượt 1 và nữ ở lượt 2})=(10/50)(9/49) \approx .037.
\end{aligned}
\]</span></p>
<p>Sau đó, giáo viên yêu cầu học sinh suy nghĩ câu hỏi sau như một bài tập về nhà:</p>
<div class="indent-left">
<p>Giả sử giới tính của học sinh được chọn ở lượt thứ nhất không được biết. Ta quan tâm đến xác suất để học sinh được chọn ở lượt thứ hai là nữ (không phụ thuộc giới tính của học sinh lượt thứ nhất). Xác suất này là —</p>
<p><span class="math display">\[
P(\text{Nữ được chọn ở lượt 2})
  =\frac{10}{50}.
\]</span></p>
<p>Em có thể giải thích vì sao đây là xác suất đúng không?</p>
</div>
<p><strong>Trong lớp học (Lớp 12)</strong></p>
<p>Học sinh có thể quay lại bài toán này ở lớp 12 sau khi đã học các quy tắc đếm. Lớp được hướng dẫn sử dụng các quy tắc đếm để xác định xác suất cho từng kết quả có thể xảy ra về số bạn nữ trong ban phụ trách, đồng thời diễn giải các xác suất đó. Việc xem lại cùng một bài toán ở mức độ cao hơn tạo cơ hội cho học sinh tạo lập ý nghĩa đối với mô phỏng mà các em đã thực hiện trước đó.</p>
<p>Học sinh được nhắc rằng</p>
<p><span class="math display">\[
  C(m,k)=\frac{m!}{k!(m-k)!}
\]</span></p>
<p>đếm số tập con có kích thước <span class="math inline">\(k\)</span> được chọn từ <span class="math inline">\(m\)</span> phần tử phân biệt.</p>
<p>Trong bài toán này, ta có <span class="math inline">\(C(50,2)\)</span>, tức <span class="math inline">\(1225\)</span>, tập con (ban) có kích thước hai được chọn từ câu lạc bộ năm mươi học sinh. Vì việc chọn là ngẫu nhiên, ta có thể giả sử rằng mỗi ban có khả năng được chọn như nhau. Số ban có —</p>
<div class="indent-left">
<p>đúng <span class="math inline">\(0\)</span> bạn nữ (và đúng <span class="math inline">\(2\)</span> bạn nam) là <span class="math inline">\(C(10,0)\cdot C(40,2)\)</span>, tức <span class="math inline">\(780\)</span>;</p>
<p>đúng <span class="math inline">\(1\)</span> bạn nữ (và đúng <span class="math inline">\(1\)</span> bạn nam) là <span class="math inline">\(C(10,1)\cdot C(40,1)\)</span>, tức <span class="math inline">\(400\)</span>;</p>
<p>đúng <span class="math inline">\(2\)</span> bạn nữ (và đúng <span class="math inline">\(0\)</span> bạn nam) là <span class="math inline">\(C(10,2)\cdot C(40,0)\)</span>, tức <span class="math inline">\(45\)</span>.</p>
</div>
<p>Vì vậy, các xác suất toán học được trình bày trong bảng sau:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 45%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;">Số bạn nữ</td>
<td style="text-align: center;">Xác suất</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{780}{1225}\approx .637\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{400}{1225}\approx .327\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{45 }{1225}\approx .037\)</span></td>
</tr>
</tbody>
</table>
<p>Ví dụ này có thể được dùng như một cơ sở để phát triển công thức tổng quát nhằm tính các xác suất kiểu này khi lấy mẫu từ một quần thể hữu hạn. Giả sử ta có một quần thể gồm <span class="math inline">\(N\)</span> đối tượng và mỗi đối tượng được phân loại là “thành công” hoặc “thất bại”. Trong quần thể đó, có <span class="math inline">\(M\)</span> đối tượng là “thành công”. Ta dự định chọn ngẫu nhiên <span class="math inline">\(n\)</span> đối tượng và đếm số “thành công” trong số các đối tượng được chọn. Trong tình huống này, số “thành công” được gọi là một <em>biến ngẫu nhiên siêu bội</em>, và xác suất để thu được đúng <span class="math inline">\(x\)</span> “thành công” được cho bởi</p>
<p><span class="math display">\[
  P(x)=\frac{C(M,x)\cdot C(N-M,n-x)}{C(N,n)}.
\]</span></p>
<p><strong><em>Tóm tắt Ví dụ 20</em></strong></p>
<p>Lưu ý rằng các xác suất ước lượng từ mô phỏng trong nhiệm vụ đầu tiên gần với các xác suất thu được bằng cách đếm hoặc sử dụng sơ đồ cây. Các xác suất sau này cho thấy rằng nếu hai thành viên được chọn ngẫu nhiên lặp đi lặp lại từ câu lạc bộ, thì trong một lần chọn bất kỳ, việc có đúng không bạn nữ là khả dĩ nhất và sẽ xảy ra xấp xỉ <span class="math inline">\(64\)</span> phần trăm số lần. Việc có đúng một bạn nữ trong ban là khá phổ biến và sẽ xảy ra xấp xỉ <span class="math inline">\(33\)</span> phần trăm số lần. Ngoài ra, vì xác suất có đúng hai bạn nữ nhỏ hơn <span class="math inline">\(0.04\)</span> nên việc ban có hai bạn nữ là một trường hợp không thường gặp. Việc xem xét bài toán này từ góc nhìn thống kê được trình bày trong Ví dụ 21.</p>
<p><strong>Các yếu tố then chốt toán học</strong></p>
<p>Luận với Thống kê và Xác suất—Mô hình hóa sự biến thiên</p>
<p>Luận với số và đo lường—Đếm</p>
<p><strong>Thói quen luận</strong></p>
<p>Phân tích bài toán—xác định các khái niệm, quy trình hoặc biểu diễn liên quan</p>
<p>Triển khai chiến lược—thực hiện suy luận logic</p>
<p>Tìm kiếm và sử dụng các mối liên hệ</p>
<p>Suy ngẫm về lời giải—diễn giải lời giải; khái quát hóa lời giải</p>
<!-- Bình giải -->
<p><strong>BÌNH GIẢI</strong></p>
<p>Ví dụ 20 được thiết kế như một tiến trình nhiều tầng, nhằm làm nổi bật cách luận xác suất được xây dựng dần từ trực giác đến hình thức. Cùng một bài toán được nhìn qua ba lăng kính: mô phỏng thực nghiệm, mô hình hóa bằng sơ đồ cây với xác suất có điều kiện và quy tắc nhân, rồi quy tắc đếm ở mức độ cao hơn.</p>
<p>Phần mô phỏng nhấn mạnh cách hiểu xác suất theo tần suất trong dài hạn. Việc yêu cầu học sinh thiết kế phép mô phỏng buộc các em phải mô hình hóa tình huống: quyết định cách mã hóa, chọn thiết bị ngẫu nhiên, quyết định số lần thử, và hiểu vì sao khi số lần thử đủ lớn thì tần suất có xu hướng tiến gần xác suất thực.</p>
<p>Phần sơ đồ cây đưa học sinh từ trải nghiệm sang cấu trúc. Sự xuất hiện của xác suất có điều kiện ở đây không phải là một công thức được cho sẵn, mà là hệ quả tự nhiên của việc rút không hoàn lại. Qua đó, học sinh thấy rõ vì sao quy tắc nhân là cần thiết khi các bước chọn không độc lập với nhau.</p>
<p>Phần lớp 12 đưa vào quy tắc đếm và mở ra sự khái quát hóa ở trường hợp siêu bội. Đây là một bước quan trọng: thay vì chỉ giải một bài toán riêng lẻ, học sinh được dẫn đến một khuôn mẫu tổng quát cho việc lấy mẫu từ một quần thể hữu hạn, từ đó đặt nền cho tư duy mô hình và suy luận thống kê.</p>
<p><strong>Ghi chú về có thứ tự và không</strong></p>
<p>Trong Ví dụ 20, việc xét thứ tự chọn học sinh không nhằm thay đổi bản chất của bài toán, vì điều bài toán quan tâm rốt cuộc vẫn là số nữ sinh trong ban. Việc đưa thứ tự vào nhằm làm nổi bật cấu trúc của một quá trình ngẫu nhiên nhiều bước. Nhờ đó, xác suất có điều kiện và quy tắc nhân có thể xuất hiện một cách tự nhiên, trước khi học sinh chuyển sang cách tiếp cận không xét thứ tự bằng các quy tắc đếm ở lớp 12.</p>
<p>Nhưng có phải xét đến thứ tự là làm sai bản chất của bài toán?</p>
<p><em>Không.</em></p>
<p>Vì:</p>
<ul>
<li>Mỗi ban không có thứ tự tương ứng với hai chuỗi có thứ tự: <span class="math inline">\((\text{nam}, \text{nữ}) \leftrightarrow (\text{nữ}, \text{nam})\)</span>.</li>
<li>Khi cộng hai xác suất có thứ tự ấy, ta trở lại đúng xác suất của ban có <span class="math inline">\(1\)</span> nữ:</li>
</ul>
<p><span class="math display">\[
\frac{10}{50}\cdot\frac{40}{49}+\frac{40}{50}\cdot\frac{10}{49}
= \frac{C(10,1)\cdot C(40,1)}{C(50,2)}.
\]</span></p>
<p>Nói cách khác, việc xét theo thứ tự không làm đổi bài toán; nó chỉ biểu diễn bài toán dưới một dạng thuận lợi hơn để làm lộ ra cấu trúc xác suất của quá trình chọn.</p>
<p><strong>Ghi chú về công thức nhân <span class="math inline">\(P(A\cap B)=P(A)P(B\mid A)\)</span></strong></p>
<p>Về mặt trực giác, ta dùng phép nhân trong công thức</p>
<p><span class="math display">\[
P(A\cap B)=P(A)P(B\mid A)
\]</span></p>
<p>vì sự kiện “<span class="math inline">\(A\)</span> và <span class="math inline">\(B\)</span>” ở đây được hiểu như một quá trình gồm hai bước liên tiếp: trước hết rơi vào <span class="math inline">\(A\)</span>, rồi trong điều kiện <span class="math inline">\(A\)</span> đã xảy ra, tiếp tục rơi vào <span class="math inline">\(B\)</span>. Xác suất của toàn bộ quá trình vì thế bằng tỉ lệ đi qua được bước thứ nhất nhân với tỉ lệ đi qua được bước thứ hai. Phép nhân ở đây không phải là một quy ước áp đặt từ bên ngoài, mà là hệ quả trực tiếp của cách hiểu cấu trúc của “và” trong một quá trình xác suất nhiều bước.</p>
<p>Về mặt toán học, xác suất có điều kiện được lấy làm định nghĩa, và công thức nhân là hệ quả trực tiếp của định nghĩa ấy. Tuy nhiên, trong dạy học, người ta thường dẫn dắt học sinh đến công thức nhân thông qua các quá trình nhiều bước và sơ đồ cây, rồi sau đó mới giới thiệu khái niệm xác suất có điều kiện để hợp thức hóa điều mà trực giác đã nắm được.</p>
<p>Trong hệ thống Kolmogorov, xác suất có điều kiện không phải là một tiên đề mà là một định nghĩa. Nó không đặt thêm một ràng buộc mới lên xác suất, mà chỉ đặt tên cho một biểu thức đã được xác định từ khuôn khổ tiên đề của độ đo xác suất. Vì vậy, công thức xác suất có điều kiện không được gọi là tiên đề, dù nó giữ vai trò nền tảng trong suy luận xác suất.</p>
<!--  -->
</section>
<div class="three-cols">
<div class="row">
<section id="connecting-statistics-and-probability" class="level3 col-original">
<h3 class="anchored" data-anchor-id="connecting-statistics-and-probability">Connecting Statistics and Probability</h3>
</section>
<section id="kết-nối-thống-kê-và-xác-suất" class="level3 col-translation">
<h3 class="anchored" data-anchor-id="kết-nối-thống-kê-và-xác-suất">Kết nối Thống kê và Xác suất</h3>
</section>
<div class="col-notes">

</div>
</div>
</div>
<!--  -->
<div class="three-cols">
<div class="row">
<div class="col-original">
<p>By incorporating randomness into data collection, probability provides a way to make sense of the variation in sample results from one sample to another. The sampling distribution of a sample statistic (e.g., the sample mean, the sample median, the number of successes or the proportion of successes in the sample) summarizes the long-run behavior of the statistic from repeated random sampling. The sampling distribution provides a mechanism for describing the variation expected in a sample statistic and for determining whether an observed value might be reasonable from chance variation or whether it is more likely due to some other factor. The activity “Sampling Rectangles” in <em>Navigating through Data Analysis in Grades 9–12</em> (Burrill et al.&nbsp;2003) illustrates important ideas related to the sampling distribution of the sample mean. The probability distribution developed in example 20 represents the sampling distribution for the number of girls (successes) in a random sample of size two selected from a club of fifty students with ten girls and forty boys. Sampling distributions make crucial links among data analysis, probability, and inferential reasoning in statistics. The following example illustrates foundational ideas underlying the reasoning in inferential statistics by considering the reasonableness of a solution and revisiting initial assumptions.</p>
</div>
<div class="col-translation">
<p>Bằng cách đưa yếu tố ngẫu nhiên vào việc thu thập dữ liệu, xác suất cung cấp một cách để hiểu sự biến thiên của các kết quả mẫu từ mẫu này sang mẫu khác. Phân phối lấy mẫu của một thống kê mẫu, chẳng hạn trung bình mẫu, trung vị mẫu, số lần thành công, hay tỉ lệ thành công trong mẫu, tóm lược hành vi dài hạn của thống kê ấy qua việc lấy mẫu ngẫu nhiên lặp đi lặp lại. Phân phối lấy mẫu cung cấp một cơ chế để mô tả mức biến thiên có thể được chờ đợi ở một thống kê mẫu, đồng thời để xác định xem một giá trị quan sát được có thể được xem là hợp lí do biến thiên ngẫu nhiên hay nhiều khả năng là do một nhân tố khác. Hoạt động “Sampling Rectangles” trong <em>Navigating through Data Analysis in Grades 9–12</em> (Burrill et al.&nbsp;2003) minh họa những ý tưởng quan trọng liên quan đến phân phối lấy mẫu của trung bình mẫu. Phân phối xác suất được xây dựng trong Ví dụ 20 biểu diễn phân phối lấy mẫu của số học sinh nữ, tức số lần thành công, trong một mẫu ngẫu nhiên cỡ hai được chọn từ một câu lạc bộ gồm năm mươi học sinh, trong đó có mười nữ và bốn mươi nam. Các phân phối lấy mẫu tạo ra những mối nối then chốt giữa phân tích dữ liệu, xác suất, và suy luận thống kê. Ví dụ tiếp theo minh họa những ý tưởng nền tảng nằm dưới lối luận trong suy luận thống kê, thông qua việc xét tính hợp lí của một lời giải và xem xét lại những giả định ban đầu.</p>
</div>
<div class="col-notes">
<p>Sự khó hiểu trước hết nằm ở chỗ có quá nhiều tầng đối tượng chồng lên nhau: dữ liệu, mẫu, thống kê mẫu, xác suất, rồi phân phối lấy mẫu. Muốn đọc đoạn văn này cho sáng, cần tách các tầng ấy ra.</p>
<p>Khi chỉ nhìn vào một mẫu cụ thể, chẳng hạn lấy ngẫu nhiên hai học sinh trong một câu lạc bộ rồi đếm số học sinh nữ, kết quả thu được chỉ là một giá trị. Nhưng nếu hình dung việc lấy mẫu ấy được lặp đi lặp lại rất nhiều lần, thì số học sinh nữ trong mẫu sẽ không luôn giống nhau. Có lúc là <span class="math inline">\(0\)</span>, có lúc là <span class="math inline">\(1\)</span>, có lúc là <span class="math inline">\(2\)</span>. Sự thay đổi ấy chính là biến thiên từ mẫu này sang mẫu khác.</p>
<p>Xác suất được đưa vào để mô tả biến thiên đó. Nó cho phép không chỉ nói rằng các kết quả khác nhau có thể xảy ra, mà còn nói mỗi kết quả có khả năng xảy ra đến mức nào. Khi đó, thay vì chỉ có một kết quả mẫu đơn lẻ, ta có cả một bức tranh về tất cả những kết quả có thể xuất hiện cùng với khả năng của chúng. Bức tranh ấy là phân phối lấy mẫu.</p>
<p>Vì vậy, phân phối lấy mẫu không phải là phân phối của từng cá nhân trong quần thể, cũng không phải là phân phối của toàn bộ dữ liệu gốc. Nó là phân phối của một đại lượng được tính từ mẫu. Đại lượng ấy có thể là trung bình mẫu, trung vị mẫu, số lần thành công, hay tỉ lệ thành công. Nói ngắn gọn, phân phối lấy mẫu mô tả một thống kê mẫu sẽ biến động ra sao nếu việc lấy mẫu ngẫu nhiên được lặp lại nhiều lần.</p>
<p>Chỗ then chốt nằm ở đây: một giá trị quan sát được từ mẫu chỉ thật sự có ý nghĩa khi được đặt vào bối cảnh của phân phối lấy mẫu. Nếu một giá trị nằm trong vùng thường gặp của phân phối ấy, thì nó có thể được xem là hợp lí do biến thiên ngẫu nhiên. Nếu nó rơi vào vùng rất hiếm, thì cần nghĩ đến khả năng có một nguyên nhân khác, chứ không chỉ do ngẫu nhiên.</p>
<p>Ví dụ 20 được nhắc tới để làm đúng bước nối đó. Trong ví dụ ấy, xác suất không còn đứng riêng như một bài toán đếm thuần túy, mà trở thành công cụ mô tả số học sinh nữ trong một mẫu ngẫu nhiên cỡ hai. Nhờ vậy, xác suất bắt đầu gắn trực tiếp với một kết quả thống kê có thể quan sát được từ mẫu. Đó chính là chỗ nối giữa phân tích dữ liệu và suy luận thống kê.</p>
<p>Điểm sâu hơn là: suy luận thống kê không bắt đầu từ việc “kết luận ngay từ dữ liệu”, mà từ việc hỏi xem dữ liệu quan sát được có bình thường hay bất thường nếu chỉ có ngẫu nhiên tác động. Muốn trả lời câu hỏi đó, phải biết ngẫu nhiên tự nó có thể tạo ra những gì. Phân phối lấy mẫu là công cụ để mô tả điều đó.</p>
<p>Nếu cần nói cực ngắn, có thể hiểu toàn bộ ý của đoạn văn như sau:</p>
<p>Lấy mẫu ngẫu nhiên tạo ra biến thiên giữa các mẫu; xác suất mô tả biến thiên ấy; phân phối lấy mẫu cho biết một thống kê mẫu thường biến động như thế nào; và nhờ đó mới có cơ sở để đánh giá một kết quả quan sát được là hợp lí hay bất thường.</p>
</div>
</div>
</div>
<!--  -->
<div class="three-cols">
<div class="row">
<section id="example-21-what-are-the-chances-part-b" class="level4 col-original">
<h4 class="anchored" data-anchor-id="example-21-what-are-the-chances-part-b">Example 21: What Are the Chances? Part B</h4>
<p>In example 20 we looked at the hypothetical question of selecting two people for a committee and asking what might happen in terms of the number of girls selected. Suppose the president of the club forms the committee and both members are girls. We have now selected a sample and have data on the gender of each student selected. Reporting that the number of girls on the committee is two summarizes the sample data. After hearing the results, the girls in the club questioned the fairness in the selection of the committee. They pointed out that if the committee members were truly chosen at random, then the probability that both are girls is only <span class="math inline">\(.037\)</span> and, because this probability is small, a committee resulting in two girls is unlikely to occur. For this reason, they questioned whether the selection process was fair.</p>
<p><strong>In the Classroom (Twelfth-Grade Mathematics Class)</strong></p>
<p>This type of reasoning is the foundation for statistical inference. In this example we assume that the committee-selection process is truly random, and we use this assumption to determine the probability (sampling) distribution for the number of girls on the committee. We then ask how likely the observed result (two girls) is on the basis of this probability distribution. Because this probability is small, the data cast doubt on the assumption that the selection is truly random and thus fair.</p>
<p><strong>Key Elements of Mathematics</strong></p>
<p>Reasoning with Statistics and Probability—Connecting statistics and probability</p>
<p><strong>Reasoning Habits</strong></p>
<p>Seeking and using connections</p>
<p>Reflecting on a solution—considering the reasonableness of a solution; revisiting initial assumptions</p>
</section>
<section id="ví-dụ-21-bao-nhiêu-khả-năng-phần-b" class="level4 col-translation">
<h4 class="anchored" data-anchor-id="ví-dụ-21-bao-nhiêu-khả-năng-phần-b">Ví dụ 21: Bao nhiêu khả năng? Phần B</h4>
<p>Trong Ví dụ 20, chúng ta đã xem xét một câu hỏi mang tính giả định: chọn hai người vào một ban và hỏi điều gì có thể xảy ra đối với số bạn nữ được chọn. Giả sử rằng chủ tịch câu lạc bộ đã lập ban và cả hai thành viên đều là nữ. Khi đó, ta đã chọn được một mẫu và có dữ liệu về giới tính của từng học sinh được chọn. Việc báo cáo rằng số bạn nữ trong ban là hai chính là cách tóm tắt dữ liệu mẫu. Sau khi nghe kết quả, các bạn nữ trong câu lạc bộ đã đặt câu hỏi về tính công bằng của quá trình lựa chọn ban. Các bạn chỉ ra rằng nếu các thành viên của ban thực sự được chọn ngẫu nhiên, thì xác suất để cả hai đều là nữ chỉ là <span class="math inline">\(0.037\)</span>; và vì xác suất này nhỏ, nên việc một ban gồm hai bạn nữ là một kết quả ít có khả năng xảy ra. Vì lý do đó, các bạn nghi ngờ rằng quá trình lựa chọn ban có thực sự công bằng hay không.</p>
<p><strong>Trong lớp học (Lớp Toán lớp 12)</strong></p>
<p>Kiểu lập luận này chính là nền tảng của thống kê suy diễn. Trong ví dụ này, ta giả định rằng quá trình lựa chọn ban là thực sự ngẫu nhiên, và sử dụng giả định đó để xác định phân bố xác suất (lấy mẫu) của số bạn nữ trong ban. Sau đó, ta đặt câu hỏi: kết quả quan sát được (hai bạn nữ) có khả năng xảy ra đến mức nào dựa trên phân bố xác suất này? Vì xác suất đó nhỏ, nên dữ liệu khiến ta nghi ngờ giả định rằng việc lựa chọn là thực sự ngẫu nhiên và do đó là công bằng.</p>
<p><strong>Các yếu tố then chốt toán học</strong></p>
<p>Luận với Thống kê và Xác suất—Kết nối thống kê và xác suất</p>
<p><strong>Thói quen lập luận</strong></p>
<p>Tìm kiếm và sử dụng các kết nối</p>
<p>Suy ngẫm về một lời giải—xem xét tính hợp lí của một lời giải; xem xét lại những giả định ban đầu</p>
</section>
<div class="col-notes">
<p>Ví dụ 21 chỉ thực sự sáng khi được đặt trong quan hệ trực tiếp với Ví dụ 20. Ở Ví dụ 20, xác suất được dùng để mô tả phân bố của những kết quả có thể xảy ra dưới một giả định đã chấp nhận, ở đây là giả định việc chọn ủy ban diễn ra ngẫu nhiên. Ở Ví dụ 21, một kết quả cụ thể đã xuất hiện, và câu hỏi chuyển thành: kết quả ấy có còn hợp lí nếu vẫn giữ giả định ban đầu hay không. Chính sự chuyển vai này là điểm cốt lõi. Cùng một đại lượng “số học sinh nữ được chọn” trước hết được xét như một biến ngẫu nhiên có phân phối xác suất, rồi sau đó được đọc như một dữ liệu đã quan sát được để đánh giá lại giả định đã đặt ra.</p>
<p>Điểm quan trọng cần giữ là: xác suất nhỏ không tự động cho phép kết luận rằng quy trình đã không công bằng. Điều mà nó cho phép là một kết luận dè dặt hơn và đúng bản chất hơn: nếu một kết quả có xác suất rất nhỏ dưới giả định ngẫu nhiên, thì kết quả ấy tạo ra lí do để nghi ngờ giả định ngẫu nhiên ấy. Đây là hình thức sơ khởi của suy luận thống kê. Dữ liệu không chứng minh trực tiếp giả định là sai; dữ liệu được dùng để xem giả định ấy còn đáng tin đến mức nào.</p>
<p>Vì thế, chỗ nối giữa xác suất và thống kê hiện ra rất rõ. Xác suất cung cấp mô hình cho biến thiên có thể có nếu giả định ban đầu là đúng. Thống kê dùng chính mô hình đó để đánh giá dữ liệu đã quan sát được. Không có bước thứ nhất thì bước thứ hai không có nền để đứng. Cũng vì vậy, Ví dụ 20 và 21 nên được đọc như hai nửa của cùng một ý tưởng, chứ không phải hai ví dụ rời nhau.</p>
<p>Một tình huống kinh điển có thể thay thế đồng thời cả Ví dụ 20 lẫn 21 là thí nghiệm tung đồng xu nhiều lần để kiểm tra giả định đồng xu công bằng. Tình huống này đặc biệt thích hợp cho giảng dạy trên lớp vì có thể thực hiện trực tiếp, dữ liệu được tạo ra ngay trước mắt học sinh, và toàn bộ cấu trúc của cặp Ví dụ 20–21 có thể được tái hiện một cách trong sáng hơn.</p>
<p>Có thể tổ chức thành hai pha tương ứng.</p>
<p>Ở pha thứ nhất, đặt giả định rằng đồng xu là công bằng. Khi tung <span class="math inline">\(n\)</span> lần, số lần xuất hiện mặt ngửa là một biến ngẫu nhiên. Từ đây có thể lập phân phối xác suất của số lần ngửa. Nếu chọn <span class="math inline">\(n\)</span> nhỏ, chẳng hạn <span class="math inline">\(n=4\)</span> hoặc <span class="math inline">\(n=5\)</span>, học sinh có thể tự liệt kê hoặc dùng lập luận đếm để tìm xác suất của từng kết quả có thể có. Đây là phần tương ứng với Ví dụ 20: câu hỏi trung tâm là nếu giả định ban đầu đúng, thì những kết quả nào có thể xảy ra và với xác suất bao nhiêu. Như vậy, học sinh thấy rõ vai trò của xác suất trong việc mô tả biến thiên của một kết quả mẫu.</p>
<p>Ở pha thứ hai, thật sự tung đồng xu trên lớp, hoặc để một nhóm học sinh tung <span class="math inline">\(20\)</span> lần hay <span class="math inline">\(30\)</span> lần, rồi ghi nhận số lần ngửa thu được. Giả sử kết quả là <span class="math inline">\(18\)</span> lần ngửa trong <span class="math inline">\(20\)</span> lần tung. Lúc ấy câu hỏi thay đổi: nếu đồng xu thực sự công bằng, thì kết quả như vậy có hợp lí không. Muốn trả lời, học sinh phải quay lại phân phối xác suất đã có hoặc dùng nó để tính xác suất của những kết quả “ít nhất cũng cực đoan như thế”. Đây là phần tương ứng với Ví dụ 21: dữ liệu đã có, và nhiệm vụ là đánh giá dữ liệu ấy dưới giả định ban đầu. Nếu xác suất rất nhỏ, học sinh có cơ sở để nói rằng dữ liệu làm suy yếu giả định đồng xu công bằng.</p>
<p>Ưu điểm sư phạm của tình huống này là nó làm lộ rất rõ ba tầng:</p>
<ul>
<li>giả định ban đầu;</li>
<li>mô hình xác suất dưới giả định ấy;</li>
<li>dữ liệu quan sát được và việc xem lại giả định.</li>
</ul>
<p>Nó cũng có lợi thế thực hành mà cặp Ví dụ 20–21 không có rõ bằng: học sinh có thể trực tiếp tham gia tạo dữ liệu, nên bước chuyển từ “khả năng có thể xảy ra” sang “điều đã xảy ra” trở nên sống động hơn nhiều. Chính vì thế, thí nghiệm tung đồng xu là một tình huống thay thế rất tốt nếu mục tiêu là dạy mối nối giữa xác suất và suy luận thống kê trong một khuôn khổ gọn, rõ, và có thể triển khai ngay trong lớp.</p>
</div>
</div>
</div>
<!--  -->
<div class="three-cols">
<div class="row">
<section id="interpreting-designed-statistical-studies" class="level3 col-original">
<h3 class="anchored" data-anchor-id="interpreting-designed-statistical-studies">Interpreting Designed Statistical Studies</h3>
</section>
<section id="diễn-giải-các-nghiên-cứu-thống-kê-được-thiết-kế" class="level3 col-translation">
<h3 class="anchored" data-anchor-id="diễn-giải-các-nghiên-cứu-thống-kê-được-thiết-kế">Diễn giải các nghiên cứu thống kê được thiết kế</h3>
</section>
<div class="col-notes">

</div>
</div>
</div>
<!--  -->
<div class="three-cols">
<div class="row">
<div class="col-original">
<p>Statistical inference involves drawing conclusions from, and making decisions based on, data obtained through designed sample surveys or experiments. Students should understand that the scope of inference for a study is related to the manner in which the data are collected. Data from studies that properly use random selection (sample surveys) or random assignment (experiments) can be used to estimate population characteristics from sample results or to determine whether a result is statistically significant. Sampling distributions offer a way to quantify the uncertainty associated with statistical inference. The reasoning employed in statistical inference is often quite difficult for students; however, using a simulation to create a sampling distribution offers an intuitive way to help students develop inferential reasoning skills. The following example illustrates the reasoning employed in designing and interpreting a simulation for detecting whether a statistically significant difference exists between two groups and presents an interpretation of a solution under uncertain conditions.</p>
</div>
<div class="col-translation">
<p>Thống kê suy diễn liên quan đến việc rút ra kết luận và đưa ra quyết định dựa trên dữ liệu thu được từ những nghiên cứu được thiết kế dưới dạng khảo sát mẫu hoặc thí nghiệm. Học sinh cần hiểu rằng phạm vi suy luận của một nghiên cứu gắn chặt với cách dữ liệu được thu thập. Dữ liệu từ những nghiên cứu sử dụng đúng đắn phép chọn mẫu ngẫu nhiên, trong khảo sát mẫu, hoặc phép phân công ngẫu nhiên, trong thí nghiệm, có thể được dùng để ước lượng các đặc trưng của quần thể từ kết quả mẫu, hoặc để xác định xem một kết quả có ý nghĩa thống kê hay không. Các phân phối lấy mẫu cung cấp một cách để định lượng mức độ bất định gắn với suy luận thống kê. Kiểu luận được dùng trong thống kê suy diễn thường khá khó đối với học sinh; tuy nhiên, việc dùng mô phỏng để tạo ra một phân phối lấy mẫu đem lại một con đường trực quan giúp học sinh phát triển năng lực suy luận thống kê. Ví dụ tiếp theo minh họa kiểu luận được sử dụng khi thiết kế và diễn giải một mô phỏng nhằm phát hiện xem có tồn tại một khác biệt có ý nghĩa thống kê giữa hai nhóm hay không, đồng thời cho thấy cách diễn giải một lời giải trong điều kiện bất định.</p>
</div>
<div class="col-notes">
<p>Suy luận thống kê được đặt ở đây trên hai loại nghiên cứu được thiết kế: khảo sát mẫu và thí nghiệm. Điểm cần phân biệt là khảo sát mẫu dựa vào chọn mẫu ngẫu nhiên để suy ra từ mẫu về quần thể, còn thí nghiệm dựa vào phân công ngẫu nhiên để so sánh các nhóm và xem một khác biệt quan sát được có thể gắn với tác động đang xét hay không. Vì thế, phạm vi của kết luận không thể tách rời cách dữ liệu được tạo ra.</p>
<p>Phân phối lấy mẫu là công cụ làm cho bước suy luận ấy trở nên khả dĩ. Nó không mô tả bản thân quần thể, mà mô tả cách một thống kê mẫu sẽ biến động nếu việc lấy mẫu hoặc phân nhóm được lặp lại theo cùng một cơ chế ngẫu nhiên. Nhờ đó, một kết quả quan sát được mới có thể được đặt vào bối cảnh: đó là một kết quả vẫn thường xuất hiện do ngẫu nhiên, hay là một kết quả đủ hiếm để khiến giả định ban đầu cần được xem xét lại.</p>
<p>Mô phỏng xuất hiện ở đây không như một loại nghiên cứu thứ ba, mà như một phương tiện để làm lộ phân phối lấy mẫu. Khi việc lặp lại lấy mẫu hay phân nhóm không thể thực hiện trực tiếp với số lượng lớn, mô phỏng cho phép tái tạo cơ chế ngẫu nhiên ấy nhiều lần và làm cho mức độ bất định trở nên nhìn thấy được. Theo nghĩa đó, mô phỏng là con đường trực quan để học sinh đi từ dữ liệu quan sát được tới suy luận thống kê.</p>
</div>
</div>
</div>
<!-- Example 22 -->
<section id="example-22-meaningful-words-part-b" class="level4">
<h4 class="anchored" data-anchor-id="example-22-meaningful-words-part-b">Example 22: Meaningful Words, Part B</h4>
<p><strong>Task</strong></p>
<p>In example 19, the difference between the medians for the number of words recalled (Meaningful – Nonsense) was four words, and the fact that this difference is positive lends support to the conjecture that students tend to do better recalling meaningful words than they do recalling nonsense words. Random assignment was used to divide the class into two groups in the hope of producing comparable groups. That is, random assignment is likely to produce two similar groups with regard to all variables at the beginning of the study, and the only difference between the two groups at the end of the study is that one received meaningful words to memorize and the other received nonsense words. Probability provides a way to assess the strength of the evidence found in the difference between the medians. Specifically, because random assignment should produce similar groups, is the observed difference between the medians reasonable from the chance variation that occurs from random assignment, or is this difference likely to be due to the fact that one list contained meaningful words and the other list contained nonsense words?</p>
<p>Design and implement a simulation to address this question.</p>
<p><strong>In the Classroom (Twelfth-Grade Class)</strong></p>
<p>Students are assumed to have had some exposure to random assignment as a method for controlling for confounding variables and for creating comparable groups in an experimental study. After a class discussion, students reasoned that if the different lists (meaningful and nonsense words) have no effect on memorization, then the observed difference between the medians is due only to the variability expected from the random assignment to groups (i.e., due to the fact that student-to-student differences will be present). Note that a similar type of reasoning was employed in example 21 when students assumed that the selection process was truly random.</p>
<p>If the different lists have no effect on memorization, then a student’s score does not depend on whether he or she memorized meaningful words or nonsense words. Consequently, the number of words recalled by a student would be the same regardless of the group assigned. This situation can be simulated by writing each of the thirty scores on index cards (one score per card), shuffling the cards, and dealing out fifteen cards. The fifteen cards dealt represent scores for the meaningful words; the remaining fifteen cards represent the scores for the nonsense words. The median for each group and the difference between the two medians (meaningful – nonsense) can be determined. Because the original conjecture for this problem is that people will perform better with meaningful words, we are interested in knowing how often this difference is <span class="math inline">\(+4\)</span> or more. Repeating this simulation <span class="math inline">\(100\)</span> times produced the simulated sampling distribution shown in the dotplot below for the difference between the two medians.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fhsm_2009_p88_1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>On the basis of this simulation, when no difference is assumed between the effects of the two types of words on memorization, a difference between medians of +4 or more occurred only two times out of <span class="math inline">\(100\)</span> trials. This result suggests that a difference between medians this large (<span class="math inline">\(+4\)</span>) or larger is unlikely to occur from chance variation alone. Thus, this difference between medians would be unusual when no difference exists between the effects of the two types of words on memorization; so the use of meaningful words does seem to help when trying to memorize.</p>
<p>Because this argument is based on a simulation of only <span class="math inline">\(100\)</span> trials, the statistical reasoning employed here is transitional in nature, from informal to formal. If similar results occurred after performing the simulation with a large number of trials, or if the exact probability distribution for the difference between the medians was available and indicated a similar small probability for a difference of <span class="math inline">\(+4\)</span> or more, then we could say that the difference between the medians is statistically significant (would not be expected as a result of chance variation). In this example the data provide fairly strong evidence that the use of meaningful words does help when trying to memorize.</p>
<p>(A more detailed illustration of students’ reasoning in this problem is presented in the supporting topic book on statistics and probability.)</p>
<p><strong>Key Elements of Mathematics</strong></p>
<p>Reasoning with Statistics and Probability—Modeling variability; Connecting statistics and probability; Interpreting designed statistical studies</p>
<p><strong>Reasoning Habits</strong> Analyzing a problem—deciding whether a statistical solution is appropriate; making preliminary deductions and conjectures; seeking patterns and relationships</p>
<p>Implementing a strategy—making purposeful use of procedures; organizing the solution; making logical deductions</p>
<p>Seeking and using connections</p>
<p>Reflecting on a solution—revisiting initial assumptions; justifying or validating a solution; interpreting a solution</p>
<!-- Ví dụ 22 -->
</section>
<section id="ví-dụ-22-những-từ-có-nghĩa-phần-b" class="level4">
<h4 class="anchored" data-anchor-id="ví-dụ-22-những-từ-có-nghĩa-phần-b">Ví dụ 22: Những từ có nghĩa, Phần B</h4>
<p>Trong Ví dụ 19, hiệu giữa hai trung vị của số từ được ghi nhớ (Có nghĩa - Vô nghĩa) là bốn từ, và việc hiệu này dương đã củng cố giả thuyết rằng học sinh có xu hướng ghi nhớ các từ có nghĩa tốt hơn so với các từ vô nghĩa. Việc phân công ngẫu nhiên được sử dụng để chia lớp thành hai nhóm với hy vọng tạo ra các nhóm tương đương. Cụ thể, phân công ngẫu nhiên có khả năng tạo ra hai nhóm tương tự nhau đối với tất cả các biến ở thời điểm bắt đầu nghiên cứu, và sự khác biệt duy nhất giữa hai nhóm ở cuối nghiên cứu là một nhóm được yêu cầu ghi nhớ các từ có nghĩa, còn nhóm kia ghi nhớ các từ vô nghĩa.</p>
<p>Xác suất cung cấp một cách thức để đánh giá mức độ mạnh yếu của bằng chứng thể hiện qua hiệu giữa hai trung vị. Cụ thể, vì phân công ngẫu nhiên được kỳ vọng tạo ra các nhóm tương tự nhau, nên câu hỏi đặt ra là: hiệu giữa hai trung vị quan sát được có hợp lý nếu chỉ do biến thiên ngẫu nhiên sinh ra từ việc phân công ngẫu nhiên hay không, hay hiệu này nhiều khả năng là do việc một danh sách gồm các từ có nghĩa còn danh sách kia gồm các từ vô nghĩa?</p>
<p>Hãy thiết kế và triển khai một mô phỏng để giải quyết câu hỏi này.</p>
<p><strong>Trong lớp học (Lớp 12)</strong></p>
<p>Giả định rằng học sinh đã có một mức độ làm quen nhất định với phân công ngẫu nhiên như một phương pháp kiểm soát các biến gây nhiễu và tạo ra các nhóm tương đương trong một nghiên cứu thực nghiệm. Sau khi thảo luận trong lớp, học sinh luận rằng nếu hai danh sách (từ có nghĩa và từ vô nghĩa) không có ảnh hưởng gì đến khả năng ghi nhớ, thì hiệu giữa hai trung vị quan sát được chỉ là kết quả của biến thiên được kỳ vọng từ việc phân công ngẫu nhiên vào các nhóm (tức là do sự khác biệt tự nhiên giữa các học sinh). Lưu ý rằng một kiểu luận tương tự đã được sử dụng trong Ví dụ 21, khi học sinh giả định rằng quá trình lựa chọn là thực sự ngẫu nhiên.</p>
<p>Nếu hai danh sách khác nhau không ảnh hưởng gì đến việc ghi nhớ, thì điểm số của một học sinh sẽ không phụ thuộc vào việc em ấy ghi nhớ các từ có nghĩa hay các từ vô nghĩa. Vì thế, số từ mà một học sinh nhớ lại sẽ là như nhau bất kể em ấy được phân vào nhóm nào. Tình huống này có thể được mô phỏng bằng cách viết mỗi một trong ba mươi điểm số lên một thẻ riêng, mỗi thẻ một điểm, rồi xáo các thẻ ấy và chia ra mười lăm thẻ. Mười lăm thẻ được chia ra sẽ biểu diễn các điểm số của nhóm các từ có nghĩa; mười lăm thẻ còn lại sẽ biểu diễn các điểm số của nhóm các từ vô nghĩa. Khi đó có thể xác định trung vị của mỗi nhóm và chênh lệch giữa hai trung vị, (có nghĩa - vô nghĩa). Vì phỏng đoán ban đầu của bài toán này là người học sẽ làm tốt hơn với các từ có nghĩa, nên điều ta muốn biết là chênh lệch này xảy ra ở mức <span class="math inline">\(+4\)</span> hoặc lớn hơn với tần suất bao nhiêu. Lặp lại mô phỏng này <span class="math inline">\(100\)</span> lần cho ra phân phối lấy mẫu mô phỏng, được biểu diễn trong biểu đồ chấm dưới đây, của chênh lệch giữa hai trung vị.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fhsm_2009_p88_1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>Dựa trên mô phỏng này, khi giả định rằng không có sự khác biệt giữa tác động của hai loại từ đối với việc ghi nhớ, thì hiệu giữa hai trung vị bằng <span class="math inline">\(+4\)</span> hoặc lớn hơn chỉ xảy ra hai lần trong <span class="math inline">\(100\)</span> lần thử. Kết quả này cho thấy một hiệu giữa hai trung vị lớn như vậy (<span class="math inline">\(+4\)</span>) hoặc lớn hơn khó có khả năng xảy ra chỉ do biến thiên ngẫu nhiên. Do đó, một hiệu giữa hai trung vị như thế là bất thường khi giả định rằng hai loại từ không có tác động khác nhau đến việc ghi nhớ; vì vậy, việc sử dụng các từ có nghĩa dường như thực sự giúp ích cho quá trình ghi nhớ.</p>
<p>Vì biện giải này dựa trên một mô phỏng chỉ gồm <span class="math inline">\(100\)</span> lần thử, nên kiểu luận thống kê được sử dụng ở đây mang tính chuyển tiếp, từ không hình thức sang hình thức. Nếu các kết quả tương tự xuất hiện khi thực hiện mô phỏng với số lần thử lớn hơn, hoặc nếu phân bố xác suất chính xác cho hiệu giữa hai trung vị được biết đến và cũng cho thấy xác suất nhỏ đối với hiệu <span class="math inline">\(+4\)</span> hoặc lớn hơn, thì ta có thể kết luận rằng hiệu giữa hai trung vị là có ý nghĩa thống kê (không được kỳ vọng xuất hiện do biến thiên ngẫu nhiên). Trong ví dụ này, dữ liệu cung cấp bằng chứng khá mạnh mẽ cho thấy việc sử dụng các từ có nghĩa giúp cải thiện khả năng ghi nhớ.</p>
<p>(Một minh họa chi tiết hơn về cách học sinh luận trong bài toán này được trình bày trong tài liệu chuyên đề hỗ trợ về thống kê và xác suất.)</p>
<p><strong>Các yếu tố then chốt của toán học</strong></p>
<p>Luận thống kê và xác suất—Mô hình hóa biến thiên; Kết nối thống kê và xác suất; Diễn giải các nghiên cứu thống kê được thiết kế</p>
<p><strong>Thói quen luận</strong></p>
<p>Phân tích vấn đề—quyết định xem một lời giải thống kê có thích hợp hay không; đưa ra những suy ra và phỏng đoán ban đầu; tìm kiếm các mẫu và các quan hệ</p>
<p>Triển khai chiến lược—sử dụng các thủ tục một cách có chủ đích; tổ chức lời giải; thực hiện những bước suy ra hợp lẽ</p>
<p>Tìm kiếm và sử dụng kết nối</p>
<p>Suy ngẫm lời giải—xem xét lại những giả định ban đầu; biện minh hoặc kiểm chứng một lời giải; diễn giải một lời giải</p>
<!-- Bình giải -->
<p><strong>BÌNH GIẢI</strong></p>
<p>Hiệu giữa hai trung vị bằng <span class="math inline">\(+4\)</span> tự nó chưa đủ để kết luận rằng các từ có nghĩa thực sự giúp ghi nhớ tốt hơn. Điều cần được xét không phải chỉ là độ lớn của hiệu ấy, mà là câu hỏi: nếu thật sự không có khác biệt nào giữa hai loại danh sách từ, thì một hiệu như vậy có còn là điều bình thường do cách chia nhóm ngẫu nhiên tạo ra hay không. Chính tại đây suy luận thống kê bắt đầu: một kết quả quan sát được chỉ có thể được đánh giá khi đặt nó trong quan hệ với một mô hình của biến thiên ngẫu nhiên.</p>
<p>Giả định nền của ví dụ là hai loại danh sách không tạo ra khác biệt thật sự đối với khả năng ghi nhớ. Khi giữ giả định ấy, điểm số được xem là thuộc về từng học sinh, còn việc một học sinh rơi vào nhóm “có nghĩa” hay “vô nghĩa” chỉ là hệ quả của phân công ngẫu nhiên. Như vậy, câu hỏi trung tâm trở thành: nếu chỉ thay đổi cách chia ngẫu nhiên ba mươi học sinh thành hai nhóm mười lăm và mười lăm, thì hiệu giữa hai trung vị thường dao động ra sao, và một giá trị bằng <span class="math inline">\(+4\)</span> hoặc lớn hơn xuất hiện thường xuyên hay hiếm.</p>
<p>Mô phỏng được đưa vào để trả lời chính câu hỏi đó. Vì chưa dễ tính trực tiếp xác suất của hiệu giữa hai trung vị ở mức phổ thông, học sinh giữ nguyên ba mươi điểm số đã có, rồi liên tục xáo trộn việc gán chúng vào hai nhóm. Mỗi lần chia lại như vậy tạo ra một “thế giới có thể xảy ra” dưới giả định không có tác động thật, từ đó cho ra một hiệu trung vị mới. Lặp lại nhiều lần sẽ tạo thành một phân bố mô phỏng của hiệu giữa hai trung vị. Phân bố ấy đóng vai trò chuẩn tham chiếu: nó cho thấy nếu không có khác biệt thật thì những hiệu nào là bình thường, những hiệu nào là hiếm.</p>
<p>Biểu đồ chấm vì thế không phải là hình vẽ trang trí thêm vào cho bài toán, mà là cách nhìn thấy trực tiếp biến thiên ngẫu nhiên do phân công ngẫu nhiên gây ra. Mỗi chấm là một lần mô phỏng; toàn bộ đám chấm cho biết hiệu trung vị sẽ phân bố ra sao nếu chỉ có ngẫu nhiên tác động. Khi giá trị quan sát được, ở đây là <span class="math inline">\(+4\)</span>, rơi vào vùng rất ít xuất hiện của phân bố ấy, nó trở thành một kết quả khó giải thích chỉ bằng ngẫu nhiên. Việc chỉ có <span class="math inline">\(2\)</span> lần trên <span class="math inline">\(100\)</span> lần mô phỏng cho hiệu bằng <span class="math inline">\(+4\)</span> hoặc lớn hơn cho thấy kết quả quan sát được là khá hiếm dưới giả định không tác động. Bởi vậy, dữ liệu tạo ra bằng chứng khá mạnh chống lại giả định ban đầu và nghiêng về phía nhận định rằng các từ có nghĩa thực sự giúp ghi nhớ tốt hơn.</p>
<p>Giá trị sư phạm đặc biệt của ví dụ nằm ở chỗ nó làm sáng tỏ toàn bộ xương sống của suy luận thống kê mà không cần đi thẳng vào một công thức kiểm định hình thức: bắt đầu từ một kết quả quan sát được, đặt một giả định nền, mô hình hóa biến thiên ngẫu nhiên dưới giả định ấy, rồi so sánh kết quả quan sát với mô hình để xem nó còn hợp lí hay không. Chính cấu trúc này nối liền dữ liệu thực nghiệm ở Ví dụ 19 với mô hình xác suất và phân bố lấy mẫu ở các ví dụ trước, và làm cho “ý nghĩa thống kê” hiện ra như tính hiếm của một kết quả dưới một giả định xác định, chứ không phải như một nhãn gắn thêm ở cuối lời giải.</p>


</section>

</main> <!-- /main -->
<!-- Overlay để click ra ngoài và đóng sidebar -->

<div class="sidebar-overlay" aria-hidden="true"></div>



<script>

  document.addEventListener("DOMContentLoaded", function () {

    const body = document.body;



    // Đảm bảo chỉ có 1 overlay trong DOM

    let overlay = document.querySelector(".sidebar-overlay");

    if (!overlay) {

      overlay = document.createElement("div");

      overlay.className = "sidebar-overlay";

      body.appendChild(overlay);

    } else {

      // xóa overlay dư thừa nếu có

      const all = document.querySelectorAll(".sidebar-overlay");

      for (let i = 1; i < all.length; i++) all[i].remove();

    }



    // Sidebar (ưu tiên #quarto-sidebar); nếu dùng lớp khác, thêm vào đây

    const sidebar = document.getElementById("quarto-sidebar");

    if (!sidebar) return;



    const toggles = Array.from(document.querySelectorAll(".quarto-btn-toggle, #quarto-header .quarto-btn-toggle"));



    // Gỡ data-bs-* để Bootstrap không tự toggle song song

    toggles.forEach(btn => {

      if (btn.hasAttribute("data-bs-toggle")) btn.removeAttribute("data-bs-toggle");

      if (btn.hasAttribute("data-bs-target")) btn.removeAttribute("data-bs-target");

    });



    const isOpen = () => sidebar.classList.contains("show");



    function openSidebar() {

      sidebar.classList.add("show");

      overlay.classList.add("active");

      overlay.style.display = "block";

      body.classList.add("sidebar-open");

      toggles.forEach(btn => btn.setAttribute("aria-expanded", "true"));

    }



    function closeSidebar() {

      sidebar.classList.remove("show");

      // tắt overlay ngay để không "kẹt xám"

      overlay.classList.remove("active");

      overlay.style.display = "none";

      body.classList.remove("sidebar-open");

      toggles.forEach(btn => btn.setAttribute("aria-expanded", "false"));

    }



    function toggleSidebar(e) {

      if (e) { e.preventDefault(); e.stopImmediatePropagation(); }

      if (isOpen()) closeSidebar(); else openSidebar();

    }



    // Bắt click toggle (capture để chạy trước handler khác)

    toggles.forEach(btn => {

      btn.addEventListener("click", toggleSidebar, { capture: true });

    });



    // Click overlay -> luôn đóng

    overlay.addEventListener("click", function (e) {

      e.preventDefault();

      e.stopImmediatePropagation();

      if (isOpen()) closeSidebar();

    }, { capture: true });



    // ESC -> đóng

    document.addEventListener("keydown", (e) => {

      if (e.key === "Escape" && isOpen()) closeSidebar();

    });



    // Đồng bộ ban đầu

    if (isOpen()) {

      overlay.classList.add("active");

      overlay.style.display = "block";

      body.classList.add("sidebar-open");

    } else {

      overlay.classList.remove("active");

      overlay.style.display = "none";

      body.classList.remove("sidebar-open");

    }

  });

</script>



<!-- nav#TOC -->



<script>

  document.addEventListener("DOMContentLoaded", function () {

    const body = document.body;



    // Lấy TOC Quarto (1 trong 3 biến thể)

    const rawToc =

      document.querySelector("nav#TOC") ||

      document.querySelector(".quarto-toc") ||

      document.querySelector(".toc");



    // Vùng breadcrumb/secondary nav để gắn nút & panel

    const secNav = document.querySelector("#quarto-header .quarto-secondary-nav");

    const secContainer = secNav?.querySelector(".container-fluid") || secNav;



    // ----- Tạo nút TOC: CHỈ ICON, KHÔNG CHỮ

    let tocBtn = secNav?.querySelector(".toc-toggle-btn");

    if (secContainer && !tocBtn) {

      tocBtn = document.createElement("button");

      tocBtn.type = "button";

      tocBtn.className = "toc-toggle-btn only-icon";

      tocBtn.setAttribute("aria-expanded", "false");

      tocBtn.setAttribute("aria-label", "Trên trang này");

      // Inline SVG (không phụ thuộc data-URI/CSP), nét rõ, dùng currentColor

      tocBtn.innerHTML = `

      <svg class="toc-icon" xmlns="http://www.w3.org/2000/svg"

           width="24" height="24" viewBox="0 0 24 24" fill="none"

           stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"

           aria-hidden="true" focusable="false">

        <path d="M10 6h10M10 12h10M10 18h10"></path>

        <circle cx="5" cy="6" r="1.15" fill="currentColor"></circle>

        <circle cx="5" cy="12" r="1.15" fill="currentColor"></circle>

        <circle cx="5" cy="18" r="1.15" fill="currentColor"></circle>

      </svg>

    `;

      const holder = document.createElement("div");

      holder.className = "toc-toggle-holder";

      holder.style.marginLeft = "auto";

      holder.appendChild(tocBtn);

      secContainer.appendChild(holder);

    }



    // ----- Chuẩn hoá panel TOC

    let tocEl = null;

    if (rawToc && secNav) {

      tocEl = rawToc;

      tocEl.classList.add("q-toc");

      // GIỮ id = "TOC" để ScrollSpy bắt đúng

      tocEl.id = "TOC";

      if (tocEl.parentElement !== secNav) secNav.appendChild(tocEl);

      tocEl.setAttribute("role", "region");

      tocEl.setAttribute("aria-label", "Trên trang này");

      tocBtn?.setAttribute("aria-controls", tocEl.id);

      const t = tocEl.querySelector(".toc-title, h2, h3");

      if (t) t.classList.add("toc-title");



      // Khởi tạo/refresh ScrollSpy sau khi đã di chuyển TOC

      initScrollSpy();

    }



    // ----- Toggle: chỉ bấm icon mới đóng/mở (KHÔNG close khi click ra ngoài)

    function toggleTOC() {

      if (!tocEl) return;

      const open = tocEl.classList.toggle("is-open");

      document.body.classList.toggle("toc-open", open);   // fallback cho CSS nếu cần

      tocBtn?.setAttribute("aria-expanded", String(open));

    }

    tocBtn?.addEventListener("click", toggleTOC);



    // Khi sidebar mở -> đóng TOC để tránh chồng chéo (giữ nguyên logic cũ)

    const mo = new MutationObserver(() => {

      if (body.classList.contains("sidebar-open")) {

        tocEl?.classList.remove("is-open");

        tocBtn?.setAttribute("aria-expanded", "false");

      }

    });

    mo.observe(body, { attributes: true, attributeFilter: ["class"] });



    // ----- Hàm khởi tạo Bootstrap ScrollSpy (đánh dấu mục đang đọc)

    function initScrollSpy() {

      if (!window.bootstrap) return; // Quarto thường có sẵn Bootstrap



      // Gắn thuộc tính cho body (nếu chưa có)

      document.body.setAttribute("data-bs-spy", "scroll");

      document.body.setAttribute("data-bs-target", "#TOC");



      // offset = navbar + breadcrumb (đọc từ CSS vars)

      const cs = getComputedStyle(document.documentElement);

      const nb = parseInt(cs.getPropertyValue("--navbar-h")) || 56;

      const bc = parseInt(cs.getPropertyValue("--bc-h")) || 32;

      const offset = nb + bc + 10;



      const spy = bootstrap.ScrollSpy.getOrCreateInstance(document.body, {

        target: "#TOC",

        offset

      });

      spy.refresh();



      // Refresh lại khi load xong ảnh/resize để tính chuẩn vị trí

      window.addEventListener("load", () => spy.refresh(), { once: true });

      window.addEventListener("resize", () => spy.refresh());

    }

  });

</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/zo-math\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><a href="#">Blog</a> | <a href="#">Help</a> | <a href="#">Credits</a> | <a href="#">Privacy Policy</a> | <a href="#">Contact Us</a><br>
<br> <a href="https://facebook.com/zo-math" title="Facebook"><i class="bi bi-facebook"></i></a> <a href="https://x.com/zo-math" title="X (Twitter)"><i class="bi bi-twitter-x"></i></a> <a href="https://www.youtube.com/@ZO-Math" title="YouTube"><i class="bi bi-youtube"></i></a><br>
<br> © 2025 <strong>ZO Math</strong></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>