---
title: "Mục lục sách What is Mathematics?"

author: ZO Math
date: last-modified
date-format: "DD-MM-YYYY"
---

```{r setup, include=FALSE}
```

CONTENTS

***Preface to Second Edition***

***Preface to Revised Editions***

***Preface to First Edition***

***How to Use the Book***

***What Is Mathematics?***


**Chapter I. *The Natural Numbers*** - *p. 1*

*Introduction*

*§1. Calculation with Integers* - *p. 1*

1. Laws of Arithmetic
2. The Representation of Integers
3. Computation in Systems Other than the Decimal

*§2. The Infinitude of the Number System. Mathematical Induction* - *p. 9*

1. The Principle of Mathematical Induction
2. The Arithmetical Progression
3. The Geometrical Progression
4. The Sum of the First $n$ Squares
5. An Important Inequality
6. The Binomial Theorem
7. Further Remarks on Mathematical Induction


**Supplement to Chapter I. *The Theory of Numbers*** - *p. 21*

*Introduction* - *p. 21*

*§1. The Prime Numbers* - *p. 21*

1. Fundamental Facts
2. The Distribution of the Primes

   a. Formulas Producing Primes
   b. Primes in Arithmetical Progressions
   c. The Prime Number Theorem
   d. Two Unsolved Problems Concerning Prime Numbers

*§2. Congruences* - *p. 31*

1. General Concepts
2. Fermat's Theorem
3. Quadratic Residues

*§3. Pythagorean Numbers and Fermat's Last Theorem* - *p. 40*

*§4. The Euclidean Algorithm* - *p. 42*

1. General Theory
2. Application to the Fundamental Theorem of Arithmetic
3. Euler's $\phi$ Function
4. Fermat's Theorem Again
5. Continued Fractions
6. Diophantine Equations


**Chapter II. *The Number System of Mathematics*** - *p. 52*

*Introduction* - *p. 52*

*§1. The Rational Numbers* - *p. 52*

1. Rational Numbers as a Device for Measuring
2. Intrinsic Need for the Rational Numbers
3. Principal of Generalization
4. Geometrical Interpretation of Rational Numbers

*§2. Incommensurable Segments, Irrational Numbers, and the Concept of Limit* - *p. 58*

1. Introduction
2. Decimal Fractions. Infinite Decimals
3. Limits. Infinite Geometrical Series
4. Rational Numbers and Periodic Decimals
5. General Definition of Irrational Numbers by Nested Intervals
6. Alternative Methods of Defining Irrational Numbers. Dedekind Cuts

*§3. Remarks on Analytic Geometry* - *p. 72*

1. The Basic Principle
2. Equations of Lines and Curves

*§4. The Mathematical Analysis of Infinity* - *p. 77*

1. Fundamental Concepts
2. The Denumerability of the Rational Numbers and the Non-Denumerability of the Continuum
3. Cantor's "Cardinal Numbers"
4. The Indirect Method of Proof
5. The Paradoxes of the Infinite
6. The Foundations of Mathematics

*§5. Complex Numbers* - *p. 88*

1. The Origin of Complex Numbers
2. The Geometrical Interpretation of Complex Numbers
3. De Moivre's Formula and the Roots of Unity
4. The Fundamental Theorem of Algebra

*§6. Algebraic and Transcendental Numbers* - *p. 103*

1. Definition and Existence
2. Liouville's Theorem and the Construction of Transcendental Numbers


**Supplement to Chapter II. *The Algebra of Sets*** - *p. 108*

1. General Theory
2. Application to Mathematical Logic
3. An Application to the Theory of Probability


**Chapter III. *Geometrical Constructions. The Algebra of Number Fields*** - *p. 117*

*Introduction* - *p. 117*

***Part I. Impossibility Proofs and Algebra*** - *p. 120*

*§1. Fundamental Geometrical Constructions* - *p. 120*

1. Construction of Fields and Square Root Extraction
2. Regular Polygons
3. Apollonius' Problem

*§2. Constructible Numbers and Number Fields* - *p. 127*

1. General Theory
2. All Constructible Numbers Are Algebraic

*§3. The Unsolvability of the Three Greek Problems* - *p. 134*

1. Doubling the Cube
2. A Theorem on Cubic Equations
3. Trisecting the Angle
4. The Regular Heptagon
5. Remarks on the Problem of Squaring the Circle

***Part II. Various Methods for Performing Constructions*** - *p. 140*

*§4. Geometrical Transformations. Inversion* - *p. 140*

1. General Remarks
2. Properties of Inversion
3. Geometrical Construction of Inverse Points
4. How to Bisect a Segment and Find the Center of a Circle with the Compass Alone

*§5. Constructions with Other Tools. Mascheroni Constructions with Compass Alone* - *p. 146*

1. A Classical Construction for Doubling the Cube
2. Restriction to the Use of the Compass Alone
3. Drawing with Mechanical Instruments. Mechanical Curves. Cycloids
4. Linkages. Peaucellier's and Hart's Inversors

*§6. More About Inversions and Its Applications* - *p. 158*

1. Invariance of Angles
2. Families of Circles
3. Application to the Problem of Apollonius
4. Repeated Reflections


**Chapter IV. Projective Geometry. Axiomatics. Non-Euclidean Geometries** - *p. 165*

*§1. Introduction* - *p. 166*

1. Classification of Geometrical Properties. Invariance under Transformations
2. Projective Transformations

*§2. Fundamental Concepts* - *p. 168*

1. The Group of Projective Transformations
2. Desargues's Theorem

*§3. Cross-Ratio* - *p. 172*

1. Definition and Proof of Invariance
2. Application to the Complete Quadrilateral

*§4. Parallelism and Infinity*- *p. 180*

1. Points at Infinity as "Ideal Points"
2. Ideal Elements and Projection
3. Cross-Ratio with Elements at Infinity

*§5. Applications* - *p. 185*

1. Preliminary Remarks
2. Proof of Desargues's Theorem in the Plane
3. Pascal's Theorem
4. Brianchon's Theorem
5. Remark on Duality

*§6. Analytic Representation* - *p. 191*

1. Introductory Remarks
2. Homogeneous Coordinates
3. The Algebraic Basis of Duality

*§7. Problems on Constructions with the Straightedge Alone* - *p. 196*

*§8. Conics and Quadric Surfaces* - *p. 198*

1. Elementary Metric Geometry of Conics
2. Projective Properties of Conics
3. Conics as Line Curves
4. Pascal's and Brianchon's General Theorems for Conics
5. The Hyperboloid

*§9. Axiomatics and Non-Euclidean Geometry* - *p. 214*

1. The Axiomatic Method
2. Hyperbolic Non-Euclidean Geometry
3. Geometry and Reality
4. Poincaré's Model
5. Elliptic or Riemannian Geometry

**Appendix: *Geometry in More Than Three Dimensions*** - *p. 227*

1. Introduction
2. Analytic Approach
3. Geometrical or Combinatorial Approach


**Chapter V. *Topology*** - *p. 235*

*Introduction* - *p. 235*

*§1. Euler's Formula for Polyhedra* - *p. 236*

*§2. Topological Properties of Figures* - *p. 241*

1. Topological Properties
2. Connectivity

*§3. Other Examples of Topological Theorems* - *p. 244*

1. The Jordan Curve Theorem
2. The Four Color Problem
3. The Concept of Dimension
4. A Fixed Point Theorem
5. Knots

*§4. The Topological Classification of Surfaces* - *p. 256*

1. The Genus of a Surface
2. The Euler Characteristic of a Surface
3. One-Sided Surfaces

**Appendix** - *p. 264*

1. The Five Color Theorem
2. The Jordan Curve Theorem for Polygons
3. The Fundamental Theorem of Algebra


**Chapter VI. *Functions and Limits*** - *p. 272*

*Introduction* - *p. 273*

*§1. Variable and Function* - *p. 273*

1. Definitions and Examples
2. Radian Measure of Angles
3. The Graph of a Function. Inverse Functions
4. Compound Functions
5. Continuity
6. Functions of Several Variables
7. Functions and Transformations

*§2. Limits* - *p. 289*

1. The Limit of a Sequence $a_n$
2. Monotone Sequences
3. Euler's Number $e$
4. The Number $\pi$
5. Continued Fractions

*§3. Limits by Continuous Approach* - *p. 303*

1. Introduction. General Definition
2. Remarks on the Limit Concept
3. The Limit of $\frac{\sin x}{x}$
5. Limits as $x \to \infty$

*§4. Precise Definition of Continuity* - *p. 310*

*§5. Two Fundamental Theorems on Continuous Functions* - *p. 312*

1. Bolzano's Theorem
2. Proof of Bolzano's Theorem
3. Weierstrass' Theorem on Extreme Values
4. A Theorem on Sequences. Compact Sets

*§6. Some Applications of Bolzano's Theorem* - *p. 317*

1. Geometrical Applications
2. Application to a Problem in Mechanics

**Supplement to Chapter VI. *More Examples on Limits and Continuity*** - *p. 322*

*§1. Examples of Limits* - *p. 322*

1. General Remarks. 
2. The Limit of $q^n$. 
3. The Limit of $\sqrt[n]{p}$. 
4. Discontinuous Functions as Limits of Continuous Functions
5. Limits by Iteration.

*§2. Example on Continuity* - *p. 327*


**Chapter VII. *Maxima and Minima*** - *p. 329*

*Introduction* - *p. 329*

*§1. Problems in Elementary Geometry* - *p. 330*

1. Maximum Area of a Triangle with Two Sides Given
2. Heron's Theorem. Extremum Property of Light Rays
3. Applications to Problems on Triangles
4. Tangent Properties of Ellipse and Hyperbola. Corresponding Extremum Properties
5. Extreme Distances to a Given Curve

*§2. A General Principle Underlying Extreme Value Problems* - *p. 338*

1. The Principle
2. Examples

*§3. Stationary Points and the Differential Calculus* - *p. 341*

1. Extrema and Stationary Points
2. Maxima and Minima of Functions of Several Variables. Saddle Points
3. Minimax Points and Topology
4. The Distance from a Point to a Surface

*§4. Schwarz's Triangle Problem* - *p. 346*

1. Schwarz's Proof
2. Another Proof
3. Obtuse Triangles
4. Triangles Formed by Light Rays
5. Remarks Concerning Problems of Reflection and Ergodic Motion

*§5. Steiner's Problem* - *p. 354*

1. Problem and Solution
2. Analysis of the Alternatives
3. A Complementary Problem
4. Remarks and Exercises
5. Generalization to the Street Network Problem

*§6. Extrema and Inequalities* - *p. 361*

1. The Arithmetical and Geometrical Mean of Two Positive Quantities
2. Generalization to $n$ Variables
3. The Method of Least Squares

*§7. The Existence of an Extremum. Dirichlet's Principle* - *p. 366*

1. General Remarks
2. Examples
3. Elementary Extremum Problems
4. Difficulties in Higher Cases

*§8. The Isoperimetric Problem* - *p. 373*

*§9. Extremum Problems with Boundary Conditions. Connection Between Steiner's Problem and the Isoperimetric Problem* - *p. 376*

*§10. The Calculus of Variations* - *p. 379*

1. Introduction
2. The Calculus of Variations. Fermat's Principle in Optics
3. Bernoulli's Treatment of the Brachistochrone Problem
4. Geodesics on a Sphere. Geodesics and Maxi-Minima

*§11. Experimental Solutions of Minimum Problems. Soap Film Experiments* - *p. 385*

1. Introduction
2. Soap Film Experiments
3. New Experiments on Plateau's Problem
4. Experimental Solutions of Other Mathematical Problems


**Chapter VIII. *The Calculus*** - *p. 398*

*Introduction* - *p. 398*

*§1. The Integral* - *p. 399*

1. Area as a Limit
2. The Integral
3. General Remarks on the Integral Concept. General Definition
4. Examples of Integration. Integration of $x^r$
5. Rules for the "Integral Calculus"

*§2. The Derivative* - *p. 414*

1. The Derivative as a Slope
2. The Derivative as a Limit
3. Examples
4. Derivatives of Trigonometrical Functions
5. Differentiation and Continuity
6. Derivative and Velocity. Second Derivative and Acceleration
7. Geometrical Meaning of the Second Derivative
8. Maxima and Minima

*§3. The Technique of Differentiation* - *p. 427*

*§4. Leibniz' Notation and the "Infinitely Small"* - *p. 433*

*§5. The Fundamental Theorem of the Calculus* - *p. 436*

1. The Fundamental Theorem
2. First Applications. Integration of $x^r$, $\cos x$, $\sin x$, $\arctan x$ 
3. Leibniz' Formula for $\pi$

*§6. The Exponential Function and the Logarithm* - *p. 442*

1. Definition and Properties of the Logarithm. Euler's Number $e$
2. The Exponential Function
3. Formulas for Differentiation of $e^x$, $a^x$, $x^n$
4. Explicit Expressions for $e^x$, $e^{-x}$, $\log x$ as Limits
5. Infinite Series for the Logarithm. Numerical Calculation

*§7. Differential Equations* - *p. 453*

1. Definition
2. The Differential Equation of the Exponential Function. Radioactive Disintegration. Law of Growth. Compound Interest
3. Other Examples. Simplest Vibrations
4. Newton's Law of Dynamics


**Supplement to Chapter VIII.** - *p. 462*

*§1. Matters of Principle* - *p. 462*

1. Differentiability
2. The Integral. 
3. Other Applications of the Concept of Integral. Work. Length.

*§2. Orders of Magnitude* - *p. 469*

1. The Exponential Function and Powers of $x$
2. Order of Magnitude of $\log (n!)$

*§3. Infinite Series and Infinite Products* - *p. 472*

1. Infinite Series of Functions. 
2. Euler’s Formula, $\cos x + i \sin x=e^{ix}$. 
3. The Harmonic Series and the Zeta Function. Euler’s Product for the Sine.

*§4. The Prime Number Theorem Obtained by Statistical Methods* - *p. 482*


**Chapter IX. *Recent Developments*** - *p. 487*

*§1. A Formula for Primes* - *p. 487*

*§2. The Goldbach Conjecture and Twin Primes* - *p. 488*

*§3. Fermat's Last Theorem* - *p. 491*

*§4. The Continuum Hypothesis* - *p. 493*

*§5. Set-Theoretic Notation* - *p. 494*

*§6. The Four Color Theorem* - *p. 495*

*§7. Hausdorff Dimension and Fractals* - *p. 499*

*§8. Knots* - *p. 501*

*§9. A Problem in Mechanics* - *p. 505*

*§10. Steiner's Problem* - *p. 507*

*§11. Soap Films and Minimal Surfaces* - *p. 513*

*§12. Nonstandard Analysis* - *p. 518*


**Appendix: *Supplementary Remarks, Problems, and Exercises*** - *p. 525*

*Arithmetic and Algebra* - *p. 525*

*Analytic Geometry* - *p. 526*

*Geometrical Constructions* - *p. 532*

*Projective and Non-Euclidean Geometry* - *p. 533*

*Topology* - *p. 534*

*Functions, Limits, and Continuity* - *p. 537*

*Maxima and Minima* - *p. 538*

*The Calculus* - *p. 540*

*Technique of Integration* - *p. 542*

***Suggestions for Further Reading*** - *p. 549*

***Suggestions for Additional Reading*** - *p. 553*

***Index*** - *p. 559*

