---
title: "Biến ngẫu nhiên"

date: last-modified
date-format: "DD-MM-YYYY"
author: "ZO Math"
---

## Dẫn nhập

Mình có hai nhóm số, nhóm A bao gồm 0 và 1; nhóm B bao gồm 0, 1 và 1. Hai nhóm này chỉ chứa hai số 0 và 1, đó là điểm tương đồng. Nhưng nhóm B có nhiều số 1 hơn nhóm A, đó là điểm khác biệt.

Trong toán học, bạn có thể gọi nhóm A là *tập hợp* A, viết $A=\{0,1\}$. Khi bạn muốn nói đến một phần tử bất kỳ thuộc tập A, bạn có thể đặt tên cho nó - chẳng hạn như $x$. Khi đó, $x$ không mang một giá trị cố định, mà có thể là 0 hoặc 1, tùy theo việc phần tử nào được chọn trong A. Chính vì vậy, $x$ được gọi là một *biến* - nó biểu diễn một phần tử chưa biết cụ thể, nhưng thuộc về một tập đã xác định.

::: {.callout-important name="Biến" collapse="true" icon="false"}
Biến là một ký hiệu đại diện cho một phần tử chưa được cụ thể thuộc về một tập hợp đã cho.
:::

Nhóm B thì không phải một tập hợp vì khái niệm này không cho phép bên trong nó chứa các phần tử trùng lặp, trong nhóm B có đến hai số 1. Nhưng, tạm thời chúng mình vẫn có thể nói về biến trên nhóm B. 

Nếu bạn muốn tìm một tập hợp mô tả nhóm B, thì vẫn có cách, đó là sử dụng các cặp số. Cặp $(0,1)$ cho biết số 0 xuất hiện một lần trong nhóm B, cặp $(1,2)$ cho biết số 1 xuất hiện hai lần trong nhóm B. Các cặp số như thế không bao giờ giống nhau vì ít nhất các số đầu tiên trong cặp luôn luôn khác nhau. Vì thế, nhóm B có thể được mô tả bằng tập hợp $B=\{(0,1),(1,2)\}$, miễn là bạn nhớ cách thức mà bạn đã xây dựng nên tập B này.

Thành phần thứ hai trong mỗi cặp số trong tập B cho biết số lần xuất hiện của thành phần thứ nhất trong nhóm B, nói cách khác thành phần thứ hai là *tần số* của thành phần thứ nhất. 

Hãy phân tích kỹ hơn cách thức mà chúng mình đã xây dựng tập B. Chúng mình đã làm việc như sau:

- Gắn số 0 với số 1, và viết thành cặp $(0,1)$.
- Gắn số 1 với số 2, và van viết thành cặp $(1,2)$.

Tiếp theo ý này mình nên nói về HÀM.




Phương trình
$$
x(x-1)(2x-1)=0
$$






