---
title: "Chương trình giáo dục phổ thông môn Toán"
subtitle: "Ban hành kèm theo Thông tư số 32/2018/TT-BGDĐT ngày 26 tháng 12 năm 2018 của Bộ trưởng Bộ Giáo dục và Đào tạo"

author: "ZO Math"
date: last-modified
date-format: "DD-MM-YYYY"

format:
  html:
    page-layout: full
    include-in-header:
      text: |
        <style>
        table,
        th,
        td {
            border: 1px solid black;
            border-collapse: collapse;
        }

        th,
        td {
            padding: 8px;
            text-align: left;
        }
        </style>
---

```{r setup, include=FALSE}
```

# III. Mục tiêu chương trình 

## 1. Mục tiêu chung

Chương trình môn Toán giúp học sinh đạt các mục tiêu chủ yếu sau:

a. Hình thành và phát triển năng lực toán học bao gồm các thành tố cốt lõi sau: năng lực tư duy và lập luận toán học; năng lực mô hình hoá toán học; năng lực giải quyết vấn đề toán học; năng lực giao tiếp toán học; năng lực sử dụng công cụ, phương tiện học toán.
b. Góp phần hình thành và phát triển ở học sinh các phẩm chất chủ yếu và năng lực chung theo các mức độ phù hợp với môn học, cấp học được quy định tại Chương trình tổng thể.
c. Có kiến thức, kĩ năng toán học phổ thông, cơ bản, thiết yếu; phát triển khả năng giải quyết vấn đề có tính tích hợp liên môn giữa môn Toán và các môn học khác như Vật lí, Hoá học, Sinh học, Địa lí, Tin học, Công nghệ, Lịch sử, Nghệ thuật,...; tạo cơ hội để học sinh được trải nghiệm, áp dụng toán học vào thực tiễn.
d. Có hiểu biết tương đối tổng quát về sự hữu ích của toán học đối với từng ngành nghề liên quan để làm cơ sở định hướng nghề nghiệp, cũng như có đủ năng lực tối thiểu để tự tìm hiểu những vấn đề liên quan đến toán học trong suốt cuộc đời.

## 2. Mục tiêu cấp tiểu học

Môn Toán cấp tiểu học nhằm giúp học sinh đạt các mục tiêu chủ yếu sau:

a. Góp phần hình thành và phát triển năng lực toán học với yêu cầu cần đạt: thực hiện được các thao tác tư duy ở mức độ đơn giản; nêu và trả lời được câu hỏi khi lập luận, giải quyết vấn đề đơn giản; lựa chọn được các phép toán và công thức số học để trình bày, diễn đạt (nói hoặc viết) được các nội dung, ý tưởng, cách thức giải quyết vấn đề; sử dụng được ngôn ngữ toán học kết hợp với ngôn ngữ thông thường, động tác hình thể để biểu đạt các nội dung toán học ở những tình huống đơn giản; sử dụng được các công cụ, phương tiện học toán đơn giản để thực hiện các nhiệm vụ học tập toán đơn giản.
b. Có những kiến thức và kĩ năng toán học cơ bản ban đầu, thiết yếu về:
- Số và phép tính: Số tự nhiên, phân số, số thập phân và các phép tính trên những tập hợp số đó.
- Hình học và Đo lường: Quan sát, nhận biết, mô tả hình dạng và đặc điểm (ở mức độ trực quan) của một số hình phẳng và hình khối trong thực tiễn; tạo lập một số mô hình hình học đơn giản; tính toán một số đại lượng hình học; phát triển trí tưởng tượng không gian; giải quyết một số vấn đề thực tiễn đơn giản gắn với Hình học và Đo lường (với các đại lượng đo thông dụng).
- Thống kê và Xác suất: Một số yếu tố thống kê và xác suất đơn giản; giải quyết một số vấn đề thực tiễn đơn giản gắn với một số yếu tố thống kê và xác suất.
c. Cùng với các môn học và hoạt động giáo dục khác như: Đạo đức, Tự nhiên và xã hội, Hoạt động trải nghiệm,... góp phần giúp học sinh có những hiểu biết ban đầu về một số nghề nghiệp trong xã hội.

## 3. Mục tiêu cấp trung học cơ sở

Môn Toán cấp trung học cơ sở nhằm giúp học sinh đạt các mục tiêu chủ yếu sau:

a. Góp phần hình thành và phát triển năng lực toán học với yêu cầu cần đạt: nêu và trả lời được câu hỏi khi lập luận, giải quyết vấn đề, thực hiện được việc lập luận hợp lí khi giải quyết vấn đề, chứng minh được mệnh đề toán học không quá phức tạp; sử dụng được các mô hình toán học (công thức toán học, phương trình đại số, hình biểu diễn,...) để mô tả tình huống xuất hiện trong một số bài toán thực tiễn không quá phức tạp; sử dụng được ngôn ngữ toán học kết hợp với ngôn ngữ thông thường để biểu đạt các nội dung toán học cũng như thể hiện chứng cứ, cách thức và kết quả lập luận; trình bày được ý tưởng và cách sử dụng công cụ, phương tiện học toán để thực hiện một nhiệm vụ học tập hoặc để diễn tả những lập luận, chứng minh toán học.
b. Có những kiến thức và kĩ năng toán học cơ bản về:
- Số và Đại số: Hệ thống số (từ số tự nhiên đến số thực); tính toán và sử dụng công cụ tính toán; ngôn ngữ và kí hiệu đại số; biến đổi biểu thức đại số, phương trình, hệ phương trình, bất phương trình; sử dụng ngôn ngữ hàm số để mô tả (mô hình hoá) một số quá trình và hiện tượng trong thực tiễn.
- Hình học và Đo lường: Nội dung Hình học và Đo lường ở cấp học này bao gồm Hình học trực quan và Hình học phẳng. Hình học trực quan tiếp tục cung cấp ngôn ngữ, kí hiệu, mô tả (ở mức độ trực quan) những đối tượng của thực tiễn (hình phẳng, hình khối); tạo lập một số mô hình hình học thông dụng; tính toán một số yếu tố hình học; phát triển trí tưởng tượng không gian; giải quyết một số vấn đề thực tiễn đơn giản gắn với Hình học và Đo lường. Hình học phẳng cung cấp những kiến thức và kĩ năng (ở mức độ suy luận logic) về các quan hệ hình học và một số hình phẳng thông dụng (điểm, đường thẳng, tia, đoạn thẳng, góc, hai đường thẳng song song, tam giác, tứ giác, đường tròn).
- Thống kê và Xác suất: Thu thập, phân loại, biểu diễn, phân tích và xử lí dữ liệu thống kê; phân tích dữ liệu thống kê thông qua tần số, tần số tương đối; nhận biết một số quy luật thống kê đơn giản trong thực tiễn; sử dụng thống kê để hiểu các khái niệm cơ bản về xác suất thực nghiệm của một biến cố và xác suất của một biến cố; nhận biết ý nghĩa của xác suất trong thực tiễn.
c. Góp phần giúp học sinh có những hiểu biết ban đầu về các ngành nghề gắn với môn Toán; có ý thức hướng nghiệp dựa trên năng lực và sở thích, điều kiện và hoàn cảnh của bản thân; định hướng phân luồng sau trung học cơ sở (tiếp tục học lên, học nghề hoặc tham gia vào cuộc sống lao động).

## 4. Mục tiêu cấp trung học phổ thông

Môn Toán cấp trung học phổ thông nhằm giúp học sinh đạt các mục tiêu chủ yếu sau:

a. Góp phần hình thành và phát triển năng lực toán học với yêu cầu cần đạt: nêu và trả lời được câu hỏi khi lập luận, giải quyết vấn đề; sử dụng được các phương pháp lập luận, quy nạp và suy diễn để hiểu được những cách thức khác nhau trong việc giải quyết vấn đề; thiết lập được mô hình toán học để mô tả tình huống, từ đó đưa ra cách giải quyết vấn đề toán học đặt ra trong mô hình được thiết lập; thực hiện và trình bày được giải pháp giải quyết vấn đề và đánh giá được giải pháp đã thực hiện, phản ánh được giá trị của giải pháp, khái quát hoá được cho vấn đề tương tự; sử dụng được công cụ, phương tiện học toán trong học tập, khám phá và giải quyết vấn đề toán học.
b. Có những kiến thức và kĩ năng toán học cơ bản, thiết yếu về:
- Đại số và Một số yếu tố giải tích: Tính toán và sử dụng công cụ tính toán; sử dụng ngôn ngữ và kí hiệu đại số; biến đổi biểu thức đại số và siêu việt (lượng giác, mũ, lôgarit), phương trình, hệ phương trình, bất phương trình; nhận biết các hàm số sơ cấp cơ bản (luỹ thừa, lượng giác, mũ, lôgarit); khảo sát hàm số và vẽ đồ thị hàm số bằng công cụ đạo hàm; sử dụng ngôn ngữ hàm số, đồ thị hàm số để mô tả và phân tích một số quá trình và hiện tượng trong thế giới thực; sử dụng tích phân để tính toán diện tích hình phẳng và thể tích vật thể trong không gian.
- Hình học và Đo lường: Cung cấp những kiến thức và kĩ năng (ở mức độ suy luận logic) về các quan hệ hình học và một số hình phẳng, hình khối quen thuộc; phương pháp đại số (véc-tơ, toạ độ) trong hình học; phát triển trí tưởng tượng không gian; giải quyết một số vấn đề thực tiễn đơn giản gắn với Hình học và Đo lường.
- Thống kê và Xác suất: Hoàn thiện khả năng thu thập, phân loại, biểu diễn, phân tích và xử lí dữ liệu thống kê; sử dụng các công cụ phân tích dữ liệu thống kê thông qua các số đặc trưng đo xu thế trung tâm và đo mức độ phân tán cho mẫu số liệu không ghép nhóm và ghép nhóm; sử dụng các quy luật thống kê trong thực tiễn; nhận biết các mô hình ngẫu nhiên, các khái niệm cơ bản của xác suất và ý nghĩa của xác suất trong thực tiễn.
c. Góp phần giúp học sinh có những hiểu biết tương đối tổng quát về các ngành nghề gắn với môn Toán và giá trị của nó; làm cơ sở cho định hướng nghề nghiệp sau trung học phổ thông; có đủ năng lực tối thiểu để tự tìm hiểu những vấn đề liên quan đến toán học trong suốt cuộc đời.

# IV. Yêu cầu cần đạt

## 1. Yêu cầu cần đạt về phẩm chất chủ yếu và năng lực chung

Môn Toán góp phần hình thành và phát triển ở học sinh các phẩm chất chủ yếu và năng lực chung theo các mức độ phù hợp với môn học, cấp học đã được quy định tại Chương trình tổng thể.

## 2. Yêu cầu cần đạt về năng lực đặc thù

Môn Toán góp phần hình thành và phát triển cho học sinh năng lực toán học (biểu hiện tập trung nhất của năng lực tính toán) bao gồm các thành phần cốt lõi sau: năng lực tư duy và lập luận toán học; năng lực mô hình hoá toán học; năng lực giải quyết vấn đề toán học; năng lực giao tiếp toán học; năng lực sử dụng công cụ, phương tiện học toán.

Biểu hiện cụ thể của năng lực toán học và yêu cầu cần đạt cho từng cấp học được thể hiện trong bảng sau:

<div>
<table>
    <thead>
        <tr>
            <th>Thành phần năng lực</th>
            <th>Cấp tiểu học</th>
            <th>Cấp trung học cơ sở</th>
            <th>Cấp trung học phổ thông</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>
                <strong><em>Năng lực tư duy và lập luận toán học</em></strong>  thể hiện qua việc:
                <ul>
                    <li> Thực hiện được các thao tác tư duy như: so sánh, phân tích, tổng hợp, đặc biệt hoá, khái quát hoá, tương tự; quy nạp, diễn dịch.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li> Thực hiện được các thao tác tư duy (ở mức độ đơn giản), đặc biệt biết quan sát, tìm kiếm sự tương đồng và khác biệt trong những tình huống quen thuộc và mô tả được kết quả của việc quan sát.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li> Thực hiện được các thao tác tư duy, đặc biệt biết quan sát, giải thích được sự tương đồng và khác biệt trong nhiều tình huống và thể hiện được kết quả của việc quan sát.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Thực hiện được tương đối thành thạo các thao tác tư duy, đặc biệt phát hiện được sự tương đồng và khác biệt trong những tình huống tương đối phức tạp và lí giải được kết quả của việc quan sát.</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                <ul>
                    <li>Chỉ ra được chứng cứ, lí lẽ và biết lập luận hợp lí trước khi kết luận.</li>
                    <li>Giải thích hoặc điều chỉnh được cách thức giải quyết vấn đề về phương diện toán học.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Nêu được chứng cứ, lí lẽ và biết lập luận hợp lí trước khi kết luận.</li>
                    <li>Nêu và trả lời được câu hỏi khi lập luận, giải quyết vấn đề. Bước đầu chỉ ra được chứng cứ và lập luận có cơ sở, có lí lẽ trước khi kết luận.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Thực hiện được việc lập luận hợp lí khi giải quyết vấn đề.</li>
                    <li>Nêu và trả lời được câu hỏi khi lập luận, giải quyết vấn đề. Chứng minh được mệnh đề toán học không quá phức tạp.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Sử dụng được các phương pháp lập luận, quy nạp và suy diễn để nhìn ra những cách thức khác nhau trong việc giải quyết vấn đề.</li>
                    <li>Nêu và trả lời được câu hỏi khi lập luận, giải quyết vấn đề. Giải thích, chứng minh, điều chỉnh được giải pháp thực hiện về phương diện toán học.</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
            <strong><em>Năng lực mô hình hoá toán học</em></strong> thể hiện qua việc:
                <ul>
                    <li>Xác định được mô hình toán học (gồm công thức, phương trình, bảng biểu, đồ thị,...) cho tình huống xuất hiện trong bài toán thực tiễn.</li>
                    <li>Giải quyết được những vấn đề toán học trong mô hình được thiết lập.</li>
                    <li>Thể hiện và đánh giá được lời giải trong ngữ cảnh thực tế và cải tiến được mô hình nếu cách giải quyết không phù hợp.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Lựa chọn được các phép toán, công thức số học, sơ đồ, bảng biểu, hình vẽ để trình bày, diễn đạt (nói hoặc viết) được các nội dung, ý tưởng của tình huống xuất hiện trong bài toán thực tiễn đơn giản.</li>
                    <li>Giải quyết được những bài toán xuất hiện từ sự lựa chọn trên.</li>
                    <li>Nêu được câu trả lời cho tình huống xuất hiện trong bài toán thực tiễn.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Sử dụng được các mô hình toán học (gồm công thức toán học, sơ đồ, bảng biểu, hình vẽ, phương trình, hình biểu diễn,...) để mô tả tình huống xuất hiện trong một số bài toán thực tiễn không quá phức tạp.</li>
                    <li>Giải quyết được những vấn đề toán học trong mô hình được thiết lập.</li>
                    <li>Thể hiện được lời giải toán học vào ngữ cảnh thực tiễn và làm quen với việc kiểm chứng tính đúng đắn của lời giải.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Thiết lập được mô hình toán học (gồm công thức, phương trình, sơ đồ, hình vẽ, bảng biểu, đồ thị,...) để mô tả tình huống đặt ra trong một số bài toán thực tiễn.</li>
                    <li>Giải quyết được những vấn đề toán học trong mô hình được thiết lập.</li>
                    <li>Lí giải được tính đúng đắn của lời giải (những kết luận thu được từ các tính toán là có ý nghĩa, phù hợp với thực tiễn hay không). Đặc biệt, nhận biết được cách đơn giản hoá, cách điều chỉnh những yêu cầu thực tiễn (xấp xỉ, bổ sung thêm giả thiết, tổng quát hoá,...) để đưa đến những bài toán giải được.</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                <strong><em>Năng lực giải quyết vấn đề toán học</strong></em> thể hiện qua việc:
                <ul>
                    <li>Nhận biết, phát hiện được vấn đề cần giải quyết bằng toán học.</li>
                    <li>Lựa chọn, đề xuất được cách thức, giải pháp giải quyết vấn đề.</li>
                    <li>Sử dụng được các kiến thức, kĩ năng toán học tương thích (bao gồm các công cụ và thuật toán) để giải quyết vấn đề đặt ra.</li>
                    <li>Đánh giá được giải pháp đề ra và khái quát hoá được cho vấn đề tương tự.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Nhận biết được vấn đề cần giải quyết và nêu được thành câu hỏi.</li>
                    <li>Nêu được cách thức giải quyết vấn đề.</li>
                    <li>Thực hiện và trình bày được cách thức giải quyết vấn đề ở mức độ đơn giản.</li>
                    <li>Kiểm tra được giải pháp đã thực hiện.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Phát hiện được vấn đề cần giải quyết.</li>
                    <li>Xác định được cách thức, giải pháp giải quyết vấn đề.</li>
                    <li>Sử dụng được các kiến thức, kĩ năng toán học tương thích để giải quyết vấn đề.</li>
                    <li>Giải thích được giải pháp đã thực hiện.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Xác định được tình huống có vấn đề; thu thập, sắp xếp, giải thích và đánh giá được độ tin cậy của thông tin; chia sẻ sự am hiểu vấn đề với người khác.</li>
                    <li>Lựa chọn và thiết lập được cách thức, quy trình giải quyết vấn đề.</li>
                    <li>Thực hiện và trình bày được giải pháp giải quyết vấn đề.</li>
                    <li>Đánh giá được giải pháp đã thực hiện; phản ánh được giá trị của giải pháp; khái quát hoá được cho vấn đề tương tự.</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                <strong><em>Năng lực giao tiếp toán học</strong></em> thể hiện qua việc:
                <ul>
                    <li>Nghe hiểu, đọc hiểu và ghi chép được các thông tin toán học cần thiết được trình bày dưới dạng văn bản toán học hay do người khác nói hoặc viết ra.</li>
                    <li>Trình bày, diễn đạt (nói hoặc viết) được các nội dung, ý tưởng, giải pháp toán học trong sự tương tác với người khác (với yêu cầu thích hợp về sự đầy đủ, chính xác).</li>
                    <li>Sử dụng được hiệu quả ngôn ngữ toán học (chữ số, chữ cái, kí hiệu, biểu đồ, đồ thị, các liên kết logic,...) kết hợp với ngôn ngữ thông thường hoặc động tác hình thể khi trình bày, giải thích và đánh giá các ý tưởng toán học trong sự tương tác (thảo luận, tranh luận) với người khác.</li>
                    <li>Thể hiện được sự tự tin khi trình bày, diễn đạt, nêu câu hỏi, thảo luận, tranh luận các nội dung, ý tưởng liên quan đến toán học.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Nghe hiểu, đọc hiểu và ghi chép (tóm tắt) được các thông tin toán học trọng tâm trong nội dung văn bản hay do người khác thông báo (ở mức độ đơn giản), từ đó nhận biết được vấn đề cần giải quyết.</li>
                    <li>Trình bày, diễn đạt (nói hoặc viết) được các nội dung, ý tưởng, giải pháp toán học trong sự tương tác với người khác (chưa yêu cầu phải diễn đạt đầy đủ, chính xác). Nêu và trả lời được câu hỏi khi lập luận, giải quyết vấn đề.</li>
                    <li>Sử dụng được ngôn ngữ toán học kết hợp với ngôn ngữ thông thường, động tác hình thể để biểu đạt các nội dung toán học ở những tình huống đơn giản.</li>
                    <li>Thể hiện được sự tự tin khi trả lời câu hỏi, khi trình bày, thảo luận các nội dung toán học ở những tình huống đơn giản.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Nghe hiểu, đọc hiểu và ghi chép (tóm tắt) được các thông tin toán học cơ bản, trọng tâm trong văn bản (ở dạng văn bản nói hoặc viết). Từ đó phân tích, lựa chọn, trích xuất được các thông tin toán học cần thiết từ văn bản (ở dạng văn bản nói hoặc viết).</li>
                    <li>Thực hiện được việc trình bày, diễn đạt, nêu câu hỏi, thảo luận, tranh luận các nội dung, ý tưởng, giải pháp toán học trong sự tương tác với người khác (ở mức tương đối đầy đủ, chính xác).</li>
                    <li>Sử dụng được ngôn ngữ toán học kết hợp với ngôn ngữ thông thường để biểu đạt các nội dung toán học cũng như thể hiện chứng cứ, cách thức và kết quả lập luận.</li>
                    <li>Thể hiện được sự tự tin khi trình bày, diễn đạt, thảo luận, tranh luận, giải thích các nội dung toán học trong một số tình huống không quá phức tạp.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Nghe hiểu, đọc hiểu và ghi chép (tóm tắt) được tương đối thành thạo các thông tin toán học cơ bản, trọng tâm trong văn bản nói hoặc viết. Từ đó phân tích, lựa chọn, trích xuất được các thông tin toán học cần thiết từ văn bản nói hoặc viết.</li>
                    <li>Lí giải được (một cách hợp lí) việc trình bày, diễn đạt, thảo luận, tranh luận các nội dung, ý tưởng, giải pháp toán học trong sự tương tác với người khác.</li>
                    <li>Sử dụng được một cách hợp lí ngôn ngữ toán học kết hợp với ngôn ngữ thông thường để biểu đạt cách suy nghĩ, lập luận, chứng minh các khẳng định toán học.</li>
                    <li>Thể hiện được sự tự tin khi trình bày, diễn đạt, thảo luận, tranh luận, giải thích các nội dung toán học trong nhiều tình huống không quá phức tạp.</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                <strong><em>Năng lực sử dụng công cụ, phương tiện học toán</strong></em> thể hiện qua việc:
                <ul>
                    <li>Nhận biết được tên gọi, tác dụng, quy cách sử dụng, cách thức bảo quản các đồ dùng, phương tiện trực quan thông thường, phương tiện khoa học công nghệ (đặc biệt là phương tiện sử dụng công nghệ thông tin), phục vụ cho việc học Toán.</li>
                    <li>Sử dụng được các công cụ, phương tiện học toán, đặc biệt là phương tiện khoa học công nghệ để tìm tòi, khám phá và giải quyết vấn đề toán học (phù hợp với đặc điểm nhận thức lứa tuổi).</li>
                    <li>Nhận biết được các ưu điểm, hạn chế của những công cụ, phương tiện hỗ trợ để có cách sử dụng hợp lí.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Nhận biết được tên gọi, tác dụng, quy cách sử dụng, cách thức bảo quản các công cụ, phương tiện học toán đơn giản (que tính, thẻ số, thước, compa, êke, các mô hình hình phẳng và hình khối quen thuộc,...)</li>
                    <li>Sử dụng được các công cụ, phương tiện học toán để thực hiện những nhiệm vụ học tập toán đơn giản.</li>
                    <li>Làm quen với máy tính cầm tay, phương tiện công nghệ thông tin hỗ trợ học tập.</li>
                    <li>Nhận biết được (bước đầu) một số ưu điểm, hạn chế của những công cụ, phương tiện hỗ trợ để có cách sử dụng hợp lí.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Nhận biết được tên gọi, tác dụng, quy cách sử dụng, cách thức bảo quản các công cụ, phương tiện học toán (mô hình hình học phẳng và không gian, thước đo góc, thước cuộn, tranh ảnh, biểu đồ,...).</li>
                    <li>Trình bày được cách sử dụng công cụ, phương tiện học toán để thực hiện nhiệm vụ học tập hoặc để diễn tả những lập luận, chứng minh toán học.</li>
                    <li>Sử dụng được máy tính cầm tay, một số phần mềm tin học và phương tiện công nghệ hỗ trợ học tập</li>
                    <li>Chỉ ra được các ưu điểm, hạn chế của những công cụ, phương tiện hỗ trợ để có cách sử dụng hợp lí.</li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Nhận biết được tác dụng, quy cách sử dụng, cách thứ cảo quản các công cụ, phương tiện học toán (bảng tổng kết về các dạng hàm số, mô hình góc và cung lượng giác, mô hình các hình khối, bộ dụng cụ tạo mặt tròn xoay,...)</li>
                    <li>Sử dụng được máy tính cầm tay, phần mềm, phương tiện công nghệ, nguồn tài nguyên trên mạng Internet để giải quyết một số vấn đề toán học.</li>
                    <li>Đánh giá được cách thức sử dụng các công cụ, phương tiện học toán trong tìm tòi, khám phá và giải quyết vấn đề toán học.</li>
                </ul>
            </td>
        </tr>
    </tbody>
</table>
</div>

# V. Nội dung giáo dục 

## 1. Nội dung khái quát

### a. Nội dung cốt lõi

Nội dung môn Toán được tích hợp xoay quanh ba mạch kiến thức: Số, Đại số và Một số yếu tố giải tích; Hình học và Đo lường; Thống kê và Xác suất.

Số, Đại số và Một số yếu tố giải tích là cơ sở cho tất cả các nghiên cứu sâu hơn về toán học, nhằm hình thành những công cụ toán học để giải quyết các vấn đề của toán học và các lĩnh vực khoa học khác có liên quan; tạo cho học sinh khả năng suy luận suy diễn, góp phần phát triển tư duy logic, khả năng sáng tạo toán học và hình thành khả năng sử dụng các thuật toán. Hàm số cũng là công cụ quan trọng cho việc xây dựng các mô hình toán học của các quá trình và hiện tượng trong thế giới thực.

Hình học và Đo lường là một trong những thành phần quan trọng của giáo dục toán học, rất cần thiết cho học sinh trong việc tiếp thu các kiến thức về không gian và phát triển các kĩ năng thực tế thiết yếu. Hình học và Đo lường hình thành những công cụ nhằm mô tả các đối tượng, thực thể của thế giới xung quanh; cung cấp cho học sinh kiến thức, kĩ năng toán học cơ bản về Hình học, Đo lường (với các đại lượng đo thông dụng) và tạo cho học sinh khả năng suy luận, kĩ năng thực hiện các chứng minh toán học, góp phần vào phát triển tư duy logic, khả năng sáng tạo toán học, trí tưởng tượng không gian và tính trực giác. Đồng thời, Hình học còn góp phần giáo dục thẩm mĩ và nâng cao văn hoá toán học cho học sinh. Việc gắn kết Đo lường và Hình học sẽ tăng cường tính trực quan, thực tiễn của việc dạy học môn Toán.

Thống kê và Xác suất là một thành phần bắt buộc của giáo dục toán học trong nhà trường, góp phần tăng cường tính ứng dụng và giá trị thiết thực của giáo dục toán học. Thống kê và Xác suất tạo cho học sinh khả năng nhận thức và phân tích các thông tin được thể hiện dưới nhiều hình thức khác nhau, hiểu bản chất xác suất của nhiều sự phụ thuộc trong thực tế, hình thành sự hiểu biết về vai trò của thống kê như là một nguồn thông tin quan trọng về mặt xã hội, biết áp dụng tư duy thống kê để phân tích dữ liệu. Từ đó, nâng cao sự hiểu biết và phương pháp nghiên cứu thế giới hiện đại cho học sinh.

Ngoài ra, chương trình môn Toán ở từng cấp cũng dành thời lượng thích đáng để tiến hành các hoạt động thực hành và trải nghiệm cho học sinh chẳng hạn như: Tiến hành các đề tài, dự án học tập về Toán, đặc biệt là các đề tài và các dự án về ứng dụng toán học trong thực tiễn; tổ chức các trò chơi học toán, câu lạc bộ toán học, diễn đàn, hội thảo, cuộc thi về Toán; ra báo tường (hoặc nội san) về Toán; tham quan các cơ sở đào tạo và nghiên cứu toán học, giao lưu với học sinh có khả năng và yêu thích môn Toán,... Những hoạt động đó sẽ giúp học sinh vận dụng những tri thức, kiến thức, kĩ năng, thái độ đã được tích luỹ từ giáo dục toán học và những kinh nghiệm của bản thân vào thực tiễn cuộc sống một cách sáng tạo; phát triển cho học sinh năng lực tổ chức và quản lí hoạt động, năng lực tự nhận thức và tích cực hoá bản thân; giúp học sinh bước đầu xác định được năng lực, sở trường của bản thân nhằm định hướng và lựa chọn nghề nghiệp; tạo lập một số năng lực cơ bản cho người lao động tương lai và người công dân có trách nhiệm.

### b. Chuyên đề học tập

Trong mỗi lớp ở giai đoạn giáo dục định hướng nghề nghiệp, học sinh (đặc biệt là những học sinh có định hướng khoa học tự nhiên và công nghệ) được chọn học một số chuyên đề học tập. Các chuyên đề này nhằm:

- Cung cấp thêm một số kiến thức và kĩ năng toán học đáp ứng yêu cầu phân hoá sâu (ví dụ: phương pháp quy nạp toán học; hệ phương trình bậc nhất ba ẩn; biến ngẫu nhiên rời rạc và các số đặc trưng của biến ngẫu nhiên rời rạc; phép biến hình phẳng; vẽ kĩ thuật; một số yếu tố của lí thuyết đồ thị); tạo cơ hội cho học sinh vận dụng toán học giải quyết các vấn đề liên môn và thực tiễn, góp phần hình thành cơ sở khoa học cho giáo dục STEM (ví dụ: các kiến thức về hệ phương trình bậc nhất cho phép giải quyết một số bài toán vật lí về tính toán điện trở, tính cường độ dòng điện trong dòng điện không đổi,...; cân bằng phản ứng trong một số bài toán hoá học,...; một số bài toán sinh học về nguyên phân, giảm phân,...; kiến thức về đạo hàm để giải quyết một số bài toán tối ưu về khoảng cách, thời gian, kinh tế;...).
- Giúp học sinh hiểu sâu thêm vai trò và những ứng dụng của Toán học trong thực tiễn; có những hiểu biết về các ngành nghề gắn với môn Toán và giá trị của nó làm cơ sở cho định hướng nghề nghiệp sau trung học phổ thông.
- Tạo cơ hội cho học sinh nhận biết năng khiếu, sở thích, phát triển hứng thú và niềm tin trong học Toán; phát triển năng lực toán học và năng lực tìm hiểu những vấn đề có liên quan đến Toán học trong suốt cuộc đời.

## 2. Phân bố các mạch nội dung ở các lớp

Nội dung trình bày tường minh, kí hiệu bằng dấu "x".

<table>
    <thead>
        <tr>
            <th rowspan="2" style="text-align: center">Mạch</th>
            <th rowspan="2" style="text-align: center">Chủ đề</th>
            <th colspan="12" style="text-align: center">Lớp</th>
        </tr>
        <tr>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
            <th>5</th>
            <th>6</th>
            <th>7</th>
            <th>8</th>
            <th>9</th>
            <th>10</th>
            <th>11</th>
            <th>12</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td colspan="14">SỐ, ĐẠI SỐ VÀ MỘT SỐ YẾU TỐ GIẢI TÍCH</td>
        </tr>
        <tr>
            <td colspan="14"><strong><em>Số học</em></strong></td>
        </tr>
        <tr>
            <td colspan="2">Số tự nhiên</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Số nguyên</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td rowspan="3">Số hữu tỉ</td>
            <td>Phân số</td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Số thập phân</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Số hữu tỉ</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Số thực</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Ước lượng và làm tròn số</td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Tỉ số. Tỉ số phần trăm. Tỉ lệ thức và dãy tỉ số bằng nhau</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="14"><strong><em>Đại số</em></strong></td>
        </tr>
        <tr>
            <td colspan="2">Mệnh đề</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Tập hợp</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Biểu thức đại số</td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Hàm số và đồ thị</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
        </tr>
        <tr>
            <td colspan="2">Phương trình, hệ phương trình</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
        <tr>
            <td colspan="2">Bất phương trình, hệ bất phương trình</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Lượng giác</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Lũy thừa, mũ và lôgarit</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Dãy số, cấp số cộng, cấp số nhân</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Đại số tổ hợp</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="14"><strong><em>Một số yếu tố giải tích</em></strong></td>
        </tr>
        <tr>
            <td rowspan="3">
                Giới hạn. Hàm số liên tục
            </td>
            <td>Giới hạn của dãy số</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
        </tr>
        <tr>
            <td>Giới hạn của hàm số</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
        </tr>
        <tr>
            <td>Hàm số liên tục</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Đạo hàm</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
        </tr>
        <tr>
            <td colspan="2">Nguyên hàm, tích phân</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
        </tr>
        <tr>
            <td colspan="14">HÌNH HỌC VÀ ĐO LƯỜNG</td>
        </tr>
        <tr>
            <td colspan="14"><strong><em>Hình học trực quan</em></strong></td>
        </tr>
        <tr>
            <td colspan="2">Hình phẳng và hình khối trong thực tiễn</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="14"><strong><em>Hình học phẳng</em></strong></td>
        </tr>
        <tr>
            <td colspan="2">Các hình hình học cơ bản (điểm, đường thẳng, đoạn thẳng)</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Góc</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Tam giác</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Tứ giác</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Đa giác đều</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Hình tròn. Đường tròn</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Ba đường conic</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Hệ thức lượng trong tam giác</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">véc-tơ trong mặt phẳng</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">Phương pháp toạ độ trong mặt phẳng</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
        </tr>

        <tr>
            <td colspan="14"><strong><em>Hình học không gian</em></strong></td>
        </tr>
        <tr>
            <td colspan="2">Đường thẳng và mặt phẳng trong không gian</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
        </tr>        
        <tr>
            <td colspan="2">Quan hệ song song trong không gian. Phép chiếu song song</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
        </tr>        
        <tr>
            <td colspan="2">Quan hệ vuông góc trong không gian. Phép chiếu vuông góc</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
        </tr>        
        <tr>
            <td colspan="2">véc-tơ trong không gian</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
        </tr>        
        <tr>
            <td colspan="2">Phương pháp toạ độ trong không gian</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
        </tr> 

        <tr>
            <td colspan="14"><strong><em>Đo lường</em></strong></td>
        </tr>  
        <tr>
            <td colspan="2">Độ dài</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
        </tr>     
        <tr>
            <td colspan="2">Số đo góc</td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td>x</td>
            <td></td>
        </tr>     
        <tr>
            <td colspan="2">Diện tích</td>
            <td></td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
        </tr>     
        <tr>
            <td colspan="2">Dung tích. Thể tích</td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td>x</td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td>x</td>
            <td>x</td>
        </tr>     
        <tr>
            <td colspan="2">Khối lượng</td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>     
        <tr>
            <td colspan="2">Nhiệt độ</td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>     
        <tr>
            <td colspan="2">Thời gian</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>     
        <tr>
            <td colspan="2">Vận tốc</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>x</td>
            <td></td>
        </tr>     
        <tr>
            <td colspan="2">Tiền tệ</td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr> 

        <tr>
            <td colspan="14">THỐNG KÊ VÀ XÁC SUẤT</td>
        </tr>
        <tr>
            <td colspan="2">Một số yếu tố thống kê</td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
        </tr> 
        <tr>
            <td colspan="2">Một số yếu tố xác suất</td>
            <td></td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
        </tr> 

        <tr>
            <td colspan="2">HOẠT ĐỘNG THỰC HÀNH VÀ TRẢI NGHIỆM</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
            <td>x</td>
        </tr>         
    </tbody>
</table>

## 3. Nội dung cụ thể và yêu cầu cần đạt ở các lớp

### Lớp 10

<table>
    <thead>
        <tr>
            <th colspan="2">Nội dung</th>
            <th>Yêu cầu cần đạt</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td colspan="3">ĐẠI SỐ VÀ MỘT SỐ YẾU TỐ GIẢI TÍCH</td>
        </tr>

        <tr>
            <td colspan="3"><strong><em>Đại số</em></strong></td>
        </tr>
        <tr>
            <td rowspan="2">
                Tập hợp. Mệnh đề
            </td>
            <td>
                Mệnh đề toán học. Mệnh đề phủ định. Mệnh đề đảo. Mệnh đề tương đương. Điều kiện cần và đủ.
            </td>
            <td>
                <ul>
                    <li>Thiết lập và phát biểu được các mệnh đề toán học, bao gồm: mệnh đề phủ định; mệnh đề đảo; mệnh đề tương đương; mệnh đề có chứa kí hiệu $\forall$, $\exists$; điều kiện cần, điều kiện đủ, điều kiện cần và đủ.</li>
                    <li>Xác định được tính đúng/sai của một mệnh đề toán học trong những trường hợp đơn giản.</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                Tập hợp. Các phép toán trên tập hợp
            </td>
            <td>
                <ul>
                    <li>Nhận biết được các khái niệm cơ bản về tập hợp (tập con, hai tập hợp bằng nhau, tập rỗng) và biết sử dụng các kí hiệu $\subset$, $\supset$, $\emptyset$.</li>
                    <li>Thực hiện được phép toán trên các tập hợp (hợp, giao, hiệu của hai tập hợp, phần bù của một tập con) và biết dùng biểu đồ Ven để biểu diễn chúng trong những trường hợp cụ thể.</li>
                    <li>Giải quyết được một số vấn đề thực tiễn gắn với phép toán trên tập hợp (ví dụ: những bài toán liên quan đến đếm số phần tử của hợp các tập hợp,...).</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                Bất phương trình và hệ bất phương trình bậc nhất hai ẩn
            </td>
            <td>
                Bất phương trình, hệ bất phương trình bậc nhất hai ẩn và ứng dụng
            </td>
            <td>
                <ul>
                    <li>Nhận biết được bất phương trình và hệ bất phương trình bậc nhất hai ẩn.</li>
                    <li>Biểu diễn được miền nghiệm của bất phương trình và hệ bất phương trình bậc nhất hai ẩn trên mặt phẳng toạ độ.</li>
                    <li>Vận dụng được kiến thức về bất phương trình, hệ bất phương trình bậc nhất hai ẩn vào giải quyết bài toán thực tiễn (ví dụ: bài toán tìm cực trị của biểu thức $F = ax + by$ trên một miền đa giác,...).</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td rowspan="4">
                Hàm số và đồ thị
            </td>
            <td>
                Khái niệm cơ bản về hàm số và đồ thị
            </td>
            <td>
                <ul>
                    <li>Nhận biết được những mô hình thực tế (dạng bảng, biểu đồ, công thức) dẫn đến khái niệm hàm số.</li>
                    <li>Mô tả được các khái niệm cơ bản về hàm số: định nghĩa hàm số, tập xác định, tập giá trị, hàm số đồng biến, hàm số nghịch biến, đồ thị của hàm số.</li>
                    <li>Mô tả được các đặc trưng hình học của đồ thị hàm số đồng biến, hàm số nghịch biến.</li>
                    <li>Vận dụng được kiến thức của hàm số vào giải quyết bài toán thực tiễn (ví dụ: xây dựng hàm số bậc nhất trên những khoảng khác nhau để tính số tiền y (phải trả) theo số phút gọi x đối với một gói cước điện thoại,...).</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                Hàm số bậc hai, đồ thị hàm số bậc hai và ứng dụng
            </td>
            <td>
                <ul>
                    <li>Thiết lập được bảng giá trị của hàm số bậc hai.</li>
                    <li>Vẽ được Parabola (parabol) là đồ thị hàm số bậc hai.</li>
                    <li>Nhận biết được các tính chất cơ bản của Parabola như đỉnh, trục đối xứng.</li>
                    <li> Nhận biết và giải thích được các tính chất của hàm số bậc hai thông qua đồ thị.</li>
                    <li>Vận dụng được kiến thức về hàm số bậc hai và đồ thị vào giải quyết bài toán thực tiễn (ví dụ: xác định độ cao của cầu, cổng có hình dạng Parabola,...).</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                Dấu của tam thức bậc hai. Bất phương trình bậc hai một ẩn
            </td>
            <td>
                <ul>
                    <li>Giải thích được định lí về dấu của tam thức bậc hai từ việc quan sát đồ thị của hàm bậc hai.</li>
                    <li>Giải được bất phương trình bậc hai.</li>
                    <li>Vận dụng được bất phương trình bậc hai một ẩn vào giải quyết bài toán thực tiễn (ví dụ: xác định chiều cao tối đa để xe có thể qua hầm có hình dạng Parabola,...).</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                Phương trình quy về phương trình bậc hai
            </td>
            <td>
                <ul>
                    <li>Giải được phương trình chứa căn thức có dạng:
                        $$
                            \sqrt{ax^2+bx+c}=\sqrt{dx^2+ex+f};
                        $$
                        $$
                            \sqrt{ax^2+bx+c}=dx+e.
                        $$
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td rowspan="2">
                Đại số tổ hợp
            </td>
            <td>
                Các quy tắc đếm (quy tắc cộng, quy tắc nhân, chỉnh hợp, hoán vị, tổ hợp) và ứng dụng trong thực tiễn
            </td>
            <td>
                <ul>
                    <li>Vận dụng được quy tắc cộng và quy tắc nhân trong một số tình huống đơn giản (ví dụ: đếm số khả năng xuất hiện mặt sấp/ngửa khi tung một số đồng xu,...).</li>
                    <li>Vận dụng được sơ đồ hình cây trong các bài toán đếm đơn giản các đối tượng trong Toán học, trong các môn học khác cũng như trong thực tiễn (ví dụ: đếm số hợp tử tạo thành trong Sinh học, hoặc đếm số trận đấu trong một giải thể thao,...).</li>
                    <li>Tính được số các hoán vị, chỉnh hợp, tổ hợp.</li>
                    <li>Tính được số các hoán vị, chỉnh hợp, tổ hợp bằng máy tính cầm tay.</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Nhị thức Newton với số mũ không quá 5
            </td>
            <td>
                Khai triển được nhị thức Newton $(a+b)^n$ với số mũ thấp ($n=4$ hoặc $n=5$) bằng cách vận dụng tổ hợp.
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <strong><em>Thực hành trong phòng máy tính với phần mềm toán học (nếu nhà trường có điều kiện thực hiện)</em></strong>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <ul>
                    <li>Sử dụng phần mềm để hỗ trợ việc học các kiến thức đại số.</li>
                    <li>Thực hành sử dụng phần mềm để vẽ đồ thị của hàm số bậc hai; sử dụng đồ thị để tạo các hình ảnh hoa văn, hình khối.</li>
                </ul>            
            </td>
        </tr>

        <tr>
            <td colspan="3">HÌNH HỌC VÀ ĐO LƯỜNG</td>
        </tr>

        <tr>
            <td colspan="3"><strong><em>Hình học phẳng</em></strong></td>
        </tr>

        <tr>
            <td rowspan="2">
                Hệ thức lượng trong tam giác. véc-tơ         
            </td>
            <td> 
                Hệ thức lượng trong tam giác. Định lí cô-sin. Định lí sin. Công thức tính diện tích tam giác. Giải tam giác           
            </td>
            <td>  
                <ul>
                    <li>Nhận biết được giá trị lượng giác của một góc từ $0\degree$ đến $180\degree$.</li>
                    <li>Tính được giá trị lượng giác (đúng hoặc gần đúng) của một góc từ $0\degree$ đến $180\degree$ bằng máy tính cầm tay.</li>
                    <li>Giải thích được hệ thức liên hệ giữa giá trị lượng giác của các góc phụ nhau, bù nhau.</li>
                    <li>Giải thích được các hệ thức lượng cơ bản trong tam giác: định lí côsin, định lí sin, công thức tính diện tích tam giác.</li>
                    <li>Mô tả được cách giải tam giác và vận dụng được vào việc giải một số bài toán có nội dung thực tiễn (ví dụ: xác định khoảng cách giữa hai địa điểm khi gặp vật cản, xác định chiều cao của vật khi không thể đo trực tiếp,...).</li>
                </ul>          
            </td>
        </tr>

        <tr>
            <td>
                Véc-tơ, các phép toán (tổng và hiệu hai véc-tơ, tích của một số với véc-tơ, tích vô hướng của hai véc-tơ) và một số ứng dụng trong Vật lí       
            </td>
            <td>  
                <ul>
                    <li>Nhận biết được khái niệm véc-tơ, véc-tơ bằng nhau, véc-tơ-không.</li>
                    <li>Biểu thị được một số đại lượng trong thực tiễn bằng véc-tơ.</li>
                    <li>Thực hiện được các phép toán trên véc-tơ (tổng và hiệu hai véc-tơ, tích của một số với véc-tơ, tích vô hướng của hai véc-tơ) và mô tả được những tính chất hình học (ba điểm thẳng hàng, trung điểm của đoạn thẳng, trọng tâm của tam giác,...) bằng véc-tơ.</li>
                    <li>Sử dụng được véc-tơ và các phép toán trên véc-tơ để giải thích một số hiện tượng có liên quan đến Vật lí và Hoá học (ví dụ: những vấn đề liên quan đến lực, đến chuyển động,...).</li>
                    <li>Vận dụng được kiến thức về véc-tơ để giải một số bài toán hình học và một số bài toán liên quan đến thực tiễn (ví dụ: xác định lực tác dụng lên vật,...).</li>
                </ul>          
            </td>
        </tr>

        <tr>
            <td rowspan="4">
                  Phương pháp toạ độ trong mặt phẳng      
            </td>
            <td>
                Toạ độ của véc-tơ đối với một hệ trục toạ độ. Biểu thức toạ độ của các phép toán véc-tơ. Ứng dụng vào bài toán giải tam giác            
            </td>
            <td>  
                <ul>
                    <li>Nhận biết được toạ độ của véc-tơ đối với một hệ trục toạ độ.</li>
                    <li>Tìm được toạ độ của một véc-tơ, độ dài của một véc-tơ khi biết toạ độ hai đầu mút của nó.</li>
                    <li>Sử dụng được biểu thức toạ độ của các phép toán véc-tơ trong tính toán.</li>
                    <li>Vận dụng được phương pháp toạ độ vào bài toán giải tam giác.</li>
                    <li>Vận dụng được kiến thức về toạ độ của véc-tơ để giải một số bài toán liên quan đến thực tiễn (ví dụ: vị trí của vật trên mặt phẳng toạ độ,...).</li>
                </ul>          
            </td>
        </tr>
        <tr>
            <td>
                Đường thẳng trong mặt phẳng toạ độ. Phương trình tổng quát và phương trình tham số của đường thẳng. Khoảng cách từ một điểm đến một đường thẳng        
            </td>
            <td>  
                <ul>
                    <li>Mô tả được phương trình tổng quát và phương trình tham số của đường thẳng trong mặt phẳng toạ độ.</li>
                    <li>Thiết lập được phương trình của đường thẳng trong mặt phẳng khi biết: một điểm và một véc-tơ pháp tuyến; biết một điểm và một véc-tơ chỉ phương; biết hai điểm.</li>
                    <li>Nhận biết được hai đường thẳng cắt nhau, song song, trùng nhau, vuông góc với nhau bằng phương pháp toạ độ.</li>
                    <li>Thiết lập được công thức tính góc giữa hai đường thẳng.</li>
                    <li>Tính được khoảng cách từ một điểm đến một đường thẳng bằng phương pháp toạ độ.</li>
                    <li>Giải thích được mối liên hệ giữa đồ thị hàm số bậc nhất và đường thẳng trong mặt phẳng toạ độ.</li>
                    <li>Vận dụng được kiến thức về phương trình đường thẳng để giải một số bài toán có liên quan đến thực tiễn.</li>
                </ul>          
            </td>
        </tr>
        <tr>
            <td>
                 Đường tròn trong mặt phẳng toạ độ và ứng dụng       
            </td>
            <td>  
                <ul>
                    <li>Thiết lập được phương trình đường tròn khi biết toạ độ tâm và bán kính; biết toạ độ ba điểm mà đường tròn đi qua; xác định được tâm và bán kính đường tròn khi biết phương trình của đường tròn.</li>
                    <li>Thiết lập được phương trình tiếp tuyến của đường tròn khi biết toạ độ của tiếp điểm.</li>
                    <li>Vận dụng được kiến thức về phương trình đường tròn để giải một số bài toán liên quan đến thực tiễn (ví dụ: bài toán về chuyển động tròn trong Vật lí,...).</li>
                </ul>          
            </td>
        </tr>

        <tr>
            <td>
                Ba đường conic trong mặt phẳng toạ độ và ứng dụng
            </td>
            <td>  
                <ul>
                    <li>Nhận biết được ba đường conic bằng hình học.</li>
                    <li>Nhận biết được phương trình chính tắc của ba đường conic trong mặt phẳng toạ độ.</li>
                    <li>Giải quyết được một số vấn đề thực tiễn gắn với ba đường conic (ví dụ: giải thích một số hiện tượng trong Quang học,...).</li>
                </ul>          
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <strong><em>Thực hành trong phòng máy tính với phần mềm toán học (nếu nhà trường có điều kiện thực hiện)</em></strong>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <ul>
                    <li>Sử dụng phần mềm để hỗ trợ việc học các kiến thức hình học.</li>
                    <li>Thực hành sử dụng phần mềm để biểu thị điểm, véc-tơ, các phép toán véc-tơ trong hệ trục toạ độ $Oxy$.</li>
                    <li>Thực hành sử dụng phần mềm để vẽ đường thẳng, đường tròn, các đường conic trên mặt phẳng toạ độ; xem xét sự thay đổi hình dạng của các hình khi thay đổi các yếu tố trong phương trình xác định chúng.</li>
                    <li>Thực hành sử dụng phần mềm để thiết kế đồ hoạ liên quan đến đường tròn và các đường conic.</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td colspan="3">THỐNG KÊ VÀ XÁC SUẤT</td>
        </tr>

        <tr>
            <td colspan="3"><strong><em>Thống kê</em></strong></td>
        </tr>

        <tr>
            <td>
                Số gần đúng
            </td>
            <td>
                Số gần đúng. Sai số
            </td>
            <td>
                <ul>
                    <li>Hiểu được khái niệm số gần đúng, sai số tuyệt đối.</li>
                    <li>Xác định được số gần đúng của một số với độ chính xác cho trước.</li>
                    <li>Xác định được sai số tương đối của số gần đúng.</li>
                    <li>Xác định được số quy tròn của số gần đúng với độ chính xác cho trước.</li>
                    <li>Biết sử dụng máy tính cầm tay để tính toán với các số gần đúng.</li>
                </ul>
            </td>
        </tr>
        
        <tr>
            <td>
                Thu thập và tổ chức dữ liệu
            </td>
            <td>
                Mô tả và biểu diễn dữ liệu trên các bảng, biểu đồ
            </td>
            <td>
                Phát hiện và lí giải được số liệu không chính xác dựa trên mối liên hệ toán học đơn giản giữa các số liệu đã được biểu diễn trong nhiều ví dụ.
            </td>
        </tr>
        
        <tr>
            <td rowspan="2">
                Phân tích và xử lí dữ liệu
            </td>
            <td>
                Các số đặc trưng đo xu thế trung tâm cho mẫu số liệu không ghép nhóm
            </td>
            <td>
                <ul>
                    <li>Tính được số đặc trưng đo xu thế trung tâm cho mẫu số liệu không ghép nhóm: số trung bình cộng (hay số trung bình), trung vị (median), tứ phân vị (quartiles), mốt (mode).</li>
                    <li>Giải thích được ý nghĩa và vai trò của các số đặc trưng nói trên của mẫu số liệu trong thực tiễn.</li>
                    <li>Chỉ ra được những kết luận nhờ ý nghĩa của số đặc trưng nói trên của mẫu số liệu trong trường hợp đơn giản.</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Các số đặc trưng đo mức độ phân tán cho mẫu số liệu không ghép nhóm
            </td>
            <td>
                <ul>
                    <li>Tính được số đặc trưng đo mức độ phân tán cho mẫu số liệu không ghép nhóm: khoảng biến thiên, khoảng tứ phân vị, phương sai, độ lệch chuẩn.</li>
                    <li>Giải thích được ý nghĩa và vai trò của các số đặc trưng nói trên của mẫu số liệu trong thực tiễn.</li>
                    <li>Chỉ ra được những kết luận nhờ ý nghĩa của số đặc trưng nói trên của mẫu số liệu trong trường hợp đơn giản.</li>
                    <li>Nhận biết được mối liên hệ giữa thống kê với những kiến thức của các môn học trong Chương trình lớp 10 và trong thực tiễn.</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td colspan="3"><strong><em>Xác suất</em></strong></td>
        </tr>

        <tr>
            <td >
                Khái niệm về xác suất
            </td>
            <td>
                Một số khái niệm về xác suất cổ điển
            </td>
            <td>
                <ul>
                    <li>Nhận biết được một số khái niệm về xác suất cổ điển: phép thử ngẫu nhiên; không gian mẫu; biến cố (biến cố là tập con của không gian mẫu); biến cố đối; định nghĩa cổ điển của xác suất; nguyên lí xác suất bé.</li>
                    <li>Mô tả được không gian mẫu, biến cố trong một số thí nghiệm đơn giản (ví dụ: tung đồng xu hai lần, tung đồng xu ba lần, tung xúc xắc hai lần).</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td rowspan="2">
                Các quy tắc tính xác suất
            </td>
            <td>
                Thực hành tính toán xác suất trong những trường hợp đơn giản
            </td>
            <td>
                <ul>
                    <li>Tính được xác suất của biến cố trong một số bài toán đơn giản bằng phương pháp tổ hợp (trường hợp xác suất phân bố đều).</li>
                    <li>Tính được xác suất trong một số thí nghiệm lặp bằng cách sử dụng sơ đồ hình cây (ví dụ: tung xúc xắc hai lần, tính xác suất để tổng số chấm xuất hiện trong hai lần tung bằng 7).</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                Các quy tắc tính xác suất
            </td>
            <td>
                <ul>
                    <li>Mô tả được các tính chất cơ bản của xác suất.</li>
                    <li>Tính được xác suất của biến cố đối.</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td colspan="3"><strong><em>Thực hành trong phòng máy tính với phần mềm toán học (nếu nhà trường có điều kiện thực hiện)</em></strong></td>
        </tr>

        <tr>
            <td colspan="3">
                <ul>
                    <li>Sử dụng phần mềm để hỗ trợ việc học các kiến thức thống kê và xác suất.</li>
                    <li>Thực hành sử dụng phần mềm để tính được số đặc trưng đo xu thế trung tâm và đo mức độ phân tán cho mẫu số liệu không ghép nhóm.</li>
                    <li>Thực hành sử dụng phần mềm để tính xác suất theo định nghĩa cổ điển.</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td colspan="3">HOẠT ĐỘNG THỰC HÀNH VÀ TRẢI NGHIỆM</td>
        </tr>

        <tr>
           <td colspan="3">
                Nhà trường tổ chức cho học sinh một số hoạt động sau và có thể bổ sung các hoạt động khác tuỳ vào điều kiện cụ thể. <br>
                <em>Hoạt động 1:</em> Thực hành ứng dụng các kiến thức toán học vào thực tiễn và các chủ đề liên môn, chẳng hạn:
                <ul>
                    <li>Thực hành tổng hợp các hoạt động liên quan đến tính toán, đo lường, ước lượng và tạo lập hình, như: tính tiền khi đi taxi theo các khung giá: dưới 1km, từ 1 - 10km, từ 10 - 31km, trên 31km,...; đo đạc một vài yếu tố của vật thể mà chúng ta không thể dùng dụng cụ đo đạc để đo trực tiếp; tính chiều cao của công trình kiến trúc dạng Parabola (như cầu Nhật Tân, cầu Trường Tiền, cầu Mỹ Thuận,...); giải thích các hiện tượng, quy luật trong Vật lí; thực hành vẽ, cắt hình có dạng Ellipse (elip).</li>
                    <li>Thực hành mô tả và biểu diễn dữ liệu trên các bảng, biểu đồ.</li>
                </ul>

                <em>Hoạt động 2:</em> Tìm hiểu một số kiến thức về tài chính, như:
                <ul>
                    <li>Hiểu sự khác biệt giữa tiết kiệm và đầu tư.</li>
                    <li>Thực hành thiết lập kế hoạch đầu tư cá nhân để đạt được tỉ lệ tăng trưởng như mong đợi.</li>
                </ul>

                <em>Hoạt động 3:</em> Tổ chức các hoạt động ngoài giờ chính khoá như các câu lạc bộ toán học, dự án học tập, trò chơi học toán, cuộc thi về Toán, chẳng hạn: thi tìm hiểu lịch sử toán học, tổ chức sinh hoạt câu lạc bộ toán học theo các chủ đề (tìm hiểu các ứng dụng của hàm số bậc hai, véc-tơ trong thực tiễn,...).<br>

                <em>Hoạt động 4 (nếu nhà trường có điều kiện thực hiện):</em> Tổ chức giao lưu học sinh giỏi trong trường và trường bạn, với các chuyên gia nhằm hiểu nhiều hơn về vai trò của Toán học trong thực tiễn và trong các ngành nghề.
            </td> 
        </tr>
    </tbody>
</table>

#### Nội dung Chuyên đề lớp 10: Ứng dụng Toán học vào giải quyết vấn đề liên môn và thực tiễn.

- Chuyên đề 10.1: Phương pháp quy nạp toán học. Nhị thức Newton.
- Chuyên đề 10.2: Hệ phương trình bậc nhất ba ẩn.
- Chuyên đề 10.3: Ba đường conic và ứng dụng.

<table>
    <thead>
        <tr>
            <th>Chuyên đề</th>
            <th>Chủ đề</th>
            <th>Yêu cầu cần đạt</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td rowspan="2">
                Chuyên đề 10.1: <strong><em>Phương pháp quy nạp toán học. Nhị thức Newton</strong></em>
            </td>
            <td>
                Phương pháp quy nạp toán học
            </td>
            <td>
                <ul>
                    <li>Mô tả được các bước chứng minh tính đúng đắn của một mệnh đề toán học bằng phương pháp quy nạp.</li>
                    <li>Chứng minh được tính đúng đắn của một mệnh đề toán học bằng phương pháp quy nạp toán học.</li>
                    <li>Vận dụng được phương pháp quy nạp toán học để giải quyết một số vấn đề thực tiễn.</li>
                <ul>
            </td>
        </tr>
        <tr>
            <td>
                Nhị thức Newton
            </td>
            <td>
                <ul>
                    <li>Khai triển được nhị thức Newton $(a + b)^n$ bằng cách vận dụng tổ hợp.</li>
                    <li>Xác định được các hệ số trong nhị thức Newton thông qua tam giác Pascal.</li>
                    <li>Xác định được hệ số của xk trong khai triển $(ax + b)^n$ thành đa thức.</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td rowspan="2">
                Chuyên đề 10.2: <strong><em>Hệ phương trình bậc nhất ba ẩn</strong></em>
            </td>
            <td>
                Hệ phương trình bậc nhất ba ẩn
            </td>
            <td>
                <ul>
                    <li>Nhận biết được khái niệm nghiệm của hệ phương trình bậc nhất ba ẩn.</li>
                    <li>Giải được hệ phương trình bậc nhất ba ẩn bằng phương pháp Gauss.</li>
                    <li>Tìm được nghiệm hệ phương trình bậc nhất ba ẩn bằng máy tính cầm tay.</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Vận dụng hệ phương trình bậc nhất ba ẩn để giải một số bài toán liên môn và thực tiễn
            </td>
            <td>
                <ul>
                    <li>Vận dụng được cách giải hệ phương trình bậc nhất ba ẩn vào giải quyết một số bài toán Vật lí (tính điện trở, tính cường độ dòng điện trong dòng điện không đổi,...), Hoá học (cân bằng phản ứng,...), Sinh học (bài tập nguyên phân, giảm phân,...).</li>
                    <li>Vận dụng cách giải hệ phương trình bậc nhất ba ẩn để giải quyết một số vấn đề thực tiễn cuộc sống (ví dụ: bài toán lập kế hoạch sản xuất, mô hình cân bằng thị trường, phân bố vốn đầu tư,...).</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td rowspan="2">
                Chuyên đề 10.3: <strong><em>Ba đường conic và ứng dụng</strong></em>
            </td>
            <td>
                Ba đường conic và ứng dụng
            </td>
            <td>
                <ul>
                    <li>Xác định được các yếu tố đặc trưng của đường conic (đỉnh, tiêu điểm, tiêu cự, độ dài trục, tâm sai, đường chuẩn, bán kính qua tiêu) khi biết phương trình chính tắc của đường conic đó.</li>
                    <li>Nhận biết được đường conic như là giao của mặt phẳng với mặt nón.</li>
                    <li>Giải quyết được một số vấn đề thực tiễn gắn với ba đường conic (ví dụ: giải thích một số hiện tượng trong Quang học, xác định quỹ đạo chuyển động của các hành tinh trong hệ Mặt Trời,...).</li>
                </ul>
            </td>
        </tr>

    </tbody>
</table>

### Lớp 11

<table>
    <thead>
        <tr>
            <th colspan="2">Nội dung</th>
            <th>Yêu cầu cần đạt</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td colspan="3">ĐẠI SỐ VÀ MỘT SỐ YẾU TỐ GIẢI TÍCH</td>
        </tr>

        <tr>
            <td colspan="3"><strong><em>Đại số</em></strong></td>
        </tr>
        <tr>
            <td rowspan="3">
                Hàm số lượng giác và phương trình lượng giác
            </td>
            <td>
                Góc lượng giác. Số đo của góc lượng giác. Đường tròn lượng giác. Giá trị lượng giác của góc lượng giác, quan hệ giữa các giá trị lượng giác. Các phép biến đổi lượng giác (công thức cộng; công thức nhân đôi; công thức biến đổi tích thành tổng; công thức biến đổi tổng thành tích)
            </td>
            <td>
                <ul>
                    <li>Nhận biết được các khái niệm cơ bản về góc lượng giác: khái niệm góc lượng giác; số đo của góc lượng giác; hệ thức Chasles cho các góc lượng giác; đường tròn lượng giác.</li>
                    <li>Nhận biết được khái niệm giá trị lượng giác của một góc lượng giác.</li>
                    <li>Mô tả được bảng giá trị lượng giác của một số góc lượng giác thường gặp; hệ thức cơ bản giữa các giá trị lượng giác của một góc lượng giác; quan hệ giữa các giá trị lượng giác của các góc lượng giác có liên quan đặc biệt: bù nhau, phụ nhau, đối nhau, hơn kém nhau $\pi$.</li>
                    <li>Sử dụng được máy tính cầm tay để tính giá trị lượng giác của một góc lượng giác khi biết số đo của góc đó.</li>
                    <li>Mô tả được các phép biến đổi lượng giác cơ bản: công thức cộng; công thức góc nhân đôi; công thức biến đổi tích thành tổng và công thức biến đổi tổng thành tích.</li>
                    <li>Giải quyết được một số vấn đề thực tiễn gắn với giá trị lượng giác của góc lượng giác và các phép biến đổi lượng giác.</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                Hàm số lượng giác và đồ thị
            </td>
            <td>
                <ul>
                    <li>Nhận biết được được các khái niệm về hàm số chẵn, hàm số lẻ, hàm số tuần hoàn.</li>
                    <li>Nhận biết được các đặc trưng hình học của đồ thị hàm số chẵn, hàm số lẻ, hàm số tuần hoàn.</li>
                    <li>Nhận biết được được định nghĩa các hàm lượng giác $y=\sin x$, $y=\cos x$, $y=\tan x$, $y=\cot x$ thông qua đường tròn lượng giác.</li>
                    <li>Giải thích được: tập xác định; tập giá trị; tính chất chẵn, lẻ; tính tuần hoàn; chu kì; khoảng đồng biến, nghịch biến của các hàm số $y=\sin x$, $y=\cos x$, $y=\tan x$, $y=\cot x$ dựa vào đồ thị.</li>
                    <li>Giải quyết được một số vấn đề thực tiễn gắn với hàm số lượng giác (ví dụ: một số bài toán có liên quan đến dao động điều hoà trong Vật lí,...).</li>
                </ul>
            </td>
        <tr>
            <td>
                Phương trình lượng giác cơ bản
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được công thức nghiệm của phương trình lượng giác cơ bản: $\sin x=m$; $\cos x=m$; $\tan x=m$; $\cot x=m$ bằng cách vận dụng đồ thị hàm số lượng giác tương ứng.
                    </li>
                    <li>
                        Tính được nghiệm gần đúng của phương trình lượng giác cơ bản bằng máy tính cầm tay.
                    </li>
                    <li>
                        Giải được phương trình lượng giác ở dạng vận dụng trực tiếp phương trình lượng giác cơ bản (ví dụ: giải phương trình lượng giác dạng $\sin 2x=\sin 3x$, $\sin x=\cos 3x$).
                    </li>
                    <li>
                        Giải quyết được một số vấn đề thực tiễn gắn với phương trình lượng giác (ví dụ: một số bài toán liên quan đến dao động điều hòa trong Vật lí,...).
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td rowspan="3">
                Dãy số. Cấp số cộng. Cấp số nhân
            </td>
            <td>
                Dãy số. Dãy số tăng, dãy số giảm
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được dãy số hữu hạn, dãy số vô hạn.
                    </li>
                    <li>
                        Thể hiện được cách cho dãy số bằng liệt kê các số hạng; bằng công thức tổng quát; bằng hệ thức truy hồi; bằng cách mô tả.
                    </li>
                    <li>
                        Nhận biết được tính chất tăng, giảm, bị chặn của dãy số trong những trường hợp đơn giản.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Cấp số cộng. Số hạng tổng quát của cấp số cộng. Tổng của n số hạng đầu tiên của cấp số cộng
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được một dãy số là cấp số cộng.
                    </li>
                    <li>
                        Giải thích được công thức xác định số hạng tổng quát của cấp số cộng.
                    </li>
                    <li>
                        Tính được tổng của n số hạng đầu tiên của cấp số cộng.
                    </li>
                    <li>
                        Giải quyết được một số vấn đề thực tiễn gắn với cấp số cộng để giải một số bài toán liên quan đến thực tiễn (ví dụ: một số vấn đề trong Sinh học, trong Giáo dục dân số,...).
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Cấp số nhân. Số hạng tổng quát của cấp số nhân. Tổng của $n$ số hạng đầu tiên của cấp số nhân
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được một dãy số là cấp số nhân.
                    </li>
                    <li>
                        Giải thích được công thức xác định số hạng tổng quát của cấp số nhân.
                    </li>
                    <li>
                        Tính được tổng của n số hạng đầu tiên của cấp số nhân.
                    </li>
                    <li>
                        Giải quyết được một số vấn đề thực tiễn gắn với cấp số nhân để giải một số bài toán liên quan đến thực tiễn (ví dụ: một số vấn đề trong Sinh học,trong Giáo dục dân số,...).
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <strong><em>Một số yếu tố giải tích</em></strong>
            </td>
        </tr>

        <tr>
            <td rowspan="3">
                Giới hạn. Hàm số liên tục
            </td>
            <td>
                1.1. Giới hạn của dãy số. Phép toán giới hạn dãy số. Tổng của một cấp số nhân lùi vô hạn
            </td>
            <td>
                <ul>
                    <li>
                       Nhận biết được khái niệm giới hạn của dãy số. 
                    </li>
                    <li>
                        Giải thích được một số giới hạn cơ bản như: $\lim_{n\to+\infty} \frac{1}{n^k}=0\, (k\in\mathbb{N}^*)$; $\lim_{n\to+\infty} q^n=0\, (\lvert q\rvert<1)$; $\lim_{n\to+\infty}c=c$ với $c$ là hằng số.
                    </li>
                    <li>
                       Vận dụng được các phép toán giới hạn dãy số để tìm giới hạn của một số dãy số đơn giản. Ví dụ: $\lim_{n\to+\infty}\frac{2n+1}{n}$; \lim_{n\to+\infty}\frac{\sqrt{4n^2+1}}{n}.
                    </li>
                    <li>
                        Tính được tổng của một cấp số nhân lùi vô hạn và vận dụng được kết quả đó để giải quyết một số tình huống thực tiễn giả định hoặc liên quan đến thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                1.2. Giới hạn của hàm số. Phép toán giới hạn hàm số
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được khái niệm giới hạn hữu hạn của hàm số, giới hạn hữu hạn một phía của hàm số tại một điểm.
                    </li>
                    <li>
                        Nhận biết được khái niệm giới hạn hữu hạn của hàm số tại vô cực và mô tả được một số giới hạn cơ bản như: $\lim_{x\to+\infty}\frac{c}{x^k}=0$, $\lim_{x\to-\infty}\frac{c}{x^k}=0$ với $c$ là hằng số và $k$ là số nguyên dương.
                    </li>
                    <li>
                        Nhận biết được khái niệm giới hạn vô cực (một phía) của hàm số tại một điểm và hiểu được một số giới hạn cơ bản như: $\lim_{x\to a^+}\frac{1}{x-a}=+\infty$, $\lim_{x\to a^-}\frac{1}{x-a}=-\infty$.
                    </li>
                    <li>
                        Tính được một số giới hạn hàm số bằng cách vận dụng các phép toán trên giới hạn hàm số.
                    </li>
                    <li>
                        Giải quyết được một số vấn đề thực tiễn gắn với giới hạn hàm số.
                    </li>
                </ul>
            </td>
        </tr>
        
        <tr>
            <td>
                1.3. Hàm số liên tục
            </td>
            <td>
                <ul>
                    <li>
                        Nhận dạng được hàm số liên tục tại một điểm, hoặc trên một khoảng, hoặc trên một đoạn.
                    </li>
                    <li>
                        Nhận dạng được tính liên tục của tổng, hiệu, tích, thương của hai hàm số liên tục.
                    </li>
                    <li>
                        Nhận biết được tính liên tục của một số hàm sơ cấp cơ bản (như hàm đa thức, hàm phân thức, hàm căn thức, hàm lượng giác) trên tập xác định của chúng.
                    </li>
                </ul>
            </td>
        </tr>
        
        <tr>
            <td rowspan="4">
                Hàm số mũ và hàm số lôgarit
            </td>
            <td>
                Phép tính luỹ thừa với số mũ nguyên, số mũ hữu tỉ, số mũ thực. Các tính chất
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được khái niệm luỹ thừa với số mũ nguyên của một số thực khác $0$; luỹ thừa với số mũ hữu tỉ và luỹ thừa với số mũ thực của một số thực dương.
                    </li>
                    <li>
                        Giải thích được các tính chất của phép tính luỹ thừa với số mũ nguyên, luỹ thừa với số mũ hữu tỉ và luỹ thừa với số mũ thực.
                    </li>
                    <li>
                        Sử dụng được tính chất của phép tính luỹ thừa trong tính toán các biểu thức số và rút gọn các biểu thức chứa biến (tính viết và tính nhẩm, tính nhanh một cách hợp lí).
                    </li>
                    <li>
                        Tính được giá trị biểu thức số có chứa phép tính luỹ thừa bằng sử dụng máy tính cầm tay.
                    </li>
                    <li>
                        Giải quyết được một số vấn đề có liên quan đến môn học khác hoặc có liên quan đến thực tiễn gắn với phép tính luỹ thừa (ví dụ: bài toán về lãi suất, sự tăng trưởng,...).
                    </li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                Phép tính lôgarit (logarithm). Các tính chất
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được khái niệm lôgarit cơ số $a$ ($a>0, a\ne 1$) của một số thực dương.
                    </li>
                    <li>
                        Giải thích được các tính chất của phép tính lôgarit nhờ sử dụng định nghĩa hoặc các tính chất đã biết trước đó.
                    </li>
                    <li>
                        Sử dụng được tính chất của phép tính lôgarit trong tính toán các biểu thức số và rút gọn các biểu thức chứa biến (tính viết và tính nhẩm, tính nhanh một cách hợp lí).
                    </li>
                    <li>
                        Tính được giá trị (đúng hoặc gần đúng) của lôgarit bằng cách sử dụng máy tính cầm tay.                        
                    </li>
                    <li>
                        Giải quyết được một số vấn đề có liên quan đến môn học khác hoặc có liên quan đến thực tiễn gắn với phép tính lôgarit (ví dụ: bài toán liên quan đến độ pH trong Hoá học,...).

                    </li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                Hàm số mũ và hàm số lôgarit
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được hàm số mũ và hàm số lôgarit. Nêu được một số ví dụ thực tế về hàm số mũ, hàm số lôgarit.
                    </li>
                    <li>
                        Nhận dạng được đồ thị của các hàm số mũ, hàm số lôgarit.
                    </li>
                    <li>
                        Giải thích được các tính chất của hàm số mũ, hàm số lôgarit thông qua đồ thị của chúng.
                    </li>
                    <li>
                        Giải quyết được một số vấn đề có liên quan đến môn học khác hoặc có liên quan đến thực tiễn gắn với hàm số mũ và hàm số lôgarit (ví dụ: lãi suất, sự tăng trưởng,...).
                    </li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                Phương trình, bất phương trình mũ và lôgarit
            </td>
            <td>
                <ul>
                    <li>
                        Giải được phương trình, bất phương trình mũ, lôgarit ở dạng đơn giản. Ví dụ: $2^{x+1}=\frac{1}{4}$, $2^{x+1}=2^{3x+5}$, $\log_2(x+1)=3$, $\log_3(x+1)=\log_3\left(x^2-1\right)$.
                    </li>
                    <li>
                        Giải quyết được một số vấn đề có liên quan đến môn học khác hoặc có liên quan đến thực tiễn gắn với phương trình, bất phương trình mũ và lôgarit (ví dụ: bài toán liên quan đến độ pH, độ rung chấn,...).
                    </li>
                </ul>
            </td>
        </tr>

        
        <tr>
            <td rowspan="3">
                Đạo hàm
            </td>
            <td>
                Khái niệm đạo hàm. Ý nghĩa hình học của đạo hàm       
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được một số bài toán dẫn đến khái niệm đạo hàm như: xác định vận tốc tức thời của một vật chuyển động không đều, xác định tốc độ thay đổi của nhiệt độ.
                    </li>
                    <li>
                        Nhận biết được định nghĩa đạo hàm. Tính được đạo hàm của một số hàm đơn giản bằng định nghĩa.
                    </li>
                    <li>
                        Nhận biết được ý nghĩa hình học của đạo hàm.
                    </li>
                    <li>
                        Thiết lập được phương trình tiếp tuyến của đồ thị hàm số tại một điểm thuộc đồ thị.

                    </li>
                    <li>
                        Nhận biết được số e thông qua bài toán mô hình hoá lãi suất ngân hàng.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Các quy tắc tính đạo hàm             
            </td>
            <td>
                <ul>
                    <li>
                        Tính được đạo hàm của một số hàm số sơ cấp cơ bản (như hàm đa thức, hàm căn thức đơn giản, hàm số lượng giác, hàm số mũ, hàm số lôgarit).
                    </li>
                    <li>
                        Sử dụng được các công thức tính đạo hàm của tổng, hiệu, tích, thương của các hàm số và đạo hàm của hàm hợp.
                    </li>
                    <li>
                        Giải quyết được một số vấn đề có liên quan đến môn học khác hoặc có liên quan đến thực tiễn gắn với đạo hàm (ví dụ: xác định vận tốc tức thời của một vật chuyển động không đều,...).
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Đạo hàm cấp hai             
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được khái niệm đạo hàm cấp hai của một hàm số.
                    </li>
                    <li>
                        Tính được đạo hàm cấp hai của một số hàm số đơn giản.
                    </li>
                    <li>
                        Giải quyết được một số vấn đề có liên quan đến môn học khác hoặc có liên quan đến thực tiễn gắn với đạo hàm cấp hai (ví dụ: xác định gia tốc từ đồ thị vận tốc theo thời gian của một chuyển động không đều,...).
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <strong><em>Thực hành trong phòng máy tính với phần mềm toán học (nếu nhà trường có điều kiện thực hiện)</em></strong>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <ul>
                    <li>Sử dụng phần mềm để hỗ trợ việc học các kiến thức đại số và giải tích.</li>
                    <li>Thực hành sử dụng phần mềm để vẽ đồ thị hàm số lượng giác và sử dụng đồ thị để tạo các hoa văn, hình khối.</li>
                    <li>Thực hành sử dụng phần mềm để tạo mô hình thao tác động mô tả giới hạn, mô tả hàm số liên tục.</li>
                    <li>Thực hành sử dụng phần mềm để vẽ đồ thị hàm số luỹ thừa, hàm số mũ, hàm số lôgarit và tìm hiểu đặc điểm của chúng.</li>
                    <li>Thực hành sử dụng phần mềm để tạo mô hình mô tả đạo hàm, ý nghĩa hình học của tiếp tuyến.</li>
                </ul>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                HÌNH HỌC VÀ ĐO LƯỜNG
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <strong><em>Hình học không gian</em></strong>
            </td>
        </tr>

        <tr>
            <td>
                Đường thẳng và mặt phẳng trong không gian
            </td>
            <td>
                Đường thẳng và mặt phẳng trong không gian. Cách xác định mặt phẳng. Hình chóp và hình tứ diện
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được các quan hệ liên thuộc cơ bản giữa điểm, đường thẳng, mặt phẳng trong không gian.
                    </li>
                    <li>
                        Mô tả được ba cách xác định mặt phẳng (qua ba điểm không thẳng hàng; qua một đường thẳng và một điểm không thuộc đường thẳng đó; qua hai đường thẳng cắt nhau).
                    </li>
                    <li>
                        Xác định được giao tuyến của hai mặt phẳng; giao điểm của đường thẳng và mặt phẳng.
                    </li>
                    <li>
                        Vận dụng được các tính chất về giao tuyến của hai mặt phẳng; giao điểm của đường thẳng và mặt phẳng vào giải bài tập.
                    </li>
                    <li>
                        Nhận biết được hình chóp, hình tứ diện.
                    </li>
                    <li>
                        Vận dụng được kiến thức về đường thẳng, mặt phẳng trong không gian để mô tả một số hình ảnh trong thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td rowspan="4">
                Quan hệ song song trong không gian. Phép chiếu song song
            </td>
            <td>
                Hai đường thẳng song song
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được vị trí tương đối của hai đường thẳng trong không gian: hai đường thẳng trùng nhau, song song, cắt nhau, chéo nhau trong không gian.
                    </li>
                    <li>
                        Giải thích được tính chất cơ bản về hai đường thẳng song song trong không gian.
                    </li>
                    <li>
                        Vận dụng được kiến thức về hai đường thẳng song song để mô tả một số hình ảnh trong thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Đường thẳng và mặt phẳng song song
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được đường thẳng song song với mặt phẳng.
                    </li>
                    <li>
                        Giải thích được điều kiện để đường thẳng song song với mặt phẳng.
                    </li>
                    <li>
                        Giải thích được tính chất cơ bản về đường thẳng song song với mặt phẳng.
                    </li>
                    <li>
                        Vận dụng được kiến thức về đường thẳng song song với mặt phẳng để mô tả một số hình ảnh trong thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Hai mặt phẳng song song. Định lí Thalès trong không gian. Hình lăng trụ và hình hộp
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được hai mặt phẳng song song trong không gian.
                    </li>
                    <li>
                        Giải thích được điều kiện để hai mặt phẳng song song.
                    </li>
                    <li>
                        Giải thích được tính chất cơ bản về hai mặt phẳng song song.
                    </li>
                    <li>
                        Giải thích được định lí Thalès trong không gian.
                    </li>
                    <li>
                        Giải thích được tính chất cơ bản của lăng trụ và hình hộp.
                    </li>
                    <li>
                        Vận dụng được kiến thức về quan hệ song song để mô tả một số hình ảnh trong thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Phép chiếu song song. Hình biểu diễn của một hình không gian
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được khái niệm và các tính chất cơ bản về phép chiếu song song.
                    </li>
                    <li>
                        Xác định được ảnh của một điểm, một đoạn thẳng, một tam giác, một đường tròn qua một phép chiếu song song.
                    </li>
                    <li>
                        Vẽ được hình biểu diễn của một số hình khối đơn giản.
                    </li>
                    <li>
                        Sử dụng được kiến thức về phép chiếu song song để mô tả một số hình ảnh trong thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td rowspan="6">
                Quan hệ vuông góc trong không gian. Phép chiếu vuông góc
            </td>
            <td>
                Góc giữa hai đường thẳng. Hai đường thẳng vuông góc
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được khái niệm góc giữa hai đường thẳng trong không gian.
                    </li>
                    <li>
                        Nhận biết được hai đường thẳng vuông góc trong không gian.
                    </li>
                    <li>
                        Chứng minh được hai đường thẳng vuông góc trong không gian trong một số trường hợp đơn giản.
                    </li>
                    <li>
                        Sử dụng được kiến thức về hai đường thẳng vuông góc để mô tả một số hình ảnh trong thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                Đường thẳng vuông góc với mặt phẳng. Định lí ba đường vuông góc. Phép chiếu vuông góc
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được đường thẳng vuông góc với mặt phẳng.
                    </li>
                    <li>
                        Xác định được điều kiện để đường thẳng vuông góc với mặt phẳng.
                    </li>
                    <li>
                        Giải thích được được định lí ba đường vuông góc.
                    </li>
                    <li>
                        Giải thích được được mối liên hệ giữa tính song song và tính vuông góc của đường thẳng và mặt phẳng.
                    </li>
                    <li>
                        Nhận biết được khái niệm phép chiếu vuông góc.
                    </li>
                    <li>
                        Xác định được hình chiếu vuông góc của một điểm, một đường thẳng, một tam giác.
                    </li>
                    <li>
                        Nhận biết được công thức tính thể tích của hình chóp, hình lăng trụ, hình hộp.                        
                    </li>
                    <li>
                        Tính được thể tích của hình chóp, hình lăng trụ, hình hộp trong những trường hợp đơn giản (ví dụ: nhận biết được đường cao và diện tích mặt đáy của hình chóp).
                    </li>
                    <li>
                         Vận dụng được kiến thức về đường thẳng vuông góc với mặt phẳng để mô tả một số hình ảnh trong thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                Hai mặt phẳng vuông góc. Hình lăng trụ đứng, lăng trụ đều, hình hộp đứng, hình hộp chữ nhật, hình lập phương,hình chóp đều.
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được hai mặt phẳng vuông góc trong không gian.
                    </li>
                    <li>
                        Xác định được điều kiện để hai mặt phẳng vuông góc.
                    </li>
                    <li>
                        Giải thích được tính chất cơ bản về hai mặt phẳng vuông góc.
                    </li>
                    <li>
                        Giải thích được tính chất cơ bản của hình lăng trụ đứng, lăng trụ đều, hình hộp đứng, hình hộp chữ nhật, hình lập phương, hình chóp đều.
                    </li>
                    <li>
                        Vận dụng được kiến thức về hai mặt phẳng vuông góc để mô tả một số hình ảnh trong thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                Khoảng cách trong không gian
            </td>
            <td>
                <ul>
                    <li>
                        Xác định được khoảng cách từ một điểm đến một đường thẳng; khoảng cách từ một điểm đến một mặt phẳng; khoảng cách giữa hai đường thẳng song song; khoảng cách giữa đường thẳng và mặt phẳng song song; khoảng cách giữa hai mặt phẳng song song trong những trường hợp đơn giản.
                    </li>
                    <li>
                        Nhận biết được đường vuông góc chung của hai đường thẳng chéo nhau; tính được khoảng cách giữa hai đường thẳng chéo nhau trong những trường hợp đơn giản (ví dụ: có một đường thẳng vuông góc với mặt phẳng chứa đường thẳng còn lại).
                    </li>
                    <li>
                        Sử dụng được kiến thức về khoảng cách trong không gian để mô tả một số hình ảnh trong thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                Góc giữa đường thẳng và mặt phẳng. Góc nhị diện và góc phẳng nhị diện
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được khái niệm góc giữa đường thẳng và mặt phẳng.
                    </li>
                    <li>
                        Xác định và tính được góc giữa đường thẳng và mặt phẳng trong những trường hợp đơn giản (ví dụ: đã biết hình chiếu vuông góc của đường thẳng lên mặt phẳng).
                    </li>
                    <li>
                        Nhận biết được khái niệm góc nhị diện, góc phẳng nhị diện.
                    </li>
                    <li>
                        Xác định và tính được số đo góc nhị diện, góc phẳng nhị diện trong những trường hợp đơn giản (ví dụ: nhận biết được mặt phẳng vuông góc với cạnh nhị diện).
                    </li>
                    <li>
                        Sử dụng được kiến thức về góc giữa đường thẳng và mặt phẳng, góc nhị diện để mô tả một số hình ảnh trong thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Hình chóp cụt đều và thể tích
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được hình chóp cụt đều.
                    </li>
                    <li>
                        Tính được thể tích khối chóp cụt đều.
                    </li>
                    <li>
                        Vận dụng được kiến thức về hình chóp cụt đều để mô tả một số hình ảnh trong thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <strong><em>
                    Thực hành trong phòng máy tính với phần mềm toán học (nếu nhà trường có điều kiện thực hiện)
                </em></strong>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <ul>
                    <li>
                        Sử dụng phần mềm để hỗ trợ việc học các kiến thức hình học.
                    </li>
                    <li>
                        Thực hành sử dụng phần mềm để vẽ đường thẳng, mặt phẳng, giao điểm, giao tuyến, tạo hình trong không gian, xác định hình biểu diễn.
                    </li>
                    <li>
                        Thực hành sử dụng phần mềm hỗ trợ đồ hoạ và vẽ kĩ thuật.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                THỐNG KÊ VÀ XÁC SUẤT
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <strong><em>
                    Thống kê
                </em></strong>
            </td>
        </tr>

        <tr>
            <td>
                Phân tích và xử lí dữ liệu
            </td>
            <td>
                Các số đặc trưng của mẫu số liệu ghép nhóm
            </td>
            <td>
                <ul>
                    <li>
                        Tính được các số đặc trưng đo xu thế trung tâm cho mẫu số liệu ghép nhóm: số trung bình cộng (hay số trung bình), trung vị (median), tứ phân vị (quartiles), mốt (mode).
                    </li>
                    <li>
                        Hiểu được ý nghĩa và vai trò của các số đặc trưng nói trên của mẫu số liệu trong thực tiễn.
                    </li>
                    <li>
                        Rút ra được kết luận nhờ ý nghĩa của các số đặc trưng nói trên của mẫu số liệu trong trường hợp đơn giản.
                    </li>
                    <li>
                        Nhận biết được mối liên hệ giữa thống kê với những kiến thức của các môn học khác trong Chương trình lớp 11 và trong thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <strong><em>
                    Xác suất
                </em></strong>
            </td>
        </tr>

        <tr>
            <td>
                Khái niệm về xác suất
            </td>
            <td>
                Một số khái niệm về xác suất cổ điển
            </td>
            <td>
                Nhận biết được một số khái niệm về xác suất cổ điển: hợp và giao các biến cố; biến cố độc lập.
            </td>
        </tr>

        <tr>
            <td>
                Các quy tắc tính xác suất
            </td>
            <td>
                Các quy tắc tính xác suất 
            </td>
            <td>
                <ul>
                    <li>
                        Tính được xác suất của biến cố hợp bằng cách sử dụng công thức cộng.
                    </li>
                    <li>
                        Tính được xác suất của biến cố giao bằng cách sử dụng công thức nhân (cho trường hợp biến cố độc lập).
                    </li>
                    <li>
                        Tính được xác suất của biến cố trong một số bài toán đơn giản bằng phương pháp tổ hợp.
                    </li>
                    <li>
                        Tính được xác suất trong một số bài toán đơn giản bằng cách sử dụng sơ đồ hình cây.
                    </li>
                </ul>
            </td>
        </tr>
        
        <tr>
            <td colspan="3"><strong><em>
                Thực hành trong phòng máy tính với phần mềm toán học (nếu nhà trường có điều kiện thực hiện)
            </em></strong></td>
        </tr>

        <tr>
            <td colspan="3">
                <ul>
                    <li>
                        Sử dụng phần mềm để hỗ trợ việc học các kiến thức thống kê và xác suất.
                    </li>
                    <li>
                        Sử dụng phần mềm để tính được các số đặc trưng đo xu thế trung tâm cho mẫu số liệu ghép nhóm.
                    </li>
                    <li>
                        Thực hành sử dụng phần mềm để tính xác suất.
                    </li>
                </ul>
           </td>
        </tr>

        <tr>
            <td colspan="3">
                HOẠT ĐỘNG THỰC HÀNH VÀ TRẢI NGHIỆM
            </td>
        </tr>

        <tr>
            <td colspan="3">
                Nhà trường tổ chức cho học sinh một số hoạt động sau và có thể bổ sung các hoạt động khác tuỳ vào điều kiện cụ thể.<br>

                <em>Hoạt động 1:</em> Thực hành ứng dụng các kiến thức toán học vào thực tiễn và các chủ đề liên môn, chẳng hạn:<br>
                    Thực hành tổng hợp các hoạt động liên quan đến tính toán, đo lường, ước lượng và vận dụng các kiến thức hình học không gian vào đồ hoạ, vẽ kĩ thuật, như: vận dụng kiến thức về hàm số lượng giác vào tìm hiểu hệ thống hướng dẫn cất cánh và hạ cánh của máy bay, tìm hiểu hệ thống xác định phần tử bắn của pháo binh, tên lửa; vận dụng kiến thức về xác suất thống kê để giải thích các quy luật di truyền học; vận dụng các kiến thức hình học không gian vào đồ hoạ, vẽ kĩ thuật và thiết kế trong công nghệ.

                <em>Hoạt động 2:</em> Thực hành ứng dụng các kiến thức toán học vào lĩnh vực Giáo dục dân số, chẳng hạn: vận dụng cấp số cộng, cấp số nhân để giải thích quy luật tăng trưởng dân số; vận dụng hàm số mũ, hàm số lôgarit để giải thích ảnh hưởng của sự tăng trưởng dân số tới tiến bộ kinh tế - xã hội, giải thích mối liên hệ giữa sự tăng trưởng dân số với môi trường sinh thái,...

                <em>Hoạt động 3:</em> Tìm hiểu một số kiến thức về tài chính, như:
                    <ul>
                        <li>
                            Thực hành lên kế hoạch và quản lí thu nhập và tích luỹ của cải trong khoảng thời gian ngắn hạn và trung hạn.
                        </li>
                        <li>
                            Xác định được các phương thức để bảo vệ bản thân khỏi rủi ro.
                        </li>
                    </ul>

                <em>Hoạt động 4:</em> Tổ chức các hoạt động ngoài giờ chính khoá: câu lạc bộ toán học; cuộc thi về Toán, dự án học tập, ra báo tường (hoặc nội san) về Toán, như: câu lạc bộ về ứng dụng toán học trong khoa học máy tính và công nghệ thông tin,...

                <em>Hoạt động 5 (nếu nhà trường có điều kiện thực hiện):</em> Tổ chức giao lưu học sinh giỏi Toán trong trường và trường bạn, giao lưu với các chuyên gia nhằm hiểu rõ hơn về vai trò của Toán học trong thực tiễn và trong các ngành nghề.
            </td>
        </tr>
    </tbody>
</table>

#### Nội dung Chuyên đề lớp 11: Ứng dụng Toán học vào giải quyết vấn đề thực tiễn, đặc biệt là một số vấn đề liên quan đến đồ họa và vẽ kĩ thuật.

- Chuyên đề 11.1: Phép biến hình phẳng.
- Chuyên đề 11.2: Một số yếu tố vẽ kĩ thuật.
- Chuyên đề 11.3: Làm quen với một số yếu tố của Lí thuyết đồ thị.

<table>
    <thead>
        <tr>
            <th>Chuyên đề</th>
            <th>Chủ đề</th>
            <th>Yêu cầu cần đạt</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td rowspan="2">
                Chuyên đề 11.1: <strong><em>Phép biến hình phẳng</strong></em>
            </td>
            <td>
                Phép dời hình. Phép đối xứng trục. Phép đối xứng tâm. Phép tịnh tiến. Phép quay
            </td>
            <td>
                <ul>
                    <li>
                       Nhận biết được khái niệm phép dời hình.
                    </li>
                    <li>
                        Nhận biết được tính chất của phép đối xứng trục, phép đối xứng tâm, phép tịnh tiến và phép quay.
                    </li>
                    <li>
                        Xác định được ảnh của điểm, đoạn thẳng, tam giác, đường tròn qua phép đối xứng trục, phép đối xứng tâm, phép tịnh tiến và phép quay.
                    </li>
                    <li>
                        Vận dụng được các phép dời hình nói trên trong đồ hoạ và trong một số vấn đề thực tiễn (ví dụ: tạo các hoa văn, hình khối,...).
                    </li>
                <ul>
            </td>
        </tr>

        <tr>
            <td>
                Phép đồng dạng phối cảnh (phép vị tự). Phép đồng dạng
            </td>
            <td>
                <ul>
                    <li>
                       Nhận biết được khái niệm phép đồng dạng phối cảnh (phép vị tự), phép đồng dạng.
                    </li>
                    <li>
                        Nhận biết được tính chất của phép vị tự.
                    </li>
                    <li>
                        Xác định được ảnh của điểm, đoạn thẳng, tam giác, đường tròn qua phép vị tự.
                    </li>
                    <li>
                        Vận dụng được phép đồng dạng trong đồ hoạ và trong một số vấn đề thực tiễn (ví dụ: tạo các hoa văn, hình khối,...).
                    </li>
                <ul>
            </td>
        </tr>

        <tr>
            <td>
                Chuyên đề 11.2: <strong><em>Một số yếu tố vẽ kĩ thuật</strong></em>
            </td>
            <td>
                Một số yếu tố vẽ kĩ thuật
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được hình biểu diễn của một hình, khối.
                    </li>
                    <li>
                        Nhận biết được một số nguyên tắc cơ bản của vẽ kĩ thuật.
                    </li>
                    <li>
                        Đọc được thông tin từ một số bản vẽ kĩ thuật đơn giản.
                    </li>
                    <li>
                        Vẽ được bản vẽ kĩ thuật đơn giản (gắn với phép chiếu song song và phép chiếu vuông góc).
                    </li>
                <ul>
            </td>
        </tr>

        <tr>
            <td>
                Chuyên đề 11.3: <strong><em>Làm quen với một vài yếu tố của Lí thuyết đồ thị</strong></em>
            </td>
            <td>
                Giới thiệu một số bài toán về tìm đường đi trong những mô hình xuất phát từ thực tiễn
            </td>
            <td>
                <ul>
                    <li>
                       Nhận biết được khái niệm đồ thị.
                    </li>
                    <li>
                        Nhận biết được đường đi Euler, đường đi Hamilton từ đồ thị.
                    </li>
                    <li>
                        Nhận biết được thuật toán về tìm đường đi tối ưu trong những trường hợp đơn giản.
                    </li>
                    <li>
                        Sử dụng kiến thức về đồ thị để giải quyết một số tình huống liên quan đến thực tiễn (ví dụ: xác định đường đi, xác định đường đi ngắn nhất,...).
                    </li>
                <ul>
            </td>
        </tr>
    </tbody>
</table>

### Lớp 12

<table>
    <thead>
        <tr>
            <th colspan="2">Nội dung</th>
            <th>Yêu cầu cần đạt</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td colspan="3">MỘT SỐ YẾU TỐ GIẢI TÍCH</td>
        </tr>
        
        <tr>
            <td colspan="3">
                <strong><em>Một số yếu tố giải tích</em></strong>
            </td>
        </tr>

        <tr>
            <td rowspan="4">
                Ứng dụng đạo hàm để khảo sát và vẽ đồ thị của hàm số
            </td>
            <td>
                Tính đơn điệu của hàm số
            </td>
            <td>
                <ul>
                    <li>
                       Nhận biết được tính đồng biến, nghịch biến của một hàm số trên một khoảng dựa vào dấu của đạo hàm cấp một của nó.
                    </li>
                    <li>
                        Thể hiện được tính đồng biến, nghịch biến của hàm số trong bảng biến thiên.
                    </li>
                    <li>
                       Nhận biết được tính đơn điệu, điểm cực trị, giá trị cực trị của hàm số thông qua bảng biến thiên hoặc thông qua hình ảnh hình học của đồ thị hàm số.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Giá trị lớn nhất, giá trị nhỏ nhất của hàm số
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được giá trị lớn nhất, giá trị nhỏ nhất của hàm số trên một tập xác định cho trước.
                    </li>
                    <li>
                        Xác định được giá trị lớn nhất, giá trị nhỏ nhất của hàm số bằng đạo hàm trong những trường hợp đơn giản.
                    </li>
                </ul>
            </td>
        </tr>
        
        <tr>
            <td>
                Khảo sát và vẽ đồ thị của hàm số
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được hình ảnh hình học của đường tiệm cận ngang, đường tiệm cận đứng, đường tiệm cận xiên của đồ thị hàm số.
                    </li>
                    <li>
                        Mô tả được sơ đồ tổng quát để khảo sát hàm số (tìm tập xác định, xét chiều biến thiên, tìm cực trị, tìm tiệm cận, lập bảng biến thiên, vẽ đồ thị).
                    </li>
                    <li>
                        Khảo sát được tập xác định, chiều biến thiên, cực trị, tiệm cận, bảng biến thiên và vẽ đồ thị của các hàm số:
                            $$
                                y=ax^3+bx^2+cx+d\, (a\ne 0);
                            $$
                            $$
                                y=\frac{ax+b}{cx+d}\, (c\ne 0, ab-bc\ne 0);
                            $$
                            $$
                                y=\frac{ax^2+bx+c}{mx+n}\, (a\ne 0, m\ne 0\, \text{và đa thức tử không chia hết cho đa thức mẫu}).
                            $$
                    </li>
                    <li>
                        Nhận biết được tính đối xứng (trục đối xứng, tâm đối xứng) của đồ thị các hàm số trên.
                    </li>
                </ul>
            </td>
        </tr>
        
        <tr>
            <td>
                Ứng dụng đạo hàm để giải quyết một số vấn đề liên quan đến thực tiễn
            </td>
            <td>
                Vận dụng được đạo hàm và khảo sát hàm số để giải quyết một số vấn đề liên quan đến thực tiễn.
            </td>
        </tr>
        
        <tr>
            <td rowspan="2">
                Nguyên hàm. Tích phân
            </td>
            <td>
                Nguyên hàm. Bảng nguyên hàm của một số hàm số sơ cấp
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được khái niệm nguyên hàm của một hàm số.
                    </li>
                    <li>
                        Giải thích được tính chất cơ bản của nguyên hàm.
                    </li>
                    <li>
                        Xác định được nguyên hàm của một số hàm số sơ cấp như: $y=x^\alpha\, (\alpha\ne -1)$, $y=\frac{1}{x}$, $y=\sin x$, $y=\cos x$, $y=\frac{1}{\cos^2 x}$, $y=\frac{1}{\sin^2 x}$, $y=a^x$, $y=ex^x$.
                    </li>
                    <li>
                        Tính được nguyên hàm trong những trường hợp đơn giản.
                    </li>
                </ul>
            </td>
        </tr>
        
        <tr>
            <td>
                Tích phân. Ứng dụng hình học của tích phân
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được định nghĩa và các tính chất của tích phân.
                    </li>
                    <li>
                        Tính được tích phân trong những trường hợp đơn giản
                    </li>
                    <li>
                        Sử dụng được tích phân để tính diện tích của một số hình phẳng, thể tích của một số hình khối.
                    </li>
                    <li>
                        Vận dụng được tích phân để giải một số bài toán có liên quan đến thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <strong><em>
                    Thực hành trong phòng máy tính với phần mềm toán học (nếu nhà trường có điều kiện thực hiện)
                </em></strong>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <ul>
                    <li>
                        Sử dụng phần mềm để hỗ trợ việc học các kiến thức đại số và giải tích.
                    </li>
                    <li>
                        Thực hành sử dụng phần mềm để vẽ các đồ thị; minh hoạ sự tương giao của các đồ thị; thực hiện các phép biến đổi đồ thị; tạo hoa văn, hình khối.
                    </li>
                    <li>
                        Thực hành sử dụng phần mềm để tạo mô hình khối tròn xoay trong một số bài toán ứng dụng tích phân xác định.
                    </li>
                </ul>
            </td>
        </tr> 
        
        <tr>
            <td colspan="3">
                HÌNH HỌC VÀ ĐO LƯỜNG
            </td>
        </tr>

        <tr>
            <td colspan="14">
                <strong><em>Hình học không gian</em></strong>
            </td>
        </tr>

        <tr>
            <td rowspan="4">
                Phương pháp toạ độ trong không gian
            </td>
            <td>
                Toạ độ của véc-tơ đối với một hệ trục toạ độ. Biểu thức toạ độ của các phép toán véc-tơ
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được véc-tơ và các phép toán véc-tơ trong không gian (tổng và hiệu của hai véc-tơ, tích của một số với một véc-tơ, tích vô hướng của hai véc-tơ).
                    </li>
                    <li>
                        Nhận biết được toạ độ của một véc-tơ đối với hệ trục toạ độ.
                    </li>
                    <li>
                        Xác định được độ dài của một véc-tơ khi biết toạ độ hai đầu mút của nó và biểu thức toạ độ của các phép toán véc-tơ.
                    </li>
                    <li>
                        Xác định được biểu thức toạ độ của các phép toán véc-tơ.
                    </li>
                    <li>
                        Vận dụng được toạ độ của véc-tơ để giải một số bài toán có liên quan đến thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Phương trình mặt phẳng
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được phương trình tổng quát của mặt phẳng.
                    </li>
                    <li>
                        Thiết lập được phương trình tổng quát của mặt phẳng trong hệ trục toạ độ $Oxyz$ theo một trong ba cách cơ bản: qua một điểm và biết véc-tơ pháp tuyến; qua một điểm và biết cặp véc-tơ chỉ phương (suy ra véc-tơ pháp tuyến nhờ vào việc tìm véc-tơ vuông góc với cặp véc-tơ chỉ phương); qua ba điểm không thẳng hàng.
                    </li>
                    <li>
                        Thiết lập được điều kiện để hai mặt phẳng song song, vuông góc với nhau.
                    </li>
                    <li>
                        Tính được khoảng cách từ một điểm đến một mặt phẳng bằng phương pháp toạ độ.
                    </li>
                    <li>
                        Vận dụng được kiến thức về phương trình mặt phẳng để giải một số bài toán liên quan đến thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Phương trình đường thẳng trong không gian 
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được phương trình chính tắc, phương trình tham số, véc-tơ chỉ phương của đường thẳng trong không gian.
                    </li>
                    <li>
                        Thiết lập được phương trình của đường thẳng trong hệ trục toạ độ theo một trong hai cách cơ bản: qua một điểm và biết một véc-tơ chỉ phương, qua hai điểm.
                    </li>
                    <li>
                        Xác định được điều kiện để hai đường thẳng chéo nhau, cắt nhau, song song hoặc vuông góc với nhau.
                    </li>
                    <li>
                        Thiết lập được công thức tính góc giữa hai đường thẳng, giữa đường thẳng và mặt phẳng, giữa hai mặt phẳng.
                    </li>
                    <li>
                        Vận dụng được kiến thức về phương trình đường thẳng trong không gian để giải một số bài toán liên quan đến thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Phương trình mặt cầu
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được phương trình mặt cầu.
                    </li>
                    <li>
                        Xác định được tâm, bán kính của mặt cầu khi biết phương trình của nó.
                    </li>
                    <li>
                        Thiết lập được phương trình của mặt cầu khi biết tâm và bán kính.
                    </li>
                    <li>
                        Vận dụng được kiến thức về phương trình mặt cầu để giải một số bài toán liên quan đến thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <strong><em>
                    Thực hành trong phòng máy tính với phần mềm toán học (nếu nhà trường có điều kiện thực hiện)
                </em></strong>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <ul>
                    <li>
                        Sử dụng phần mềm để hỗ trợ việc học các kiến thức hình học.
                    </li>
                    <li>
                        Thực hành sử dụng phần mềm để biểu thị điểm, véc-tơ, các phép toán véc-tơ trong hệ trục toạ độ $Oxyz$.
                    </li>
                    <li>
                        Thực hành sử dụng phần mềm để vẽ đường thẳng, mặt phẳng, mặt cầu trong hệ trục toạ độ $Oxyz$; xem xét sự thay đổi hình dạng khi thay đổi các yếu tố trong phương trình của chúng.

                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                THỐNG KÊ VÀ XÁC SUẤT
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <strong><em>
                    Thống kê
                </em></strong>
            </td>
        </tr>

        <tr>
            <td>
                Phân tích và xử lí dữ liệu
            </td>
            <td>
                Các số đặc trưng của mẫu số liệu ghép nhóm
            </td>
            <td>
                <ul>
                    <li>
                        Tính được các số đặc trưng đo mức độ phân tán cho mẫu số liệu ghép nhóm: khoảng biến thiên, khoảng tứ phân vị, phương sai, độ lệch chuẩn.
                    </li>
                    <li>
                        Giải thích được ý nghĩa và vai trò của các số đặc trưng nói trên của mẫu số liệu trong thực tiễn.
                    </li>
                    <li>
                        Chỉ ra được những kết luận nhờ ý nghĩa của các số đặc trưng nói trên của mẫu số liệu trong trường hợp đơn giản.
                    </li>
                    <li>
                        Nhận biết được mối liên hệ giữa thống kê với những kiến thức của các môn học khác trong Chương trình lớp 12 và trong thực tiễn.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <strong><em>
                    Xác suất
                </em></strong>
            </td>
        </tr>

        <tr>
            <td>
                Khái niệm về xác suất có điều kiện 
            </td>
            <td>
                Xác suất có điều kiện 
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được khái niệm về xác suất có điều kiện.
                    </li>
                    <li>
                        Giải thích được ý nghĩa của xác suất có điều kiện trong những tình huống thực tiễn quen thuộc.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                Các quy tắc tính xác suất
            </td>
            <td>
                Các quy tắc tính xác suất 
            </td>
            <td>
                <ul>
                    <li>
                        Mô tả được công thức xác suất toàn phần, công thức Bayes thông qua bảng dữ liệu thống kê 2x2 và sơ đồ hình cây.
                    </li>
                    <li>
                        Sử dụng được công thức Bayes để tính xác suất có điều kiện và vận dụng vào một số bài toán thực tiễn.
                    </li>
                    <li>
                        Sử dụng được sơ đồ hình cây để tính xác suất có điều kiện trong một số bài toán thực tiễn liên quan tới thống kê.

                    </li>
                </ul>
            </td>
        </tr>
        
        <tr>
            <td colspan="3"><strong><em>
                Thực hành trong phòng máy tính với phần mềm toán học (nếu nhà trường có điều kiện thực hiện)
            </em></strong></td>
        </tr>

        <tr>
            <td colspan="3">
                <ul>
                    <li>
                        Sử dụng phần mềm để hỗ trợ việc học các kiến thức thống kê và xác suất.
                    </li>
                    <li>
                        Thực hành sử dụng phần mềm để tính phân bố nhị thức, tính toán thống kê.
                    </li>
                </ul>
           </td>
        </tr>

        <tr>
            <td colspan="3">
                HOẠT ĐỘNG THỰC HÀNH VÀ TRẢI NGHIỆM
            </td>
        </tr>

        <tr>
            <td colspan="3">
                Nhà trường tổ chức cho học sinh một số hoạt động sau và có thể bổ sung các hoạt động khác tuỳ vào điều kiện cụ thể.<br>

                <em>Hoạt động 1:</em> Thực hành ứng dụng các kiến thức toán học vào thực tiễn và các chủ đề liên môn, chẳng hạn:<br>
                    <ul>
                        <li>
                            Thực hành tổng hợp các hoạt động liên quan đến tính toán, đo lường, ước lượng và tạo lập hình.
                        </li>
                        <li>
                            Vận dụng kiến thức về phương pháp toạ độ trong hình học không gian để tìm hiểu hệ thống GPS, tìm hiểu về đồ hoạ, vẽ kĩ thuật và thiết kế trong Công nghệ.
                        </li>
                        <li>
                            Vận dụng kiến thức về đạo hàm để giải thích các quy luật của Vật lí (quy luật âm học, quang học), Hoá học và giải quyết bài toán tối ưu về kinh tế, thời gian, quãng đường,...
                        </li>
                    </ul>

                <em>Hoạt động 2:</em> Vận dụng các kiến thức toán học vào một số vấn đề liên quan đến tài chính.

                <em>Hoạt động 3:</em> Tổ chức các hoạt động ngoài giờ chính khoá: câu lạc bộ toán học; cuộc thi về Toán; dự án học tập; ra báo tường (hoặc nội san) về Toán, chẳng hạn: câu lạc bộ về ứng dụng toán học trong khoa học máy tính và công nghệ thông tin.

                <em>Hoạt động 4 (nếu nhà trường có điều kiện thực hiện):</em> Tổ chức giao lưu học sinh giỏi Toán trong trường và trường bạn, giao lưu với các chuyên gia nhằm hiểu vai trò của Toán học trong thực tiễn và trong các ngành nghề,...
            </td>
        </tr>
    </tbody>
</table>

#### Nội dung Chuyên đề lớp 12: Ứng dụng Toán học vào giải quyết vấn đề thực tiễn, đặc biệt là một số vấn đề liên quan đến kinh tế và tài chính

- Chuyên đề 12.1: Biến ngẫu nhiên rời rạc. Các số đặc trưng của biến ngẫu nhiên rời rạc.
- Chuyên đề 12.2: Ứng dụng toán học để giải quyết một số bài toán tối ưu.
- Chuyên đề 12.3:  Ứng dụng toán học trong một số vấn đề liên quan đến tài chính.

<table>
    <thead>
        <tr>
            <th>Chuyên đề</th>
            <th>Chủ đề</th>
            <th>Yêu cầu cần đạt</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td rowspan="2">
                Chuyên đề 12.1: <strong><em>Biến ngẫu nhiên rời rạc. Các số đặc trưng của biến ngẫu nhiên rời rạc</strong></em>
            </td>
            <td>
                Biến ngẫu nhiên rời rạc. Các số đặc trưng của biến ngẫu nhiên rời rạc
            </td>
            <td>
                <ul>
                    <li>
                       Nhận biết được khái niệm biến ngẫu nhiên rời rạc; phân bố xác suất của biến ngẫu nhiên rời rạc; kì vọng, phương sai, độ lệch chuẩn của biến ngẫu nhiên rời rạc.
                    </li>
                    <li>
                        Lập và đọc được bảng phân bố xác suất của biến ngẫu nhiên rời rạc với một số ít giá trị.
                    </li>
                    <li>
                        Tính được kì vọng, phương sai và độ lệch chuẩn của biến ngẫu nhiên rời rạc.
                    </li>
                    <li>
                        Giải thích được ý nghĩa thực tiễn của các số đặc trưng của biến ngẫu nhiên rời rạc.
                    </li>
                    <li>
                        Vận dụng được kiến thức về xác suất, các số đặc trưng của biến ngẫu nhiên rời rạc để giải quyết một số bài toán thực tiễn (ví dụ: tìm phương án cho năng suất cao, tìm phương án để rủi ro là ít nhất,...).
                    </li>
                <ul>
            </td>
        </tr>

        <tr>
            <td>
                Phân bố Bernoulli. Phân bố nhị thức
            </td>
            <td>
                <ul>
                    <li>
                       Nhận biết được khái niệm về phép thử lặp và công thức Bernoulli.
                    </li>
                    <li>
                        Nhận biết được khái niệm phân bố nhị thức. Nhận biết được ý nghĩa của phân bố nhị thức.
                    </li>
                    <li>
                        Vận dụng phân bố nhị thức để giải một số bài toán liên quan đến thực tiễn.
                    </li>
                <ul>
            </td>
        </tr>

        <tr>
            <td rowspan="2">
                Chuyên đề 11.2: <strong><em>Ứng dụng toán học để giải quyết một số bài toán tối ưu</strong></em>
            </td>
            <td>
                Vận dụng hệ bất phương trình bậc nhất để giải quyết một số bài toán quy hoạch tuyến tính
            </td>
            <td>
                Vận dụng được các kiến thức về hệ bất phương trình bậc nhất để giải quyết một số bài toán quy hoạch tuyến tính.
            </td>
        </tr>
        
        <tr>
            <td>
                Vận dụng đạo hàm để giải quyết một số bài toán tối ưu trong thực tiễn, đặc biệt là trong kinh tế
            </td>
            <td>
                <ul>
                    <li>
                       Vận dụng được các kiến thức về đạo hàm để giải quyết một số bài toán tối ưu xuất hiện trong thực tiễn (ví dụ: bài toán tối ưu liên quan đến khoảng cách, thời gian,...).
                    </li>
                    <li>
                        Vận dụng được các kiến thức về đạo hàm để giải quyết một số bài toán tối ưu trong kinh tế (ví dụ: bài toán tối ưu hoá chi phí sản xuất, bài toán tối ưu hoá lợi nhuận,...).
                    </li>
                <ul>
            </td>
        </tr>

        <tr>
            <td rowspan="2">
                Chuyên đề 12.3: <strong><em>Ứng dụng toán học trong một số vấn đề liên quan đến tài chính</strong></em>
            </td>
            <td>
                Vận dụng kiến thức toán học trong việc giải quyết một số vấn đề về lãi suất và vay nợ của các tổ chức tín dụng
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được một số vấn đề về tiền tệ.
                    </li>
                    <li>
                        Thiết lập được kế hoạch tài chính cá nhân cho các nhu cầu dài hạn như giáo dục hoặc sống tự lập.
                    </li>
                    <li>
                        Nhận biết được một số vấn đề về lãi suất và vay nợ của các tổ chức tín dụng (như ngân hàng, quỹ tín dụng,...).
                    </li>
                    <li>
                        Tính được lãi suất được hưởng qua tiền tiết kiệm và các giá trị thực chất có tính đến lạm phát.
                    </li>
                    <li>
                        Tính được lãi suất cần trả cho thẻ tín dụng, phí sử dụng thẻ (bao gồm các giao dịch).
                    </li>
                    <li>
                        Nhận biết được kết quả của việc trả các khoản tiền nợ đúng thời hạn, bao gồm hồ sơ tín dụng và giá trị tín dụng.
                    </li>
                    <li>
                        Vận dụng được kiến thức toán học (như các kiến thức về tỉ số, tỉ số phần trăm, phép tính luỹ thừa và lôgarit) trong việc giải quyết một số vấn đề về lãi suất và vay nợ của các tổ chức tín dụng (như ngân hàng, quỹ tín dụng,...).
                    </li>
                <ul>
            </td>
        </tr>

        <tr>
            <td>
                Vận dụng kiến thức toán học trong việc giải quyết một số vấn đề về đầu tư
            </td>
            <td>
                <ul>
                    <li>
                        Nhận biết được một số vấn đề về đầu tư.
                    </li>
                    <li>
                        Vận dụng được kiến thức toán học (như các kiến thức về tỉ số, tỉ số phần trăm, đạo hàm, cách tìm giá trị cực trị của biểu thức) trong việc giải quyết một số vấn đề về đầu tư.
                    </li>
                    <li>
                        Giải thích được rằng các khoản đầu tư có thể tăng giá trị, và cũng như tiền, có thể giảm giá trị nếu lạm phát vượt tỉ lệ lãi suất.
                    </li>
                <ul>
            </td>
        </tr>
    </tbody>
</table>

# VI. Phương pháp giáo dục 

## 1. Phương pháp dạy học trong Chương trình môn Toán đáp ứng các yêu cầu cơ bản sau:
a. Phù hợp với tiến trình nhận thức của học sinh (đi từ cụ thể đến trừu tượng, từ dễ đến khó); không chỉ coi trọng tính logic của khoa học toán học mà cần chú ý cách tiếp cận dựa trên vốn kinh nghiệm và sự trải nghiệm của học sinh;
b. Quán triệt tinh thần "lấy người học làm trung tâm", phát huy tính tích cực, tự giác, chú ý nhu cầu, năng lực nhận thức, cách thức học tập khác nhau của từng cá nhân học sinh; tổ chức quá trình dạy học theo hướng kiến tạo, trong đó học sinh được tham gia tìm tòi, phát hiện, suy luận giải quyết vấn đề;
c. Linh hoạt trong việc vận dụng các phương pháp, kĩ thuật dạy học tích cực; kết hợp nhuần nhuyễn, sáng tạo với việc vận dụng các phương pháp, kĩ thuật dạy học truyền thống; kết hợp các hoạt động dạy học trong lớp học với hoạt động thực hành trải nghiệm, vận dụng kiến thức toán học vào thực tiễn. Cấu trúc bài học bảo đảm tỉ lệ cân đối, hài hoà giữa kiến thức cốt lõi, kiến thức vận dụng và các thành phần khác.
d. Sử dụng đủ và hiệu quả các phương tiện, thiết bị dạy học tối thiểu theo quy định đối với môn Toán; có thể sử dụng các đồ dùng dạy học tự làm phù hợp với nội dung học và các đối tượng học sinh; tăng cường sử dụng công nghệ thông tin và các phương tiện, thiết bị dạy học hiện đại một cách phù hợp và hiệu quả.

## 2. Định hướng phương pháp hình thành và phát triển các phẩm chất chủ yếu và năng lực chung

a. Phương pháp hình thành, phát triển các phẩm chất chủ yếu

Thông qua việc tổ chức các hoạt động học tập, môn Toán góp phần cùng các môn học và hoạt động giáo dục khác giúp học sinh rèn luyện tính trung thực, tình yêu lao động, tinh thần trách nhiệm, ý thức hoàn thành nhiệm vụ học tập; bồi dưỡng sự tự tin, hứng thú học tập, thói quen đọc sách và ý thức tìm tòi, khám phá khoa học.

b. Phương pháp hình thành, phát triển các năng lực chung

- Môn Toán góp phần hình thành và phát triển năng lực tự chủ và tự học thông qua việc rèn luyện cho người học biết cách lựa chọn mục tiêu, lập được kế hoạch học tập, hình thành cách tự học, rút kinh nghiệm và điều chỉnh để có thể vận dụng vào các tình huống khác trong quá trình học các khái niệm, kiến thức và kĩ năng toán học cũng như khi thực hành,
luyện tập hoặc tự lực giải toán, giải quyết các vấn đề có ý nghĩa toán học.
- Môn Toán góp phần hình thành và phát triển năng lực giao tiếp và hợp tác thông qua việc nghe hiểu, đọc hiểu, ghi chép, diễn tả được các thông tin toán học cần thiết trong văn bản toán học; thông qua sử dụng hiệu quả ngôn ngữ toán học kết hợp với ngôn ngữ thông thường để trao đổi, trình bày được các nội dung, ý tưởng, giải pháp toán học trong sự tương tác với người khác, đồng thời thể hiện sự tự tin, tôn trọng người đối thoại khi mô tả, giải thích các nội dung, ý tưởng toán học.
- Môn Toán góp phần hình thành và phát triển năng lực giải quyết vấn đề và sáng tạo thông qua việc giúp học sinh nhận biết được tình huống có vấn đề; chia sẻ sự am hiểu vấn đề với người khác; biết đề xuất, lựa chọn được cách thức, quy trình giải quyết vấn đề và biết trình bày giải pháp cho vấn đề; biết đánh giá giải pháp đã thực hiện và khái quát hoá cho vấn đề tương tự.

## 3. Phương pháp dạy học môn Toán góp phần hình thành và phát triển năng lực tính toán, năng lực ngôn ngữ và các năng lực đặc thù khác. Cụ thể:

a. Môn Toán với ưu thế nổi trội, có nhiều cơ hội để phát triển năng lực tính toán thể hiện ở chỗ vừa cung cấp kiến thức toán học, rèn luyện kĩ năng tính toán, ước lượng, vừa giúp hình thành và phát triển các thành tố của năng lực toán học (năng lực tư duy và lập luận, năng lực mô hình hoá, năng lực giải quyết vấn đề; năng lực giao tiếp và năng lực sử dụng công cụ và phương tiện học toán).
b. Môn Toán góp phần phát triển năng lực ngôn ngữ thông qua rèn luyện kĩ năng đọc hiểu, diễn giải, phân tích, đánh giá tình huống có ý nghĩa toán học, thông qua việc sử dụng hiệu quả ngôn ngữ toán học kết hợp với ngôn ngữ thông thường để trình bày, diễn tả các nội dung, ý tưởng, giải pháp toán học.
c. Môn Toán góp phần phát triển năng lực tin học thông qua việc sử dụng các phương tiện, công cụ công nghệ thông tin và truyền thông như công cụ hỗ trợ trong học tập và tự học; tạo dựng môi trường học tập trải nghiệm.
d. Môn Toán góp phần phát triển năng lực thẩm mĩ thông qua việc giúp học sinh làm quen với lịch sử toán học, với tiểu
sử của các nhà toán học và thông qua việc nhận biết vẻ đẹp của Toán học trong thế giới tự nhiên.

# VII. Đánh giá kết quả giáo dục 

Mục tiêu đánh giá kết quả giáo dục môn Toán là cung cấp thông tin chính xác, kịp thời, có giá trị về sự phát triển năng lực và sự tiến bộ của học sinh trên cơ sở yêu cầu cần đạt ở mỗi lớp học, cấp học; điều chỉnh các hoạt động dạy học, bảo đảm sự tiến bộ của từng học sinh và nâng cao chất lượng giáo dục môn Toán nói riêng và chất lượng giáo dục nói chung.

Vận dụng kết hợp nhiều hình thức đánh giá (đánh giá quá trình, đánh giá định kì), nhiều phương pháp đánh giá (quan sát, ghi lại quá trình thực hiện, vấn đáp, trắc nghiệm khách quan, tự luận, kiểm tra viết, bài tập thực hành, các dự án/sản phẩm học tập, thực hiện nhiệm vụ thực tiễn,...) và vào những thời điểm thích hợp.

Đánh giá quá trình (hay đánh giá thường xuyên) do giáo viên phụ trách môn học tổ chức, kết hợp với đánh giá của giáo viên các môn học khác, của bản thân học sinh được đánh giá và của các học sinh khác trong tổ, trong lớp hoặc đánh giá của cha mẹ học sinh. Đánh giá quá trình đi liền với tiến trình hoạt động học tập của học sinh, tránh tình trạng tách rời giữa quá trình dạy học và quá trình đánh giá, bảo đảm mục tiêu đánh giá vì sự tiến bộ trong học tập của học sinh.

Đánh giá định kì (hay đánh giá tổng kết) có mục đích chính là đánh giá việc thực hiện các mục tiêu học tập. Kết quả đánh giá định kì và đánh giá tổng kết được sử dụng để chứng nhận cấp độ học tập, công nhận thành tích của học sinh. Đánh giá định kì do cơ sở giáo dục tổ chức hoặc thông qua các kì kiểm tra, đánh giá quốc gia.

Đánh giá định kì còn được sử dụng để phục vụ quản lí các hoạt động dạy học, bảo đảm chất lượng ở cơ sở giáo dục và phục vụ phát triển chương trình môn Toán.

Đánh giá năng lực học sinh thông qua các bằng chứng biểu hiện kết quả đạt được trong quá trình thực hiện các hành động của học sinh. Tiến trình đánh giá gồm các bước cơ bản như: xác định mục đích đánh giá; xác định bằng chứng cần thiết; lựa chọn các phương pháp, công cụ đánh giá thích hợp; thu thập bằng chứng; giải thích bằng chứng và đưa ra nhận xét.

Chú trọng việc lựa chọn phương pháp, công cụ đánh giá các thành tố của năng lực toán học. Cụ thể:

- Đánh giá năng lực tư duy và lập luận toán học: có thể sử dụng một số phương pháp, công cụ đánh giá như các câu hỏi (nói, viết), bài tập,... mà đòi hỏi học sinh phải trình bày, so sánh, phân tích, tổng hợp, hệ thống hoá kiến thức; phải vận dụng kiến thức toán học để giải thích, lập luận.
- Đánh giá năng lực mô hình hoá toán học: lựa chọn những tình huống trong thực tiễn làm xuất hiện bài toán toán học. Từ đó, đòi hỏi học sinh phải xác định được mô hình toán học (gồm công thức, phương trình, bảng biểu, đồ thị,...) cho tình huống xuất hiện trong bài toán thực tiễn; giải quyết được những vấn đề toán học trong mô hình được thiết lập; thể hiện và đánh giá được lời giải trong ngữ cảnh thực tiễn và cải tiến được mô hình nếu cách giải quyết không phù hợp.
- Đánh giá năng lực giải quyết vấn đề toán học: có thể sử dụng các phương pháp như yêu cầu người học nhận dạng tình huống, phát hiện và trình bày vấn đề cần giải quyết; mô tả, giải thích các thông tin ban đầu, mục tiêu, mong muốn của tình huống vấn đề đang xem xét; thu thập, lựa chọn, sắp xếp thông tin và kết nối với kiến thức đã có; sử dụng các câu hỏi (có thể yêu cầu trả lời nói hoặc viết) đòi hỏi người học vận dụng kiến thức vào giải quyết vấn đề, đặc biệt các vấn đề thực tiễn; sử dụng phương pháp quan sát (như bảng kiểm theo các tiêu chí đã xác định), quan sát người học trong quá trình giải quyết vấn đề; đánh giá qua các sản phẩm thực hành của người học (chẳng hạn sản phẩm của các dự án học tập); quan tâm hợp lí đến các nhiệm vụ đánh giá mang tính tích hợp.
- Đánh giá năng lực giao tiếp toán học: có thể sử dụng các phương pháp như yêu cầu người học nghe hiểu, đọc hiểu, ghi chép (tóm tắt), phân tích, lựa chọn, trích xuất được được các thông tin toán học cơ bản, trọng tâm trong văn bản nói hoặc viết; sử dụng được ngôn ngữ toán học kết hợp với ngôn ngữ thông thường trong việc trình bày, diễn đạt, nêu câu hỏi, thảo luận, tranh luận các nội dung, ý tưởng, giải pháp toán học trong sự tương tác với người khác.
- Đánh giá năng lực sử dụng công cụ, phương tiện học toán: có thể sử dụng các phương pháp như yêu cầu người học nhận biết được tên gọi, tác dụng, quy cách sử dụng, cách thức bảo quản, ưu điểm, hạn chế của các công cụ, phương tiện học toán; trình bày được cách sử dụng (hợp lí) công cụ, phương tiện học toán để thực hiện nhiệm vụ học tập hoặc để diễn tả những lập luận, chứng minh toán học.

Khi giáo viên lên kế hoạch bài học, cần thiết lập các tiêu chí và cách thức đánh giá để bảo đảm ở cuối mỗi bài học học sinh đạt được các yêu cầu cơ bản dựa trên các tiêu chí đã nêu, trước khi thực hiện các hoạt động học tập tiếp theo.

# VIII. Giải thích và hướng dẫn thực hiện chương trình 

## 1. Giải thích thuật ngữ

### a. Một số thuật ngữ chuyên môn

- Tạo lập: là tạo nên, lập nên. Ví dụ: Học sinh tạo lập được lục giác đều thông qua việc lắp ghép các tam giác đều.
- Hình học trực quan: Quá trình nhận thức hình học của trẻ em phải đi từ cụ thể đến trừu tượng, từ hình ảnh trực quan đến những kiến thức hình học đã được trừu tượng hoá, hình thức hoá. Ví dụ: Trong giai đoạn từ lớp 1 đến lớp 6, học sinh được làm quen với việc học hình học thông qua hình ảnh trực quan hoặc các dụng cụ trực quan (vật thật), không có yếu tố suy luận; học sinh lớp 7, lớp 8, lớp 9 cũng được học hình học không gian với cách tiếp cận này. Vì thế, hình học được giảng dạy trong giai đoạn đầu của tiến trình nhận thức hình học của học sinh được gọi là hình học trực quan. Khi dạy học hình học trực quan, giáo viên không nhất thiết yêu cầu học sinh suy luận, tránh gây áp lực không tốt lên học sinh, nhưng cũng có thể đề cập đến những kiến thức hình học đã được hình thức hoá nếu điều kiện nhận thức của học sinh cho phép.

### b. Từ ngữ thể hiện mức độ đáp ứng yêu cầu cần đạt

Chương trình môn Toán sử dụng một số động từ để thể hiện mức độ đáp ứng yêu cầu cần đạt của người học, được nêu trong bảng tổng hợp dưới đây. Một số động từ được sử dụng ở các mức độ khác nhau nhưng trong mỗi trường hợp thể hiện một hành động có đối tượng và yêu cầu cụ thể.

Trong quá trình dạy học, đặc biệt là khi đặt câu hỏi thảo luận, ra đề kiểm tra đánh giá, giáo viên có thể dùng những động từ nêu trong bảng tổng hợp hoặc thay thế bằng các động từ có nghĩa tương đương cho phù hợp với tình huống sư phạm và nhiệm vụ cụ thể giao cho học sinh.

<table>
    <thead>
        <tr>
            <th style="text-align: center">
                Mức độ
            </th>
            <th style="text-align: center">
                Một số động từ mô tả mức độ 
            </th>
            <th style="text-align: center">
                Ví dụ minh hoạ
            </th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>
                <strong><em>Biết</em></strong><br>
                (Nhận biết và nhớ lại các thông tin đã được tiếp nhận trước đó)
            </td>
            <td>
                Đọc;<br>
                Đếm;<br>
                Viết;<br>
                Làm quen;<br>
                Nhận dạng;<br>
                Nhận biết.
            </td>
            <td>
                <ul>
                    <li>
                        Đếm, đọc, viết được các số trong phạm vi 10.
                    </li>
                    <li>
                        Làm quen với dãy số tự nhiên và đặc điểm.
                    </li>
                    <li>
                        Nhận dạng được hình tứ giác thông qua việc sử dụng bộ đồ dùng học tập cá nhân hoặc vật thật.
                    </li>
                    <li>
                        Nhận biết được số đối của một số nguyên.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                <strong><em>Hiểu</em></strong><br>
                (Hiểu được ý nghĩa của thông tin, diễn đạt được thông tin theo ý hiểu của cá nhân)
            </td>
            <td>
                Mô tả;<br>
                Giải thích;<br>
                Thể hiện;<br>
                Sắp xếp.
            </td>
            <td>
                <ul>
                    <li>
                        Đọc và mô tả được các số liệu ở dạng bảng.
                    </li>
                    <li>
                        Giải thích được định lí về dấu của tam thức bậc hai từ việc quan sát đồ thị của hàm bậc hai.
                    </li>
                    <li>
                        Thể hiện được các số đo đại lượng bằng cách dùng số thập phân.
                    </li>
                    <li>
                        Sắp xếp được số liệu vào biểu đồ cột.
                    </li>
                </ul>
            </td>
        </tr>

        <tr>
            <td>
                <strong><em>Vận dụng</em></strong><br>
                (Vận dụng thông tin đã biết vào một tình huống, điều kiện mới hoặc để giải quyết vấn đề)
            </td>
            <td>
                Tính;<br>
                Vẽ;<br>
                Thực hiện;<br>
                Sử dụng;<br>
                Vận dụng;<br>
                So sánh;<br>
                Phân biệt;<br>
                Lí giải;<br>
                Chứng minh;<br>
                Giải quyết.
            </td>
            <td>
                <ul>
                    <li>
                        Tính được độ dài đường gấp khúc khi biết độ dài các cạnh.
                    </li>
                    <li>
                        Vẽ được đường cao của hình tam giác.
                    </li>
                    <li>
                        Thực hiện được phép cộng hai số nguyên.
                    </li>
                    <li>
                        Sử dụng được thuật ngữ tập hợp, phần tử thuộc (không thuộc) một tập hợp.
                    </li>
                    <li>
                        Vận dụng được kiến thức về phương trình mặt cầu để giải một số bài toán liên quan đến thực tiễn.
                    </li>
                    <li>
                        So sánh được hai phân số cho trước.
                    </li>
                    <li>
                        Phân biệt được góc nhị diện và góc giữa hai mặt phẳng.
                    </li>
                    <li>
                        Lí giải được cách chuyển dữ liệu từ dạng biểu diễn này sang dạng biểu diễn khác.
                    </li>
                    <li>
                        Chứng minh được tính đúng đắn của một mệnh đề toán học bằng phương pháp quy nạp toán học.
                    </li>
                    <li>
                        Giải quyết được một số vấn đề thực tiễn đơn giản liên quan đến hình phẳng và hình khối đã học.
                    </li>
                </ul>
            </td>
        </tr>
    </tbody>
</table>

## 2. Thời lượng thực hiện chương trình

### a. Thời lượng thực hiện chương trình ở các lớp

<table>
    <tr>
        <td style="text-align: center"><strong>Lớp</strong></td>
        <td style="text-align: center">Lớp 1</td>
        <td style="text-align: center">Lớp 2</td>
        <td style="text-align: center">Lớp 3</td>
        <td style="text-align: center">Lớp 4</td>
        <td style="text-align: center">Lớp 5</td>
        <td style="text-align: center">Lớp 6</td>
        <td style="text-align: center">Lớp 7</td>
        <td style="text-align: center">Lớp 8</td>
        <td style="text-align: center">Lớp 9</td>
        <td style="text-align: center">Lớp 10</td>
        <td style="text-align: center">Lớp 11</td>
        <td style="text-align: center">Lớp 12</td>
    </tr>
    <tr>
        <td style="text-align: center"><strong>Số tiết</strong></td>
        <td style="text-align: center">105</td>
        <td style="text-align: center">175</td>
        <td style="text-align: center">175</td>
        <td style="text-align: center">175</td>
        <td style="text-align: center">175</td>
        <td style="text-align: center">140</td>
        <td style="text-align: center">140</td>
        <td style="text-align: center">140</td>
        <td style="text-align: center">140</td>
        <td style="text-align: center">105</td>
        <td style="text-align: center">105</td>
        <td style="text-align: center">105</td>
    </tr>
</table>

Riêng ở cấp trung học phổ thông, mỗi lớp có thêm 35 tiết/năm học cho các chuyên đề học tập lựa chọn.

### b. Thời lượng dành cho các nội dung giáo dục

Ước lượng thời gian (tính theo %) cho các mạch nội dung ở từng lớp (không tính chuyên đề học tập) như sau:

<table>
    <thead>
        <tr>
            <th rowspan="2" colspan="2" style="text-align: center">
                Cấp học/Lớp
            </th>
            <th colspan="4" style="text-align: center">
                Mạch kiến thức
            </th>
        </tr>
        <tr>
            <th style="text-align: center">
                Số, Đại số và Một số yếu tố giải tích
            </th>
            <th style="text-align: center">
                Hình học và Đo lường
            </th>
            <th style="text-align: center">
                Thống kê và Xác suất
            </th>
            <th style="text-align: center">
                Hoạt động thực hành và trải nghiệm
            </th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td rowspan="6" style="text-align: center">
                Tiểu học
            </td>
            <td style="text-align: center">
                1
            </td>
            <td style="text-align: center">
                80%
            </td>
            <td style="text-align: center">
                15%
            </td>
            <td style="text-align: center">
                0%
            </td>
            <td style="text-align: center">
                5%
            </td>
        </tr>

        <tr>
            <td style="text-align: center">
                2
            </td>
            <td style="text-align: center">
                75%
            </td>
            <td style="text-align: center">
                17%
            </td>
            <td style="text-align: center">
                3%
            </td>
            <td style="text-align: center">
                5%
            </td>
        </tr>

        <tr>
            <td style="text-align: center">
                3
            </td>
            <td style="text-align: center">
                70%
            </td>
            <td style="text-align: center">
                22%
            </td>
            <td style="text-align: center">
                3%
            </td>
            <td style="text-align: center">
                5%
            </td>
        </tr>

        <tr>
            <td style="text-align: center">
                4
            </td>
            <td style="text-align: center">
                75%
            </td>
            <td style="text-align: center">
                16%
            </td>
            <td style="text-align: center">
                4%
            </td>
            <td style="text-align: center">
                5%
            </td>
        </tr>

        <tr>
            <td style="text-align: center">
                5
            </td>
            <td style="text-align: center">
                50%
            </td>
            <td style="text-align: center">
                40%
            </td>
            <td style="text-align: center">
                5%
            </td>
            <td style="text-align: center">
                5%
            </td>
        </tr>

        <tr>
            <td style="text-align: center">
                Toàn cấp
            </td>
            <td style="text-align: center">
                69%
            </td>
            <td style="text-align: center">
                23%
            </td>
            <td style="text-align: center">
                3%
            </td>
            <td style="text-align: center">
                5%
            </td>
        </tr>

        <tr>
            <td rowspan="5" style="text-align: center">
                Trung học cơ sở 
            </td>
            <td style="text-align: center">
                6
            </td>
            <td style="text-align: center">
                49%
            </td>
            <td style="text-align: center">
                30%
            </td>
            <td style="text-align: center">
                14%
            </td>
            <td style="text-align: center">
                7%
            </td>
        </tr>

        <tr>
            <td style="text-align: center">
                7
            </td>
            <td style="text-align: center">
                43%
            </td>
            <td style="text-align: center">
                36%
            </td>
            <td style="text-align: center">
                14%
            </td>
            <td style="text-align: center">
                7%
            </td>
        </tr>

        <tr>
            <td style="text-align: center">
                8
            </td>
            <td style="text-align: center">
                43%
            </td>
            <td style="text-align: center">
                36%
            </td>
            <td style="text-align: center">
                14%
            </td>
            <td style="text-align: center">
                7%
            </td>
        </tr>

        <tr>
            <td style="text-align: center">
                9
            </td>
            <td style="text-align: center">
                43%
            </td>
            <td style="text-align: center">
                36%
            </td>
            <td style="text-align: center">
                14%
            </td>
            <td style="text-align: center">
                7%
            </td>
        </tr>

        <tr>
            <td style="text-align: center">
                Toàn cấp
            </td>
            <td style="text-align: center">
                43%
            </td>
            <td style="text-align: center">
                36%
            </td>
            <td style="text-align: center">
                14%
            </td>
            <td style="text-align: center">
                7%
            </td>
        </tr>

        <tr>
            <td rowspan="4" style="text-align: center">
                Trung học phổ thông
            </td>
            <td style="text-align: center">
                10
            </td>
            <td style="text-align: center">
                44%
            </td>
            <td style="text-align: center">
                35%
            </td>
            <td style="text-align: center">
                14%
            </td>
            <td style="text-align: center">
                7%
            </td>
        </tr>

        <tr>
            <td style="text-align: center">
                11
            </td>
            <td style="text-align: center">
                44%
            </td>
            <td style="text-align: center">
                35%
            </td>
            <td style="text-align: center">
                14%
            </td>
            <td style="text-align: center">
                7%
            </td>
        </tr>

        <tr>
            <td style="text-align: center">
                12
            </td>
            <td style="text-align: center">
                44%
            </td>
            <td style="text-align: center">
                35%
            </td>
            <td style="text-align: center">
                14%
            </td>
            <td style="text-align: center">
                7%
            </td>
        </tr>

        <tr>
            <td style="text-align: center">
                Toàn cấp
            </td>
            <td style="text-align: center">
                44%
            </td>
            <td style="text-align: center">
                35%
            </td>
            <td style="text-align: center">
                14%
            </td>
            <td style="text-align: center">
                7%
            </td>
        </tr>

        <tr>
            <td colspan="2" style="text-align: center">
                <strong>
                    Toàn bộ chương trình
                </strong>
            </td>
            <td style="text-align: center">
                <strong>
                    44%
                </strong>
            </td>
            <td style="text-align: center">
                <strong>
                    35%
                </strong>
            </td>
            <td style="text-align: center">
                <strong>
                    14%
                </strong>
            </td>
            <td style="text-align: center">
                <strong>
                    7%
                </strong>
            </td>
        </tr>
    </tbody>
</table>

## 3. Thiết bị dạy học

a. Thiết bị dạy học môn Toán chứa đựng, mô tả những tri thức có khả năng hỗ trợ giáo viên và hỗ trợ học sinh hướng vào đối tượng toán học cụ thể (khái niệm, quan hệ, tính chất toán học,...) nhằm phát hiện, tìm tòi, khắc sâu kiến thức,... trong quá trình học tập môn Toán.
b. Việc sử dụng thiết bị dạy học môn Toán cần bảo đảm một số yêu cầu sau:
    - Các thiết bị dạy học phải phục vụ cho mục tiêu dạy học môn Toán, phù hợp với nội dung học và các đối tượng học sinh, hỗ trợ đổi mới phương pháp dạy học và tránh làm tăng thêm nội dung dạy học, công việc của giáo viên và gây tốn kém không cần thiết.
    - Sử dụng đúng lúc, đúng chỗ, tránh hình thức hoặc lạm dụng gây phản tác dụng, làm giảm hiệu quả của quá trình dạy học; tạo điều kiện để học sinh thực sự được thực hành, thao tác trên các thiết bị dạy học, qua đó giúp học sinh chủ động, tích cực khám phá, phát hiện kiến thức và góp phần phát triển "năng lực sử dụng công cụ, phương tiện học toán".
    - Khuyến khích sử dụng các phương tiện nghe nhìn, phương tiện kĩ thuật hiện đại hỗ trợ quá trình dạy học, đồng thời     coi trọng việc sử dụng các phương tiện truyền thống. Khi có điều kiện, giáo viên hướng dẫn học sinh cách tìm kiếm thông tin, tư liệu trên Internet hoặc chương trình truyền hình có uy tín về giáo dục để mở rộng vốn hiểu biết và năng lực tự học.
    - Tăng cường thiết bị dạy học tự làm: Ngoài các thiết bị dạy học tối thiểu được quy định trong danh mục do Bộ Giáo dục và Đào tạo ban hành cần huy động sáng kiến, sự sáng tạo của học sinh, giáo viên và phụ huynh trong việc khai thác, thiết kế và sử dụng các thiết bị dạy học tự làm.
    - Phối hợp sử dụng linh hoạt các loại hình thiết bị dạy học: Mỗi loại hình thiết bị đều có ưu điểm và hạn chế nhất định, do đó tùy thuộc nội dung bài học, phương pháp dạy học mà có thể kết hợp sử dụng các loại hình thiết bị dạy học và phối hợp một cách hợp lí, khoa học và sinh động.
c. Căn cứ mục tiêu và yêu cầu cần đạt của chương trình môn Toán, Bộ Giáo dục và Đào tạo ban hành danh mục thiết bị dạy học tối thiểu, bảo đảm đủ về số lượng và chủng loại. Cụ thể:
    - Cấp tiểu học:
        - Số và Phép tính: Gồm các bộ thiết bị dạy học về Số tự nhiên và các phép tính (cộng, trừ, nhân, chia) với số tự nhiên; Phân số và các phép tính (cộng, trừ, nhân, chia) với phân số; Số thập phân và Các phép tính về số thập phân; Tỉ số phần trăm.
        - Hình học và Đo lường: Gồm các bộ thiết bị dạy học về nhận biết, mô tả hình dạng và đặc điểm của một số hình phẳng và hình khối; thực hành đo, vẽ, lắp ghép, tạo hình (tương ứng với chương trình môn Toán mỗi lớp); thực hành cân, đo, đong, đếm, xem thời gian, mua bán.
        - Một số yếu tố thống kê và xác suất: Gồm các bộ thiết bị dạy học về Đọc, mô tả, biểu diễn số liệu vào các bảng, biểu đồ thống kê; làm quen với khả năng xảy ra của một sự kiện.
    - Cấp trung học cơ sở:
        + Số và Đại số: Gồm các bộ thiết bị dạy học về Số nguyên và Các phép tính với số nguyên; Tỉ số phần trăm; Hàm số và đồ thị.
        + Hình học và Đo lường: Bộ thiết bị dạy học về nhận biết, mô tả hình dạng và đặc điểm của một số hình phẳng và hình khối; về thực hành đo, vẽ, tạo hình gắn với các hình phẳng và hình khối đã học.
        + Một số yếu tố Thống kê và Xác suất: Bộ thiết bị dạy học về Thống kê và Xác suất.
    - Cấp trung học phổ thông:
        + Đại số và Một số yếu tố giải tích: Bộ thiết bị dạy và học về Hàm số và đồ thị.
        + Hình học và Đo lường: Bộ thiết dạy học về Nhận biết, mô tả hình dạng và đặc điểm hình chóp, hình lăng trụ, hình nón, hình cầu, hình trụ, các đường cônic.
        + Thống kê và Xác suất: Bộ thiết bị dạy học về Thống kê và Xác suất.


---

# Yêu cầu cần đạt ở cấp trung học phổ thông

Được diễn giải theo tinh thần của ZO Math: *chúng ta phải làm gì nếu muốn ZO Math thực sự đồng hành cùng chương trình Toán quốc gia.*

## ZO Math và yêu cầu cần đạt của môn Toán cấp THPT

Ở bậc trung học phổ thông, mục tiêu của môn Toán không chỉ là nắm được công thức hay phương pháp giải, mà là hình thành một năng lực toán học toàn diện - tức là khả năng tư duy, mô hình hóa, giải quyết vấn đề, giao tiếp và sử dụng công cụ một cách chủ động, sáng tạo. ZO Math có thể xem đây như là năm hướng phát triển cốt lõi mà mỗi bài học, mỗi hoạt động, mỗi dự án đều cần chạm tới ít nhất một trong số đó.

### 1. Tư duy và lập luận toán học

Học sinh THPT cần biết phân tích và so sánh những tình huống phức tạp, biết tìm ra mối liên hệ ẩn sau các con số, biểu thức và đồ thị, và đặc biệt là có thể chứng minh, phản biện và tự điều chỉnh lập luận của mình. ZO Math vì vậy phải dạy Toán như dạy cách suy nghĩ. Các bài học nên có những đoạn đối thoại, những tình huống mở nơi học sinh phải tự hỏi "tại sao" và "có thể khác đi không?". Những bài luận, chuyên đề, hay phần bình giải của ZO Math không nên chỉ cho lời giải, mà nên phơi bày cả con đường đi tới lời giải ấy - cả sự do dự, kiểm chứng, và điều chỉnh lập luận.

### 2. Mô hình hoá toán học

Khi học sinh biết dùng công thức, phương trình, đồ thị để mô tả và lý giải hiện tượng đời sống - từ quãng đường xe chạy, sự lan truyền của tin tức, đến chi phí sản xuất hay tốc độ tăng trưởng - Toán học trở thành một ngôn ngữ sống. ZO Math nên nuôi dưỡng khả năng đó bằng các hoạt động khám phá và bài toán có bối cảnh thực. Mỗi chủ đề nên có ít nhất một "cửa sổ thực tiễn" - một tình huống thật để học sinh tự đặt mô hình, tự tính, rồi so sánh kết quả với đời. Không chỉ dừng ở việc ra bài tập, ZO Math cần kể lại cách người học chuyển một hiện tượng cụ thể thành mô hình toán học, và ngược lại, kiểm chứng ý nghĩa thực tế của kết quả.

### 3. Giải quyết vấn đề toán học

Ở bậc THPT, học sinh cần biết đặt câu hỏi, chọn hướng đi, tự tổ chức các bước giải quyết vấn đề, và quan trọng hơn là biết đánh giá giá trị của lời giải. Đây là năng lực của người tự học và người sáng tạo.
ZO Math có thể phát triển mảng này bằng những bài toán mở và những chuyên đề có nhiều cách tiếp cận. Trong đó, thay vì khẳng định "đáp án đúng là...", trang nên khuyến khích học sinh thử nghiệm, phản biện, và rút ra quy luật. Các chuyên mục như "Bài toán mở rộng", "Giải theo nhiều cách", hay "Sai ở đâu?" sẽ giúp rèn luyện chính xác năng lực này.

### 4. Giao tiếp toán học

Học sinh cần hiểu, nói, viết và thuyết phục bằng ngôn ngữ toán học kết hợp ngôn ngữ tự nhiên. Khi một học sinh có thể diễn đạt mạch lạc lý do tại sao đạo hàm mang dấu âm, hoặc vì sao đồ thị có cực trị, lúc đó em không chỉ học Toán - em đang làm Toán. ZO Math có thể tạo ra môi trường giao tiếp toán học thông qua lời bình, bài viết, video, hoặc diễn đàn. Trong mỗi bài giảng, phần diễn giải phải rõ ràng, mềm mại và có cảm xúc, để học sinh thấy rằng trình bày Toán học cũng là một nghệ thuật. Những bài học nên khuyến khích người học "viết lại theo cách của mình", "giải thích cho người khác", hay "đưa ra phản biện hợp lý" - đó chính là giao tiếp toán học sống động nhất.

### 5. Sử dụng công cụ và phương tiện học Toán

Ở thời đại này, người học không thể tách khỏi công nghệ. Họ cần biết sử dụng máy tính, phần mềm, mô phỏng, dữ liệu và Internet như những người bạn đồng hành trong việc khám phá Toán. ZO Math nên biến phần này thành lợi thế của mình. Mỗi bài học, mỗi chuyên đề có thể gắn với một công cụ cụ thể: GeoGebra để vẽ đồ thị, Python để mô phỏng dữ liệu, hoặc ứng dụng Shiny để học sinh tự thao tác. Trang web của ZO Math nên trở thành "phòng thí nghiệm toán học trực tuyến", nơi học sinh không chỉ đọc mà còn bấm, kéo, thử và quan sát.

### Kết luận

Nếu ZO Math muốn tham gia thực chất vào Chương trình giáo dục phổ thông môn Toán, dự án cần định vị mình như một *hệ sinh thái hỗ trợ năng lực toán học hiện đại*. Mỗi nội dung, dù là bài học, hoạt động khám phá hay bài tập, đều nên hướng đến việc làm rõ ít nhất một năng lực cốt lõi ở cấp THPT; khơi gợi tư duy phản biện, tính mô hình, khả năng giải quyết vấn đề, năng lực diễn đạt và thói quen sử dụng công cụ hiện đại.

Nói cách khác, nhiệm vụ của ZO Math không chỉ là dạy Toán, mà là *rèn luyện cách tư duy bằng Toán*, để học sinh bước ra khỏi lớp học vẫn giữ trong mình năng lực phân tích, suy luận và sáng tạo - những phẩm chất mà chương trình quốc gia mong muốn, và mà ZO Math có thể hiện thực hóa theo cách sinh động, tự nhiên và đầy sức sống.

---

# Chuyển tri thức thành chiến lược hành động

Bảng dưới đây mình biên soạn như một *"Bảng ghi nhớ chiến lược ZO Math - Đồng hành & Dẫn dắt Chương trình Toán THPT"*, kết hợp cả ba mục tiêu bạn đã đặt ra:

* Bám sát *chương trình quốc gia*;
* Vượt qua bằng *giải pháp sáng tạo và công nghệ*;
* Hướng đến *tự chủ nghề nghiệp và sứ mệnh chấn hưng giáo dục*.

## Bảng ghi nhớ chiến lược ZO Math

### Đồng hành - Vượt qua - Dẫn đầu Chương trình Toán Trung học Phổ thông

| **Trục chương trình quốc gia**                                                                                                                     | **Tinh thần / mục tiêu của Bộ GD&ĐT**                                                      | **Hành động chiến lược ZO Math**                                                                                                                                                                                                                                                                                                  | **Ý nghĩa dài hạn**                                                                                      |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------- |
| **1. Cấu trúc nội dung (3 mạch lớn)**<br>• Đại số & Giải tích<br>• Hình học & Đo lường<br>• Thống kê & Xác suất                                    | Trang bị nền tảng toán học hiện đại, tăng tính ứng dụng và gắn thực tiễn.                  | 🔹 Xây dựng 3 **Trục học tập chính** của ZO Math song song với chương trình quốc gia.<br>🔹 Mỗi trục có "chuỗi bài học xuyên suốt" giúp học sinh hiểu sâu và kết nối liên mạch qua các lớp.<br>🔹 Phát triển thêm "mạch thứ tư": **Toán học và Cuộc sống** (ứng dụng tài chính, dữ liệu, mô hình hóa).                            | Giúp ZO Math trở thành hệ thống học tập song hành - tự nhiên bổ trợ, không cạnh tranh với trường học.    |
| **2. Mạch chuyên đề lựa chọn (35 tiết/năm)**                                                                                                       | Cho phép học sinh chọn học Toán theo hướng nghề nghiệp hoặc hứng thú.                      | 🔹 Tạo bộ **ZO Math Electives**: chuyên đề mở rộng như "Đạo hàm và tối ưu", "Toán - Kinh tế - Đầu tư", "Thống kê dữ liệu thật", "Đồ họa và phép biến hình", "Python trong Toán học".<br>🔹 Triển khai online qua **ZO Math Studio / Lab**.                                                                                        | ZO Math trở thành "nhà cung cấp chuyên đề mở rộng" cho hệ thống giáo dục phổ thông.                      |
| **3. Phương pháp dạy học**                                                                                                                         | Học sinh là trung tâm - học qua kiến tạo, trải nghiệm và công nghệ.                        | 🔹 Chuẩn hóa mô hình **"Làm - Soi - Học"** tương ứng với ba mức "Biết - Hiểu - Vận dụng".<br>🔹 Mỗi bài học gồm: Hoạt động khám phá → Phân tích → Vận dụng thực tiễn.<br>🔹 Tích hợp **GeoGebra, Shiny, Quarto interactive, Python-Plot, TikZ** làm "thiết bị học tập số".                                                        | ZO Math trở thành mô hình **"Phòng thí nghiệm học Toán số hóa"**, nơi học sinh tự kiến tạo tri thức.     |
| **4. Phát triển năng lực toán học (5 năng lực đặc thù)**<br>• Lập luận<br>• Mô hình hóa<br>• Giải quyết vấn đề<br>• Giao tiếp<br>• Sử dụng công cụ | Chuyển trọng tâm từ "học đúng" sang "học có năng lực thực hành toán".                      | 🔹 Gắn từng bài học ZO Math với ít nhất một năng lực trọng tâm.<br>🔹 Tạo **Bộ rubric đánh giá năng lực Toán học** (ví dụ: mô hình hóa, lập luận, giao tiếp).<br>🔹 Cho phép học sinh nộp sản phẩm học tập (mô hình, đồ thị, video, phản chiếu cá nhân).                                                                          | Tạo ra **hệ đánh giá dựa trên năng lực** có thể dùng trong nhà trường và ngoài nhà trường.               |
| **5. Đánh giá kết quả học tập**                                                                                                                    | Đánh giá quá trình - năng lực - sản phẩm, thay cho kiểm tra ghi nhớ.                       | 🔹 Mỗi bài học ZO Math kết thúc bằng **"Sản phẩm học tập"** (project nhỏ, mô hình, hình minh họa, file tương tác).<br>🔹 Áp dụng **peer-assessment** (học sinh đánh giá lẫn nhau) và **self-reflection** (tự soi).<br>🔹 Xây dựng **dashboard năng lực cá nhân** cho học sinh.                                                    | Biến việc học Toán thành quá trình phát triển năng lực tự thân, không còn là áp lực điểm số.             |
| **6. Thiết bị & phương tiện dạy học**                                                                                                              | Khuyến khích thiết bị hiện đại, học sinh được thao tác thật, sáng tạo, tiết kiệm.          | 🔹 Phát triển hệ **ZO Lab**: bộ mô phỏng, ứng dụng Shiny, video minh họa, mô hình 3D tự làm.<br>🔹 Cung cấp **"ZO Toolkit for Teachers"** - tài nguyên số giúp giáo viên đổi mới phương pháp trong trường phổ thông.<br>🔹 Hướng dẫn học sinh **"Tự chế thiết bị học toán số"** (ví dụ: mini mô phỏng bằng Python hoặc GeoGebra). | ZO Math trở thành **nhà cung cấp thiết bị học tập số và sư phạm mở** cho giáo viên và học sinh.          |
| **7. Thời lượng & cân đối nội dung (44-35-14-7)**                                                                                                  | Bảo đảm sự hài hòa giữa giải tích, hình học, thống kê, trải nghiệm.                        | 🔹 Giữ tỉ lệ tương tự trong ZO Math nhưng **mở rộng mạnh phần Thống kê - Xác suất - Trải nghiệm**.<br>🔹 Tạo **cầu nối dữ liệu - đời sống - mô hình hóa** (phân tích dữ liệu thực, khảo sát hàm chi phí, đo đạc hình học thực tiễn).                                                                                              | Giúp học sinh nhìn Toán như "khoa học của thế giới thật" - không chỉ là bài kiểm tra.                    |
| **8. Giải thích và hướng dẫn (ngôn ngữ chương trình)**                                                                                             | Chuẩn hóa động từ "biết - hiểu - vận dụng" và tinh thần "trực quan - suy luận - ứng dụng". | 🔹 Viết lại mọi mục tiêu bài học ZO Math bằng **ngôn ngữ năng lực** (VD: "Hiểu được", "Vận dụng để", "Giải thích tại sao").<br>🔹 Mỗi bài đều có **hình minh họa hoặc mô phỏng trực quan** trước khi đi vào lý thuyết.                                                                                                            | Làm cho tài liệu ZO Math tương thích 100% với chương trình quốc gia - có thể dùng ngay trong trường học. |

## Tầm nhìn hành động ba gia đoạn của ZO Math

| **Giai đoạn** | **Trọng tâm**                                                            | **Sản phẩm tiêu biểu**                                                                  | **Tác động xã hội - nghề nghiệp**                                                |
| ------------- | ------------------------------------------------------------------------ | --------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| **2025-2026** | Bám sát chương trình - chuẩn hóa bài học tương tác.                      | "Sổ tay kiến thức Toán THPT" & "Thực hành Toán phổ thông" (web + in).                   | Khẳng định ZO Math như một nền tảng học Toán hiện đại, đáng tin cậy.             |
| **2026-2027** | Mở rộng chuyên đề - xây dựng ZO Lab - hệ đánh giá năng lực.              | "ZO Lab" (ứng dụng mô phỏng Shiny, GeoGebra, Python) & "ZO Assessment Kit".             | Trở thành đối tác hỗ trợ giáo viên và trường học trong đổi mới giáo dục.         |
| **2027-2029** | Dẫn đầu thời đại chấn hưng giáo dục - đào tạo thế hệ "người học tự chủ". | "ZO Math School" (mô hình học kết hợp trực tuyến - thực nghiệm), CLB học Toán sáng tạo. | Tạo hệ sinh thái tự duy trì, vừa mang giá trị xã hội vừa mang thu nhập bền vững. |

## Lời kết từ bảng ghi nhớ

ZO Math không cần chạy theo chương trình mà chỉ cần *đi cùng tinh thần của nó*, và *đi trước một bước* bằng cách:

> biến Toán học từ "nội dung" thành "trải nghiệm sống".

Khi ấy, ZO Math không chỉ là một dự án dạy học, mà là *một phần của phong trào chấn hưng giáo dục Việt Nam* - nơi thầy và trò cùng sáng tạo, cùng nuôi sống bản thân bằng tri thức, và cùng mở đường cho thời đại mới của học tập tự do.

---

Mình hiểu bạn đang muốn kiểm tra hai điều cùng lúc: (1) đã "nắm trọn" Chương trình Toán THPT chưa, đặc biệt những gì thật sự chi phối cách dạy-học ở trường; và (2) ZO Math phải làm gì-rất cụ thể, có thể triển khai ngay-để vừa bám sát chương trình, vừa đi trước một bước, đủ sức sống bằng sản phẩm/dịch vụ thực sự hữu ích cho nhà trường, giáo viên, học sinh và phụ huynh. Bạn không cần một bản nhắc lại rời rạc; bạn cần một bức tranh tổng hợp, nêu đúng "điểm đau-điểm hay-điểm bứt phá", rồi quy về một đường đi khả thi.

Dưới đây là bản cô đọng, theo đúng tinh thần bạn đã dẫn dắt phiên làm việc: đọc kĩ chương trình, chỉ tập trung THPT, giải nghĩa-đánh giá-chuyển hóa thành hành động của ZO Math, viết mạch lạc, ít liệt kê.

# Bạn đang cần gì (mình đọc được qua cả phiên trao đổi)

Bạn cần một đối tác tư duy để biến văn bản chương trình thành mô hình vận hành: dạy cái gì, dạy thế nào, đánh giá ra sao, dùng công cụ gì, và ZO Math phải "bán" được giá trị nào cho hệ sinh thái giáo dục. Bạn muốn an tâm rằng mọi đề xuất đều ăn khớp với: cấu trúc nội dung lớp 10-11-12, tinh thần dạy học kiến tạo lấy học sinh làm trung tâm, đánh giá theo năng lực, và 35 tiết/năm chuyên đề tự chọn. Bạn cũng muốn câu trả lời đi thẳng vào việc: ZO Math nên sản xuất sản phẩm gì, tổ chức trải nghiệm học tập thế nào, cung cấp công cụ nào cho giáo viên, và chọn chỉ số thành công ra sao để vừa có tác động, vừa bền vững.

# Chương trình THPT-những chốt then chốt cần nắm

Về nội dung, toàn bộ THPT xoay quanh ba mạch: Đại số & một số yếu tố giải tích; Hình học & Đo lường; Thống kê & Xác suất. Tỉ trọng được cố định (44% - 35% - 14% - 7% thực hành/trải nghiệm), thời lượng mỗi khối 105 tiết/năm cộng 35 tiết chuyên đề lựa chọn. Cái "mới" của chương trình không chỉ là đề mục kiến thức, mà là cách nhìn: phát triển 5 năng lực toán học (lập luận, mô hình hoá, giải quyết vấn đề, giao tiếp, sử dụng công cụ), coi trọng ứng dụng liên môn và thực tiễn; ưu tiên dạy học kiến tạo, trực quan-rồi-suy luận; khuyến khích thiết bị dạy học hiện đại và thiết bị tự làm; đánh giá chủ yếu theo năng lực, bằng chứng, sản phẩm, quá trình.

Nói gọn: đây là một chương trình "có cổng vào bằng trực quan-trải nghiệm", "đi bằng năng lực", và "ra bằng sản phẩm/ứng dụng". Nhà trường rất cần tài nguyên, công cụ và quy trình để biến tinh thần đó thành giờ học cụ thể.

# ZO Math-mảnh ghép ăn khớp và điểm vượt lên

Từ những gì chúng ta cùng xây: ZO Math đã hình thành "khung sư phạm" hợp với chương trình: dẫn nhập trực quan, thao tác-khám phá, rồi mới khái quát-chứng minh; và luôn chốt bằng ứng dụng. Mô hình "Làm - Soi - Học" bạn đang dùng tương ứng đẹp với "Biết - Hiểu - Vận dụng" của chương trình. Thêm nữa, ZO Math có lợi thế về công nghệ (GeoGebra/JS, Python/Shiny, TikZ, dashboard) - đúng tinh thần "thiết bị dạy học hiện đại và tự làm" mà Bộ khuyến khích. Điểm còn thiếu hiện nay là một gói sản phẩm-dịch vụ đóng gói "chuẩn trường học": bám mục tiêu từng bài/chủ đề, có rubric năng lực, có kế hoạch 35 tiết chuyên đề, có tài liệu giáo viên, có bằng chứng đánh giá, có cách tích hợp vào phân phối chương trình thực tế.

# Bạn thật sự cần ZO Math làm gì ngay bây giờ

Một là, chuẩn hoá nội dung cốt lõi theo lớp 10-11-12 dưới dạng chuỗi bài học tương tác, mỗi bài đều ghi rõ mục tiêu theo ngôn ngữ năng lực (biết-hiểu-vận dụng), bước hoạt động (trực quan-phân tích-ứng dụng), sản phẩm học tập và tiêu chí đánh giá. Hai là, tạo bộ chuyên đề 35 tiết/năm có thể "plug-and-play" cho trường: Toán-Tài chính cá nhân; Đạo hàm và tối ưu thực tiễn; Thống kê dữ liệu thật; Phép biến hình & đồ họa; Toán mũ-log trong tăng trưởng. Ba là, phát triển "ZO Toolkit for Teachers": giáo án gợi ý, slide, phiếu học tập, mô phỏng sẵn, rubric đánh giá 5 năng lực, ngân hàng câu hỏi theo mức độ. Bốn là, dựng "ZO Lab": kho mô phỏng/ứng dụng số như một dạng "thiết bị dạy học" để giờ học có phần thao tác thật chứ không chỉ trình chiếu. Năm là, chuẩn định dạng đánh giá theo năng lực: mỗi chủ đề gắn một sản phẩm (mô hình, báo cáo dữ liệu, bài toán tối ưu, video giải thích), có checklist minh chứng, có hướng dẫn tự đánh giá và đánh giá đồng đẳng. Sáu là, chuẩn hoá lộ trình làm việc với trường: cách lồng ghép vào 105 tiết chính khoá và 35 tiết chuyên đề; cách huấn luyện nhanh giáo viên; cách chứng minh hiệu quả (dashboard tiến bộ, tỷ lệ hoàn thành sản phẩm).

# Một lộ trình ngắn gọn nhưng đủ lực

Trong 8-12 tuần đầu, bạn có thể hoàn thành một "gói mẫu" dùng được ngay ở lớp 10 rồi nhân rộng. Gói này nên gồm: chuỗi Hàm bậc hai & Parabol (đủ trực quan-đồ thị-ứng dụng); Bất phương trình/hệ bất phương trình bậc nhất hai ẩn (miền nghiệm & bài toán tuyến tính đơn giản); Hệ thức lượng & vectơ (liên hệ Vật lí); Thống kê cơ bản lớp 10 (số gần đúng, sai số, số đo trung tâm/phân tán) với dữ liệu thật; một chuyên đề 35 tiết "Toán & Tài chính cá nhân" đóng gói trọn vẹn. Tất cả đều có mô phỏng, sản phẩm học tập, rubric, tài liệu giáo viên. Khi "gói mẫu lớp 10" chạy ổn, mở rộng đồng thời hai nhánh: chuyên đề lớp 11-12 và mạch Giải tích 11-12 (giới hạn-liên tục, đạo hàm, khảo sát đồ thị, nguyên hàm-tích phân, phương pháp toạ độ không gian), vẫn giữ triết lí trực quan-mô hình-ứng dụng.

# Vì sao cách làm này vừa "bám sát" vừa "vượt qua"

Bám sát vì mọi bài, mọi chuyên đề đều gắn mục tiêu-yêu cầu cần đạt đúng ngôn ngữ chương trình, đủ ba mức "biết-hiểu-vận dụng", đúng tỉ trọng mạch kiến thức, đúng hình thức đánh giá theo năng lực. Vượt qua vì ZO Math không dừng ở giải tập mà xây dựng trải nghiệm số có thao tác thực, dữ liệu thật, bài toán bối cảnh, sản phẩm học tập; đưa học sinh vào mô hình hoá, giao tiếp toán học, và sử dụng công cụ số-điểm mà trường công lập đang còn thiếu nguồn lực. Cũng vượt qua vì ZO Math tạo ra chuyên đề liên môn-nghề nghiệp có thể triển khai ngay, giúp nhà trường lấp đúng "khoảng trống 35 tiết" một cách chất lượng.

# Bạn có thể dùng gì làm thước đo thành công

Những chỉ số phù hợp với tinh thần chương trình: tỷ lệ học sinh hoàn thành sản phẩm học tập theo rubric năng lực; mức tăng độ chính xác khi làm việc với số gần đúng-sai số; khả năng đọc-lập bảng/biểu đồ và rút kết luận đúng; tỷ lệ bài toán mô hình hoá giải trọn vẹn (đặt mô hình-giải-diễn giải kết quả); chất lượng báo cáo tối ưu hóa dùng đạo hàm; số giờ học có thao tác thật trên "thiết bị số"; mức độ hài lòng-tự chủ của giáo viên khi dùng Toolkit. Về mặt nghề nghiệp: số trường tích hợp 35 tiết chuyên đề ZO Math; tỷ lệ tái kí hợp đồng theo năm; chi phí phục vụ một lớp giảm dần theo quy mô nhờ tài nguyên số; biên lợi nhuận duy trì ở mức lành mạnh mà không hy sinh chất lượng.

# Kết lại: mình hiểu bạn đang muốn nói điều này

Bạn muốn ZO Math trở thành cầu nối giữa "văn bản chương trình" và "giờ học sống động có tác dụng thật", để khi làn sóng đổi mới lan rộng, ZO Math đã sẵn sàng bộ giải pháp đầy đủ: nội dung-phương pháp-đánh giá-thiết bị-chuyên đề-chỉ số thành công. Bạn muốn một con đường rõ ràng, có thể đi ngay, và đủ chiều sâu học thuật để không rơi vào dạy mẹo; đủ chiều rộng ứng dụng để học sinh, phụ huynh, nhà trường thấy giá trị; đủ tính hệ thống để trở thành một "hạ tầng" dạy-học Toán mới.

Nếu bạn muốn, mình sẽ viết ngay bộ "khung triển khai lớp 10 trong 10 tuần" theo đúng định dạng dùng được ở trường: mục tiêu theo năng lực, phân phối bài-tiết, kịch bản giờ học, mô phỏng đính kèm, sản phẩm học tập và rubric, cùng một chuyên đề 35 tiết mẫu. Chỉ cần bạn nói "làm bộ lớp 10 trước", mình sẽ đưa trọn gói ngay trong trả lời kế tiếp.










