---
title: "ĐÁNH SỐ BÀI HỌC TRÊN YOUTUBE CỦA SÁCH TOÁN PHỔ THÔNG"
output:
  html_notebook: default
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
---

# LỚP 10

## BỘ CHÂN TRỜI SÁNG TẠO

PHẦN ĐẠI SỐ VÀ MỘT SỐ YẾU TỐ GIẢI TÍCH

1. Chương I. MỆNH ĐỀ VÀ TẬP HỢP
2. Bài 1. Mệnh đề
3. Bài tập Bài 1
4. Bài 2. Tập hợp
5. Bài tập Bài 2
6. Bài 3. Các phép toán trên tập hợp
7. Bài tập Bài 3
8. Bài tập cuối chương I 

9. Chương II. BẤT PHƯƠNG TRÌNH VÀ HỆ BẤT PHƯƠNG TRÌNH BẬC NHẤT HAI ẨN
10. Bài 1. Bất phương trình bậc nhất hai ẩn
11. Bài tập Bài 1
12. Bài 2. Hệ bất phương trình bậc nhất hai ẩn
13. Bài tập Bài 2
14. Bài tập cuối chương II

15. Chương III. HÀM SỐ BẬC HAI VÀ ĐỒ THỊ
16. Bài 1. Hàm số và đồ thị
17. Bài tập Bài 1
18. Bài 2. Hàm số bậc hai
19. Bài tập Bài 2
20. Bài tập cuối chương III

PHẦN HÌNH HỌC VÀ ĐO LƯỜNG

21. Chương IV. HỆ THỨC LƯỢNG GIÁC TRONG TAM GIÁC 
22. Bài 1. Giá trị lượng giác của một góc từ $0^\circ$ đến $180^\circ$
23. Bài tập Bài 1
24. Bài 2. Định lí cô-sin và định lí sin
25. Bài tập Bài 2
26. Bài 3. Giải tam giác và ứng dụng thực tế
27. Bài tập Bài 3
28. Bài tập cuối chương IV

29. Chương V. VÉC-TƠ
30. Bài 1. Khái niệm véc-tơ
31. Bài tập Bài 1
32. Bài 2. Tổng và hiệu của hai véc-tơ
33. Bài tập Bài 2
34. Bài 3. Tích của một số với một véc-tơ
35. Bài tập Bài 3
36. Bài 4. Tích vô hướng của hai véc-tơ
37. Bài tập Bài 4
38. Bài tập cuối chương V

PHẦN THỐNG KÊ VÀ XÁC SUẤT 

39. Chương VI. THỐNG KÊ
40. Bài 1. Số gần đúng và sai số
41. Bài tập Bài 1
42. Bài 2. Mô tả và biểu diễn dữ liệu trên các bảng và biểu đồ
43. Bài tập Bài 2
44. Bài 3. Các số đặc trưng đo xu thế trung tâm của mẫu số liệu
45. Bài tập Bài 3
46. Bài 4. Các số đặc trưng đo mức độ phân tán của mẫu số liệu
47. Bài tập Bài 4
48. Bài tập cuối chương VI

HOẠT ĐỘNG THỰC HÀNH VÀ TRẢI NGHIỆM

49. Bài 1. Dùng máy tính cầm tay để tính toán với số gần đúng và tính các số đặc trưng của mẫu số liệu thống kê
50. Bài 2. Dùng bảng tính để tính các số đặc trưng của mẫu số liệu thống kê

PHẦN ĐẠI SỐ VÀ MỘT SỐ YẾU TỐ GIẢI TÍCH

51. Chương VII. BẤT PHƯƠNG TRÌNH BẬC HAI MỘT ẨN
52. Bài 1. Dấu của tam thức bậc hai 
53. Bài tập Bài 1
54. Bài 2. Giải bất phương trình bậc hai một ẩn
55. Bài tập Bài 2
56. Bài 3. Phương trình quy về phương trình bậc hai
57. Bài tập Bài 3
58. Bài tập cuối Chương VII

59. Chương VIII. ĐẠI SỐ TỔ HỢP 
60. Bài 1. Quy tắc cộng và quy tắc nhân 
61. Bài tập Bài 1
62. Bài 2. Hoán vị, chỉnh hợp và tổ hợp 
63. Bài tập Bài 2
64. Bài 3. Nhị thức Newton
65. Bài tập Bài 3
66. Bài tập cuối Chương VIII

PHẦN HÌNH HỌC VÀ ĐO LƯỜNG

67. Chương IX. PHƯƠNG PHÁP TỌA ĐỘ TRONG MẶT PHẲNG
68. Bài 1. TỌa độ của véc-tơ 
69. Bài tập Bài 1
70. Bài 2. Đường thẳng trong mặt phẳng tọa độ 
71. Bài tập Bài 2
72. Bài 3. Đường tròn trong mặt phẳng tọa độ 
73. Bài tập Bài 3
74. Bài 4. Ba đường conic trong mặt phẳng tọa độ 
75. Bài tập Bài 4
76. Bài tập cuối Chương IX

PHẦN THỐNG KÊ VÀ XÁC SUẤT 

77. Chương X. XÁC SUẤT 
78. Bài 1. Không gian mẫu và biến cố 
79. Bài tập Bài 1
80. Bài 2. Xác suất của biến cố 
81. Bài tập Bài 2
82. Bài tập cuối Chương X

HOẠT ĐỘNG THỰC HÀNH VÀ TRẢI NGHIỆM 

83. Bài 1. Vẽ đồ thị hàm số bậc hai bằng phần mềm GeoGebra
84. Bài 2. Vẽ ba đường conic bằng phần mềm GeoGebra

---

# LỚP 11

## BỘ CÁNH DIỀU

1. *Chương I. Hàm số lượng giác và phương trình lượng giác* - Bài 1. Góc lượng giác. Giá trị lượng giác của góc lượng giác  
2. Bài tập Bài 1
3. Bài 2. Các phép biến đổi lượng giác
4. Bài tập Bài 2
5. Bài 3. Hàm số lượng giác và đồ thị 
6. Bài tập Bài 3
7. Bài 4. Phương trình lượng giác cơ bản
8. Bài tập Bài 4
9. Bài tập cuối Chương I

10. *Chương II. Dãy số. Cấp số cộng và cấp số nhân* - Bài 1. Dãy số
11. Bài tập Bài 1
12. Bài 2. Cấp số cộng
13. Bài tập bài 2
14. Bài 3. Cấp số nhân
15. Bài tập Bài 3
16. Bài tập cuối Chương II

17. *Chương III. Giới hạn. Hàm số liên tục* - Bài 1. Giới hạn của dãy số 
18. Bài tập Bài 1
19. Bài 2. Giới hạn của hàm số
20. Bài tập Bài 2
21. Bài 3. Hàm số liên tục 
22. Bài tập Bài 3
23. Bài tập cuối Chương III

24. *Hoạt động thực hành và trải nghiệm* - Chủ đề 1. Một số hình thức đầu tư tài chính

25. *Chương IV. Đường thẳng và mặt phẳng trong không gian. Quan hệ song song* - Bài 1. Đường thẳng và mặt phẳng trong không gian 
26. Bài tập Bài 1
27. Bài 2. Hai đường thẳng song song trong không gian
28. Bài tập Bài 2
29. Bài 3. Đường thẳng và mặt phẳng song song
30. Bài tập Bài 3
31. Bài 4. Hai mặt phẳng song song 
32. Bài tập Bài 4
33. Bài 5. Hình lăng trụ và hình hộp
34. Bài tập Bài 5
35. Bài 6. Phép chiếu song song. Hình biểu diễn của một hình không gian 
36. Bài tập Bài 6
37. Bài tập cuối Chương IV

38. *Chương V. Một số yếu tố thống kê và xác suất* - Bài 1. Các số đặc trưng đo xu thế trung tâm cho mẫu số liệu ghép nhóm

39. Bài tập Bài 1
40. Biến cố hợp và biến cố giao. Biến cố độc lập. Các quy tắc tính xác suất
41. Bài tập Bài 2
43. Bài tập cuối Chương V

44. *Chương VI. Hàm số mũ và hàm số lôgarit* - Bài 1. Phép tính lũy thừa với số mũ thực
45. Bài tập Bài 1
46. Bài 2. Phép tính lôgarit
47. Bài tập Bài 2
48. Bài 3. Hàm số mũ. Hàm số lôgarit
49. Bài tập Bài 3
50. Bài 4. Phương trình, bất phương trình mũ và lôgarit
51. Bài tập Bài 4
52. Bài tập cuối Chương VI

53. *Chương VII. Đạo hàm* - Bài 1. Định nghĩa đạo hàm. Ý nghĩa hình học của đạo hàm
54. Bài tập Bài 1
55. Bài 2. Các quy tắc tính đạo hàm 
56. Bài tập Bài 2
57. Bài 3. Đạo hàm cấp hai
58. Bài tập Bài 3
59. Bài tập cuối Chương VII

60. *Chương VIII. Quan hệ vuông góc trong không gian. Phép chiếu vuông góc* - Bài 1. Hai đường thẳng vuông góc 
61. Bài tập Bài 1
62. Bài 2. Đường thẳng vuông góc với mặt phẳng 
63. Bài tập Bài 2
64. Bài 3. Góc giữa đường thẳng với mặt phẳng. Góc nhị diện
65. Bài tập Bài 3
66. Bài 4. Hai mặt phẳng vuông góc 
67. Bài tập Bài 4
68. Bài 5. Khoảng cách
69. Bài tập Bài 5
70. Bài 6. Hình lăng trụ đứng. Hình chóp đều. Thể tích của một số hình khối
71. Bài tập Bài 6
72. Bài tập cuối Chương VIII

73. *Hoạt động thực hành và trải nghiệm* - Chủ đề 2. Tính thể tích một số hình khối trong thực tiễn

74. Thực hành phần mềm Geogebra




